### ISSUE TITLE
GOOGLE Cookies部分也放了 請問是放錯嗎?

### ISSUE THREAD

**Issue by qwe3410475** [miyouzi/aniGamerPlus#1]
PS D:\Users\Desktop\aniGamerPlus-5.0> python aniGamerPlus.py -s 11364 -e 1
當前aniGamerPlus版本: v5.0
使用命令行模式, 文件將保存在配置文件中指定的目錄下:
    D:\Users\Desktop\aniGamerPlus-5.0\bangumi
未设定下载清晰度, 将使用配置文件指定的清晰度: 1080P
當前下載模式: 下載本番劇指定劇集

Traceback (most recent call last):
  File "aniGamerPlus.py", line 317, in <module>
    __cui(arg.sn, resolution, download_mode, thread_limit, download_episodes, save_dir)
  File "aniGamerPlus.py", line 219, in __cui
    anime = Anime(sn)
  File "D:\Users\Desktop\aniGamerPlus-5.0\Anime.py", line 20, in __init__
    self._cookies = Config.read_cookies()
  File "D:\Users\Desktop\aniGamerPlus-5.0\Config.py", line 91, in read_cookies
    cookies = f.readline()
  File "D:\Tool\Python\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 39: invalid start byte

**Comment by miyouzi** [comment]
這個是Cookie文件編碼錯誤, 請確認使用 UTF-8 無 BOM 編碼保存, 編輯器不建議使用 Windows 自帶記事本編輯, 建議使用 [notepad++](https://notepad-plus-plus.org/) 進行編輯.
Cookie僅需要巴哈的就行, 其他站不需要.

**Comment by qwe3410475** [comment]
![image](https://user-images.githubusercontent.com/46574011/51034521-fbedc780-15e1-11e9-8568-f9cb74468741.png)

使用這個外掛複製後直接貼上?
![image](https://user-images.githubusercontent.com/46574011/51034476-db257200-15e1-11e9-8a8f-f9b9056df5af.png)

**Comment by miyouzi** [comment]
額, 和設計的格式不一樣, 設計是cookie從這裏獲取.
![whereiscookie](https://user-images.githubusercontent.com/24269465/51034722-9e0daf80-15e2-11e9-8901-50a823458d7e.png)

複製過來直接貼上, 像是這樣
![](https://user-images.githubusercontent.com/24269465/51034836-fb096580-15e2-11e9-8302-1348b5da4fe6.png)

**Comment by qwe3410475** [comment]
原來是截錯 
感謝 可以了
