### ISSUE TITLE
在未登入前可正常下載，登入cookie後屢次失敗

### ISSUE THREAD

**Issue by Howard890222** [miyouzi/aniGamerPlus#100]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#
在未登入前可正常下載，登入cookie後屢次失敗
如將cookie內容刪至和說明一樣，則顯示非VIP帳號
## 錯誤截圖
#在這裏附上錯誤的窗口截圖#
![image](https://user-images.githubusercontent.com/81023237/111870696-2d802b80-89c1-11eb-97c7-a3b74ad66a7e.png)

## config.json 配置
```
#將你的config.json内容複製到這裏#
```
{
    "bangumi_dir": "",
    "temp_dir": "",
    "classify_bangumi": true,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36",
    "use_proxy": false,
    "proxy": "http://user:passwd@example.com:1000",
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "msg_argument_name": "message",
        "message_suffix": "追加的資訊",
        "query": [
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
        ]
    },
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": false,
    "danmu": false,
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "mobile_ads_time": 3,
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 15.1,
    "database_version": 2.0
}
## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```19849 all # 進擊的巨人 The Final Season [1]

**最好上傳 log 檔案**
[2021-03-20.log](https://github.com/miyouzi/aniGamerPlus/files/6175618/2021-03-20.log)

**Comment by gimi65536** [comment]
我本來也遇到同樣的問題，後來才想起cookie可能藏有中文字（巴哈暱稱）
把cookie裡頭暱稱的訊息刪除

`BAHANICK=ooxx;`
以及
`MB_BAHANICK=ooxx;`
都去掉，應該就正常了

**Comment by Howard890222** [comment]
我把chrome退回86版，再從抓一次cookie也就正常了

**Comment by yxh0** [comment]
> 我本來也遇到同樣的問題，後來才想起cookie可能藏有中文字（巴哈暱稱）
> 把cookie裡頭暱稱的訊息刪除
> 
> `BAHANICK=ooxx;`
> 以及
> `MB_BAHANICK=ooxx;`
> 都去掉，應該就正常了

太感谢了,已经成功了,我也是因为带了中文Unicode的字符导致出错的

**Comment by miyouzi** [comment]
我用的 Chrome 版本是 91.0.4472.164，拿到的是 URLEncode 過的字符，你們是直接的中文？

**Comment by gimi65536** [comment]
> 我用的 Chrome 版本是 91.0.4472.164，拿到的是 URLEncode 過的字符，你們是直接的中文？

如果是在開發者工具裡頭的欄位右鍵選`Copy value`的話，Chrome會「貼心地」自動decode後再存到剪貼簿，所以會看到中文等符號
如果是用一般的方法，選取後複製，就會是如同所見的百分比編碼

**Comment by miyouzi** [comment]
https://github.com/miyouzi/aniGamerPlus/releases/tag/v22.1  嘗試新版本看看，新增了自動轉碼
