### ISSUE TITLE
關於視頻檔案名稱的重命名功能

### ISSUE THREAD

**Issue by pipixia244** [miyouzi/aniGamerPlus#102]
## 問題描述
是否可以提供視頻檔案名稱的重命名功能

比如設置參數 %name% 為番劇名稱，%season%為季，%episode%為集數等，進行視頻資料的重命名

目的：使用emby刮削視頻檔案時，如果以[02]的集數命名則無法正確識別到標題和元數據等檔案，因此希望能夠將關鍵詞（名稱，集數）等重新組合。

同時，#94 也提到了檔案的重命名問題。

感謝作者這麽好的項目！

**Comment by miyouzi** [comment]
你這裏提到了季度提取問題，目前這個項目還沒有把季度分離出來，對於多季度的動畫，資料夾的結構你想是什麽樣的？把多季度的動畫放在以系列名命名的资料夹里？还是保持不变，只改 mp4 的檔名？

PS：另外，我的小夥伴目前也在針對 jellyfin（emby的開源fork，或許有兼容emby的可能）做適配中文動畫命名習慣的 metadata provider 插件，可以期待一下~

**Comment by pipixia244** [comment]
> 你這裏提到了季度提取問題，目前這個項目還沒有把季度分離出來，對於多季度的動畫，資料夾的結構你想是什麽樣的？把多季度的動畫放在以系列名命名的资料夹里？还是保持不变，只改 mp4 的檔名？
> 
> PS：另外，我的小夥伴目前也在針對 jellyfin（emby的開源fork，或許有兼容emby的可能）做適配中文動畫命名習慣的 metadata provider 插件，可以期待一下~

我覺得季度方面只要能被emby jellyfin plex之類的正確識別出就可以了，比如這樣的目錄結構
- <番劇名>
        - Season 1
                - xxxS01E01[1080P].mkv
        - Season 2
        - Specials
這樣應該就可以很好的識別了，或者單獨更改檔名也完全足夠，畢竟提這個issue的初衷只是因爲[01]這種集數無法被識別到而已，能這樣已經非常感謝了~

期待插件~

**Comment by ch010060** [comment]
@miyouzi 
請問現在動畫瘋是否沒有 季度 的metadata可以獲取?
看了一下code裡沒找著，巴哈網頁也沒看到
所以我自己寫了一版依照標題 第X季 來做PLEX重命名的功能
"X" 支援中文數字，例如 二、十一、二十一、二二
當然如果標題沒有寫季度就沒支援，例如 "進擊的巨人The Final Season"
如果這樣做OK我就丟PR了

具體如下圖:
![DEMO](https://s2.loli.net/2022/04/06/5d7jcfzqCEVDvM4.png)

**Comment by miyouzi** [comment]
v24.0 版本以上支持 #181
