### ISSUE TITLE
無法指定下載目錄

### ISSUE THREAD

**Issue by zacharyptt** [miyouzi/aniGamerPlus#104]
## 問題描述
更改bangumi_dir 執行命令行模式時，沒有套用路徑，一直都是使用預設路徑
印象中以前是可以設定成功的

使用Web 控制臺更改路徑後保存，查看config.json 一樣沒有更新
嘗試修改解析度，config.json裡面就是正常的

是哪裡壞了嗎？

**Comment by miyouzi** [comment]
提供下 config.json 和 log 檔案

**Comment by NiGHTsC** [comment]
同樣的問題，如果是硬碟主目錄的話就沒問題，但一加入夾子名稱就會重設
config.json
[](https://pastebin.com/rqQ53Fa3)
web.log
[](https://pastebin.com/MV4QmUBJ)

謝謝。

**Comment by miyouzi** [comment]
最新版本還有這個問題嗎？
