### ISSUE TITLE
抓取影片信息時發生未知錯誤，懇請協助

### ISSUE THREAD

**Issue by bmanex** [miyouzi/aniGamerPlus#106]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#
抓取影片跳出錯誤碼
## 錯誤截圖
#在這裏附上錯誤的窗口截圖#

## config.json 配置
```
#將你的config.json内容複製到這裏#
```
{
    "bangumi_dir": "E:\Anime",
    "temp_dir": "",
    "classify_bangumi": true,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": false,
    "default_download_mode": "all",
    "use_copyfile_method": false,
    "multi-thread": 5,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 5,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36 Edg/91.0.864.37",
    "use_proxy": false,
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "query": [
            "http://127.0.0.1:5700/send_group_msg?group_id=123456789"
        ],
        "message_suffix": "",
        "msg_argument_name": "message"
    },
    "faststart_movflags": false,
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 15.1,
    "database_version": 2.0,
    "audio_language": false,
    "proxy": "socks5://127.0.0.1:1080",
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "ads_time": 25,
    "danmu": false,
    "use_mobile_api": false,
    "mobile_ads_time": 3
}
## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```
18626 lastest  <咒術迴戰>
20561 lastest <約定的夢幻島 第二季>
20620 lastest  <無職轉生，到了異世界就拿出真本事>
20600 lastest  <轉生成蜘蛛又怎樣>
22227 lastest  <刮掉鬍子的我與撿到的女高中生>
22245 lastest  <86－不存在的戰區－>
22243 lastest  <持續狩獵史萊姆三百年，不知不覺就練到 LV MAX>
22235 lastest  <聖女魔力無所不能>
22378 lastest  <Vivy -Fluorite Eye's Song->

**最好上傳 log 檔案**
[2021-06-12.log](https://github.com/miyouzi/aniGamerPlus/files/6641754/2021-06-12.log)

**Comment by miyouzi** [comment]
使用源碼運行會有這個問題嗎？

**Comment by miyouzi** [comment]
可以看下這個 issue #100 ，cookie 中帶有中文名問題
