### ISSUE TITLE
VIP帳號，顯示為非VIP

### ISSUE THREAD

**Issue by Riridesu** [miyouzi/aniGamerPlus#110]
## 問題描述
大大您好，今天VIP到期，重新購買後就出問題了，
VIP帳號，顯示為非VIP，
原本因暱稱為中文導致影片搜索錯誤，後將暱稱改回英文，
使用Chrome 91版無痕模式重新取得cookie，並更新UA，仍舊顯示非VIP帳戶，但網頁觀看確認是沒有問題的

## 錯誤截圖
[https://i.imgur.com/W2Pn8Vj.jpg](url)

## config.json 配置
```
{
    "bangumi_dir": "",
    "temp_dir": "",
    "classify_bangumi": true,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": true,
    "default_download_mode": "all",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36",
    "use_proxy": false,
    "proxy": "http://user:passwd@example.com:1000",
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "msg_argument_name": "message",
        "message_suffix": "追加的資訊",
        "query": [
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
        ]
    },
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": false,
    "danmu": false,
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "mobile_ads_time": 3,
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 15.1,
    "database_version": 2.0
}
```

## sn_list.txt 配置
```
@2016
5872 all # 發條精靈戰記 天鏡的極北之星
@2019
13809 all # 入間同學入魔了
12584 all # 劇場版 夏目友人帳～緣結空蟬～
@2020
18215 all # 熊熊勇闖異世界
18369 all # 憂國的莫里亞蒂 第一季
@2021
22727 all # 持續狩獵史萊姆三百年，不知不覺就練到 LV MAX
22228 all # 轉生史萊姆日記
22700 all # 轉生成蜘蛛又怎樣！
22715 all # 真白之音
22811 all # 入間同學入魔了 第二季
22815 all # Vivy -Fluorite Eye's Song-
22733 all # 86－不存在的戰區－
22730 all # 不要欺負我，長瀞同學
22736 all # SHADOWS HOUSE-影宅-
22741 all # 戰鬥員派遣中！
22744 all # 憂國的莫里亞蒂 第一季 後半
22823 all # 刮掉鬍子的我與撿到的女高中生
22825 all # 燒窯的話也要馬克杯
22829 all # 給不滅的你
22839 all # 擾亂 THE PRINCESS OF SNOW AND BLOOD
22871 all # 本田小狼與我
22873 all # 義呆利 World Stars
20555 all # 搖曳露營△ 第二季
22842 all # 聖女魔力無所不能
22899 all # 夏目友人帳特別上映版：喚石與可疑訪客
23143 all # 七騎士：革命 -英雄的繼承者-
23288 all # 舞伎家的料理人
23103 all # 佐賀偶像是傳奇 捲土重來
23273 all # 緋紅結繫
23111 all # BLUE REFLECTION : 澪
23177 all # 水星領航員 ARIA THE AVVENIRE
23179 all # 青梅竹馬絕對不會輸的戀愛喜劇
22680 all # GIVEN 被贈與的未來 劇場版
23295 all # 工作細胞 特別上映版 - 強「菌」來襲！人體腸道大騷動！
23342 all # 桃子男孩渡海而來
23182 all # 奇蛋物語 Wonder Egg Priority
23493 all # 偵探已經，死了。
23376 all # 死神少爺與黑女僕
23363 all # RE-MAIN
23364 all # 現實主義勇者的王國重建記
23362 all # 魔法科高中的優等生
23375 all # 我們的重製人生
23381 all # 女朋友 and 女朋友
23350 all # 轉生成女性向遊戲只有毀滅 END 的壞人大小姐 X
23348 all # 瓦尼塔斯的手札
23338 all # 開掛藥師的異世界悠閒生活
23339 all # 月光下的異世界之旅
23346 all # 白沙的 Aquatope
```

**最好上傳 log 檔案**
[2021-07-19.log](https://github.com/miyouzi/aniGamerPlus/files/6837887/2021-07-19.log)

**Comment by miyouzi** [comment]
在動畫瘋網頁打開一個影片，按 F12 ，在左上角搜索框輸入 `token` ，點擊鏈接，在右邊的區域點擊 `Preview` 選項卡，看一下内容

![image](https://user-images.githubusercontent.com/24269465/126108647-9ee7365f-4a73-49e5-9058-5ca4f75ac1c0.png)

**Comment by Riridesu** [comment]
> 在動畫瘋網頁打開一個影片，按 F12 ，在左上角搜索框輸入 `token` ，點擊鏈接，在右邊的區域點擊 `Preview` 選項卡，看一下内容
> 
> ![image](https://user-images.githubusercontent.com/24269465/126108647-9ee7365f-4a73-49e5-9058-5ca4f75ac1c0.png)

跟大大顯示的是一樣的，確實是VIP
![螢幕擷取畫面 2021-07-19 141730](https://user-images.githubusercontent.com/87630859/126111859-982c85b2-8732-4d85-91d6-16f43b8f2a10.jpg)

**Comment by miyouzi** [comment]
用源碼運行試看看呢？

**Comment by coeusym** [comment]
我也有這個問題 好像是更新後每次運行exe后cookie文件都會被修改掉

**Comment by Riridesu** [comment]
> 用源碼運行試看看呢？

抱歉，我不會用源碼運行，我研究看看
不過確實如樓上所講cookie文件內容會被修改成"ANIME_SIGN=031ef728a8c42a9bcb12d945932a3ca9a303edb2b046539160f4f939"

**Comment by miyouzi** [comment]
目前我用源碼運行尚沒有碰到這個情況，不是很好debug。

另外，log 裏面還有 `'latin-1' codec can't encode characters` 的錯誤，可以參考一下這個 issue #100

**Comment by Riridesu** [comment]
> 目前我用源碼運行尚沒有碰到這個情況，不是很好debug。
> 
> 另外，log 裏面還有 `'latin-1' codec can't encode characters` 的錯誤，可以參考一下這個 issue #100

恩，這個就是暱稱有中文的時候會出現的錯誤，後來我把巴哈暱稱改成英文再重新獲取一次cookie就好了
不過顯示非VIP的問題還是沒解決，我使用另一個動畫瘋下載工具"AniGamerV1.3"是可以正常下在1080P的，不過這個程式就是不太方便只能單集下載。

**Comment by Riridesu** [comment]
> > 目前我用源碼運行尚沒有碰到這個情況，不是很好debug。
> > 另外，log 裏面還有 `'latin-1' codec can't encode characters` 的錯誤，可以參考一下這個 issue #100
> 
> 恩，這個就是暱稱有中文的時候會出現的錯誤，後來我把巴哈暱稱改成英文再重新獲取一次cookie就好了
> 不過顯示非VIP的問題還是沒解決，我使用另一個動畫瘋下載工具"AniGamerV1.3"是可以正常下在1080P的，不過這個程式就是不太方便只能單集下載。

原本暱稱有中文時會顯示吳

**Comment by coeusym** [comment]
> > 目前我用源碼運行尚沒有碰到這個情況，不是很好debug。
> > 另外，log 裏面還有 `'latin-1' codec can't encode characters` 的錯誤，可以參考一下這個 issue #100
> 
> 恩，這個就是暱稱有中文的時候會出現的錯誤，後來我把巴哈暱稱改成英文再重新獲取一次cookie就好了
> 不過顯示非VIP的問題還是沒解決，我使用另一個動畫瘋下載工具"AniGamerV1.3"是可以正常下載1080P的，不過這個程式就是不太方便只能單集下載。

我的巴哈id也是英文的 然後我在cookie裏把英文id刪了就又能識別出vip了 很神奇

**Comment by Riridesu** [comment]
> > > 目前我用源碼運行尚沒有碰到這個情況，不是很好debug。
> > > 另外，log 裏面還有 `'latin-1' codec can't encode characters` 的錯誤，可以參考一下這個 issue #100
> > 
> > 
> > 恩，這個就是暱稱有中文的時候會出現的錯誤，後來我把巴哈暱稱改成英文再重新獲取一次cookie就好了
> > 不過顯示非VIP的問題還是沒解決，我使用另一個動畫瘋下載工具"AniGamerV1.3"是可以正常下載1080P的，不過這個程式就是不太方便只能單集下載。
> 
> 我的巴哈id也是英文的 然後我在cookie裏把英文id刪了就又能識別出vip了 很神奇

WOW，真的成功了，刪掉BAHANICK這段就成功識別VIP了

**Comment by BraveSail** [comment]
> > > > 目前我用源碼運行尚沒有碰到這個情況，不是很好debug。
> > > > 另外，log 裏面還有 `'latin-1' codec can't encode characters` 的錯誤，可以參考一下這個 issue #100
> > > 
> > > 
> > > 恩，這個就是暱稱有中文的時候會出現的錯誤，後來我把巴哈暱稱改成英文再重新獲取一次cookie就好了
> > > 不過顯示非VIP的問題還是沒解決，我使用另一個動畫瘋下載工具"AniGamerV1.3"是可以正常下載1080P的，不過這個程式就是不太方便只能單集下載。
> > 
> > 
> > 我的巴哈id也是英文的 然後我在cookie裏把英文id刪了就又能識別出vip了 很神奇
> 
> WOW，真的成功了，刪掉BAHANICK這段就成功識別VIP了

我这边还是不行，删除了所有key只剩下BAHARUNE可以了

**Comment by BraveSail** [comment]
目前看来只要有BAHARUNE就可以，但是不清楚程序在自动续cookie的时候是否会重写其他参数导致再次失败

**Comment by miyouzi** [comment]
我這邊複現了，預計今晚修復

**Comment by miyouzi** [comment]
https://github.com/miyouzi/aniGamerPlus/releases/tag/v22.1  嘗試新版本看看

**Comment by Riridesu** [comment]
> 我這邊複現了，預計今晚修復

新版已可識別cookie，辛苦了!!

另外想請教大大，如果不想讓更新後的程式重新下載所有檔案該怎麼做呢？
因為更新後他會重新讀取SNLIST並重新下載全部檔案，即使bangumi資料夾中已經有檔案仍會在重新下載一次

**Comment by miyouzi** [comment]
> > 我這邊複現了，預計今晚修復
> 
> 新版已可識別cookie，辛苦了!!
> 
> 另外想請教大大，如果不想讓更新後的程式重新下載所有檔案該怎麼做呢？
> 因為更新後他會重新讀取SNLIST並重新下載全部檔案，即使bangumi資料夾中已經有檔案仍會在重新下載一次

任務狀態記錄在 `aniGamer.db` 你看下這個檔案在不在

**Comment by Riridesu** [comment]
> > > 我這邊複現了，預計今晚修復
> > 
> > 
> > 新版已可識別cookie，辛苦了!!
> > 另外想請教大大，如果不想讓更新後的程式重新下載所有檔案該怎麼做呢？
> > 因為更新後他會重新讀取SNLIST並重新下載全部檔案，即使bangumi資料夾中已經有檔案仍會在重新下載一次
> 
> 任務狀態記錄在 `aniGamer.db` 你看下這個檔案在不在

有了，感謝大大~

**Comment by RyanL-29** [comment]
![image](https://user-images.githubusercontent.com/48479346/126637970-831f5741-12bd-4204-92bb-0c137e6cb3ba.png)

知道什麼問題新版好像無法更新 cookie

> https://github.com/miyouzi/aniGamerPlus/releases/tag/v22.1 嘗試新版本看看
