### ISSUE TITLE
最新版无法正常使用

### ISSUE THREAD

**Issue by YFTX2015** [miyouzi/aniGamerPlus#113]
## 問題描述
按照上个版本的配置，重新抓了cookie，重新安装了依赖，然而不管是exe，还是命令行，均出现如下图所示的情况，无法加载出任何内容。

## 錯誤截圖
![屏幕截图(5)](https://user-images.githubusercontent.com/12757305/126402862-ea9bdba9-cafe-4df0-bb0c-94af60ed3309.png)
![屏幕截图(7)](https://user-images.githubusercontent.com/12757305/126402877-84a5a55e-2528-4ed1-9dc3-564ed20e7687.png)

## config.json 配置
```
#將你的config.json内容複製到這裏#
{
    "bangumi_dir": "C:\\Users\\YFTX2\\视频",
    "temp_dir": "",
    "classify_bangumi": false,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": false,
    "default_download_mode": "largest-sn",
    "use_copyfile_method": false,
    "multi-thread": 5,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 5,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": false,
    "customized_video_filename_prefix": "",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "ts",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36",
    "use_proxy": false,
    "proxy": "http://127.0.0.1:7890",
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "msg_argument_name": "message",
        "message_suffix": "追加的資訊",
        "query": [
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
        ]
    },
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": true,
    "danmu": false,
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 0,
    "mobile_ads_time": 0,
    "use_dashboard": true,
    "dashboard": {
        "host": "0.0.0.0",
        "port": 5000,
        "SSL": true,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 15.2,
    "database_version": 2.0,
    "telebot_notify": false,
    "telebot_token": ""
}

## sn_list.txt 配置
23498

**最好上傳 log 檔案**
由于加载不出来任何内容，因此无log档案。

**Comment by miyouzi** [comment]
是不是更新访问 github 出了问题，你试试关闭检查更新`"check_latest_version": false`

**Comment by YFTX2015** [comment]
关了，还是不行

**Comment by miyouzi** [comment]
关闭杀毒软件呢？包括 Windows Defender ？

**Comment by RyanL-29** [comment]
Windows 11... ?.?  有可能本身os問題??

**Comment by miyouzi** [comment]
或者用源码运行吧，或者 Docker ，不过 Windows 上的 Docker 基于 HyperV，你还要用安卓模拟器的话，就只能用 HyperV 版本的蓝叠了

**Comment by YFTX2015** [comment]
晚上再试能出来内容了，不过是这样
![屏幕截图(8)](https://user-images.githubusercontent.com/12757305/126497584-996b12e8-a7aa-4fd5-9369-3d7e13aeb0a6.png)

**Comment by miyouzi** [comment]
关闭使用APP API 解析 `"use_mobile_api": false` 移动端的强制广告时间和Web没什么差别了，这个功能感觉没啥用了

**Comment by YFTX2015** [comment]
终于好了，多谢

**Comment by YFTX2015** [comment]
凌晨五点过试，又不行了，出来不了任何内容。感觉这个版本相当不稳定。

**Comment by YFTX2015** [comment]
挂了若干分钟后，信息总算出来了并显示已下载完成。但是这个版本为啥加载时间那么漫长？

**Comment by miyouzi** [comment]
同样的环境 v22.0 不会有这个问题是么？

**Comment by YFTX2015** [comment]
v22.0正常

**Comment by YFTX2015** [comment]
然后，刚才建了个任务，等了20分钟左右后出现如下图所示情况：
![屏幕截图(9)](https://user-images.githubusercontent.com/12757305/126578755-989289d9-6d75-4616-8d49-9524acc12e41.png)
这在v22.0不会发生

**Comment by RyanL-29** [comment]
> 然后，刚才建了个任务，等了20分钟左右后出现如下图所示情况：
> ![屏幕截图(9)](https://user-images.githubusercontent.com/12757305/126578755-989289d9-6d75-4616-8d49-9524acc12e41.png)
> 这在v22.0不会发生

https://github.com/RyanL-29/aniGamerPlus/releases/tag/22.1
你可以先試一下這個我自行編譯版本, 我這個裏面多了一個功能,

`"add_bangumi_name_to_video_meta": true, ` (把動漫的封面圖和介紹寫進影片meta)

你可以在 config.json 設置為false他那麼就和原本的版本沒有分別了

**Comment by RyanL-29** [comment]
> 然后，刚才建了个任务，等了20分钟左右后出现如下图所示情况：
> ![屏幕截图(9)](https://user-images.githubusercontent.com/12757305/126578755-989289d9-6d75-4616-8d49-9524acc12e41.png)
> 这在v22.0不会发生

https://github.com/RyanL-29/aniGamerPlus/releases/tag/22.1
你可以先試一下這個我自行編譯版本, 我這個裏面多了一個功能,

"add_bangumi_name_to_video_meta": true, (把動漫的封面圖和介紹寫進影片meta)

你可以在 config.json 設置為false他那麼就和原本的版本沒有分別了
