### ISSUE TITLE
最新版本無法正常使用

### ISSUE THREAD

**Issue by andy83527** [miyouzi/aniGamerPlus#116]
## 問題描述
下載版本22.1後執行exe檔後跑出參數錯誤後exe檔就自動關閉了

## 錯誤截圖
#在這裏附上錯誤的窗口截圖#
![2021-07-22_092009](https://user-images.githubusercontent.com/87789685/126578694-a3875a46-7a0b-42f3-adaf-5703c1c6b8e1.jpg)
## config.json 配置
```
#將你的config.json内容複製到這裏#
`{
    "bangumi_dir": "D:\\Anime",
    "temp_dir": "",
    "classify_bangumi": false,
    "check_frequency": 20,
    "download_resolution": "720",
    "lock_resolution": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 3,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 5,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36",
    "use_proxy": false,
    "proxy": "http://user:passwd@example.com:1000",
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "query": [
            "http://127.0.0.1:5700/send_group_msg?group_id=123456789"
        ],
        "message_suffix": "",
        "msg_argument_name": "message"
    },
    "faststart_movflags": false,
    "audio_language": false,
    "check_latest_version": false,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 10,
    "config_version": 15.1,
    "database_version": 2.0,
    "danmu": false,
    "use_mobile_api": false,
    "mobile_ads_time": 3
}`

## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```

**最好上傳 log 檔案**

**Comment by RyanL-29** [comment]
> ## 問題描述
> 下載版本22.1後執行exe檔後跑出參數錯誤後exe檔就自動關閉了
> 
> ## 錯誤截圖
> #在這裏附上錯誤的窗口截圖#
> ![2021-07-22_092009](https://user-images.githubusercontent.com/87789685/126578694-a3875a46-7a0b-42f3-adaf-5703c1c6b8e1.jpg)
> 
> ## config.json 配置
> ```
> #將你的config.json内容複製到這裏#
> `{
>     "bangumi_dir": "D:\\Anime",
>     "temp_dir": "",
>     "classify_bangumi": false,
>     "check_frequency": 20,
>     "download_resolution": "720",
>     "lock_resolution": false,
>     "default_download_mode": "latest",
>     "use_copyfile_method": false,
>     "multi-thread": 3,
>     "multi_upload": 3,
>     "segment_download_mode": true,
>     "multi_downloading_segment": 5,
>     "segment_max_retry": 8,
>     "add_bangumi_name_to_video_filename": true,
>     "add_resolution_to_video_filename": true,
>     "customized_video_filename_prefix": "【動畫瘋】",
>     "customized_bangumi_name_suffix": "",
>     "customized_video_filename_suffix": "",
>     "video_filename_extension": "mp4",
>     "zerofill": 1,
>     "ua": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36",
>     "use_proxy": false,
>     "proxy": "http://user:passwd@example.com:1000",
>     "upload_to_server": false,
>     "ftp": {
>         "server": "",
>         "port": "",
>         "user": "",
>         "pwd": "",
>         "tls": true,
>         "cwd": "",
>         "show_error_detail": false,
>         "max_retry_num": 15
>     },
>     "user_command": "shutdown -s -t 60",
>     "coolq_notify": false,
>     "coolq_settings": {
>         "query": [
>             "http://127.0.0.1:5700/send_group_msg?group_id=123456789"
>         ],
>         "message_suffix": "",
>         "msg_argument_name": "message"
>     },
>     "faststart_movflags": false,
>     "audio_language": false,
>     "check_latest_version": false,
>     "read_sn_list_when_checking_update": true,
>     "read_config_when_checking_update": true,
>     "ads_time": 25,
>     "use_dashboard": true,
>     "dashboard": {
>         "host": "127.0.0.1",
>         "port": 5000,
>         "SSL": false,
>         "BasicAuth": false,
>         "username": "admin",
>         "password": "admin"
>     },
>     "save_logs": true,
>     "quantity_of_logs": 10,
>     "config_version": 15.1,
>     "database_version": 2.0,
>     "danmu": false,
>     "use_mobile_api": false,
>     "mobile_ads_time": 3
> }`
> 
> ## sn_list.txt 配置
> ```
> 
> #將你的sn_list.txt内容複製到這裏#
> 
> ```
> 
> **最好上傳 log 檔案**
> ```

https://github.com/RyanL-29/aniGamerPlus/releases/tag/22.1
你可以先試一下這個我自行編譯版本, 我這個裏面多了一個功能, 

`"add_bangumi_name_to_video_meta": true,`  (把動漫的封面圖和介紹寫進影片meta)

你可以在 config.json 關閉他那麼就和原本的版本沒有分別了

**Comment by andy83527** [comment]
![2021-07-22_125203](https://user-images.githubusercontent.com/87789685/126591446-44857327-50e6-4898-a3dc-fc18f36727d7.jpg)


> > ## 問題描述
> > 下載版本22.1後執行exe檔後跑出參數錯誤後exe檔就自動關閉了
> > ## 錯誤截圖
> > #在這裏附上錯誤的窗口截圖#
> > ![2021-07-22_092009](https://user-images.githubusercontent.com/87789685/126578694-a3875a46-7a0b-42f3-adaf-5703c1c6b8e1.jpg)
> > ## config.json 配置
> > ```
> > #將你的config.json内容複製到這裏#
> > `{
> >     "bangumi_dir": "D:\\Anime",
> >     "temp_dir": "",
> >     "classify_bangumi": false,
> >     "check_frequency": 20,
> >     "download_resolution": "720",
> >     "lock_resolution": false,
> >     "default_download_mode": "latest",
> >     "use_copyfile_method": false,
> >     "multi-thread": 3,
> >     "multi_upload": 3,
> >     "segment_download_mode": true,
> >     "multi_downloading_segment": 5,
> >     "segment_max_retry": 8,
> >     "add_bangumi_name_to_video_filename": true,
> >     "add_resolution_to_video_filename": true,
> >     "customized_video_filename_prefix": "【動畫瘋】",
> >     "customized_bangumi_name_suffix": "",
> >     "customized_video_filename_suffix": "",
> >     "video_filename_extension": "mp4",
> >     "zerofill": 1,
> >     "ua": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36",
> >     "use_proxy": false,
> >     "proxy": "http://user:passwd@example.com:1000",
> >     "upload_to_server": false,
> >     "ftp": {
> >         "server": "",
> >         "port": "",
> >         "user": "",
> >         "pwd": "",
> >         "tls": true,
> >         "cwd": "",
> >         "show_error_detail": false,
> >         "max_retry_num": 15
> >     },
> >     "user_command": "shutdown -s -t 60",
> >     "coolq_notify": false,
> >     "coolq_settings": {
> >         "query": [
> >             "http://127.0.0.1:5700/send_group_msg?group_id=123456789"
> >         ],
> >         "message_suffix": "",
> >         "msg_argument_name": "message"
> >     },
> >     "faststart_movflags": false,
> >     "audio_language": false,
> >     "check_latest_version": false,
> >     "read_sn_list_when_checking_update": true,
> >     "read_config_when_checking_update": true,
> >     "ads_time": 25,
> >     "use_dashboard": true,
> >     "dashboard": {
> >         "host": "127.0.0.1",
> >         "port": 5000,
> >         "SSL": false,
> >         "BasicAuth": false,
> >         "username": "admin",
> >         "password": "admin"
> >     },
> >     "save_logs": true,
> >     "quantity_of_logs": 10,
> >     "config_version": 15.1,
> >     "database_version": 2.0,
> >     "danmu": false,
> >     "use_mobile_api": false,
> >     "mobile_ads_time": 3
> > }`
> > 
> > ## sn_list.txt 配置
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > #將你的sn_list.txt内容複製到這裏#
> > ```
> > 
> > **最好上傳 log 檔案**
> > ```
> 
> https://github.com/RyanL-29/aniGamerPlus/releases/tag/22.1
> 你可以先試一下這個我自行編譯版本, 我這個裏面多了一個功能,
> 
> `"add_bangumi_name_to_video_meta": true,` (把動漫的封面圖和介紹寫進影片meta)
> 
> 你可以在 config.json 設置為false他那麼就和原本的版本沒有分別了

![2021-07-22_125203](https://user-images.githubusercontent.com/87789685/126591467-3ee10287-ee62-4176-ac56-463126725933.jpg)
能夠正常跑了
不過還是吃不到cookie

**Comment by miyouzi** [comment]
提供一下 Log

**Comment by RyanL-29** [comment]
> ![2021-07-22_125203](https://user-images.githubusercontent.com/87789685/126591446-44857327-50e6-4898-a3dc-fc18f36727d7.jpg)
> 
> > > ## 問題描述
> > > 下載版本22.1後執行exe檔後跑出參數錯誤後exe檔就自動關閉了
> > > ## 錯誤截圖
> > > #在這裏附上錯誤的窗口截圖#
> > > ![2021-07-22_092009](https://user-images.githubusercontent.com/87789685/126578694-a3875a46-7a0b-42f3-adaf-5703c1c6b8e1.jpg)
> > > ## config.json 配置
> > > ```
> > > #將你的config.json内容複製到這裏#
> > > `{
> > >     "bangumi_dir": "D:\\Anime",
> > >     "temp_dir": "",
> > >     "classify_bangumi": false,
> > >     "check_frequency": 20,
> > >     "download_resolution": "720",
> > >     "lock_resolution": false,
> > >     "default_download_mode": "latest",
> > >     "use_copyfile_method": false,
> > >     "multi-thread": 3,
> > >     "multi_upload": 3,
> > >     "segment_download_mode": true,
> > >     "multi_downloading_segment": 5,
> > >     "segment_max_retry": 8,
> > >     "add_bangumi_name_to_video_filename": true,
> > >     "add_resolution_to_video_filename": true,
> > >     "customized_video_filename_prefix": "【動畫瘋】",
> > >     "customized_bangumi_name_suffix": "",
> > >     "customized_video_filename_suffix": "",
> > >     "video_filename_extension": "mp4",
> > >     "zerofill": 1,
> > >     "ua": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36",
> > >     "use_proxy": false,
> > >     "proxy": "http://user:passwd@example.com:1000",
> > >     "upload_to_server": false,
> > >     "ftp": {
> > >         "server": "",
> > >         "port": "",
> > >         "user": "",
> > >         "pwd": "",
> > >         "tls": true,
> > >         "cwd": "",
> > >         "show_error_detail": false,
> > >         "max_retry_num": 15
> > >     },
> > >     "user_command": "shutdown -s -t 60",
> > >     "coolq_notify": false,
> > >     "coolq_settings": {
> > >         "query": [
> > >             "http://127.0.0.1:5700/send_group_msg?group_id=123456789"
> > >         ],
> > >         "message_suffix": "",
> > >         "msg_argument_name": "message"
> > >     },
> > >     "faststart_movflags": false,
> > >     "audio_language": false,
> > >     "check_latest_version": false,
> > >     "read_sn_list_when_checking_update": true,
> > >     "read_config_when_checking_update": true,
> > >     "ads_time": 25,
> > >     "use_dashboard": true,
> > >     "dashboard": {
> > >         "host": "127.0.0.1",
> > >         "port": 5000,
> > >         "SSL": false,
> > >         "BasicAuth": false,
> > >         "username": "admin",
> > >         "password": "admin"
> > >     },
> > >     "save_logs": true,
> > >     "quantity_of_logs": 10,
> > >     "config_version": 15.1,
> > >     "database_version": 2.0,
> > >     "danmu": false,
> > >     "use_mobile_api": false,
> > >     "mobile_ads_time": 3
> > > }`
> > > 
> > > ## sn_list.txt 配置
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > #將你的sn_list.txt内容複製到這裏#
> > > ```
> > > 
> > > **最好上傳 log 檔案**
> > > ```
> > 
> > 
> > https://github.com/RyanL-29/aniGamerPlus/releases/tag/22.1
> > 你可以先試一下這個我自行編譯版本, 我這個裏面多了一個功能,
> > `"add_bangumi_name_to_video_meta": true,` (把動漫的封面圖和介紹寫進影片meta)
> > 你可以在 config.json 設置為false他那麼就和原本的版本沒有分別了
> 
> ![2021-07-22_125203](https://user-images.githubusercontent.com/87789685/126591467-3ee10287-ee62-4176-ac56-463126725933.jpg)
> 能夠正常跑了
> 不過還是吃不到cookie

你看一下你的 cookie.txt 是否變成了 invalid_cookie.txt

**Comment by andy83527** [comment]
![2021-07-23_083244](https://user-images.githubusercontent.com/87789685/126725117-d76791c4-52f2-4cbe-a9cd-4ac4f84b24e1.jpg)
cookie重抓後ok了
感謝各位

**Comment by Riridesu** [comment]
> 提供一下 Log

我也是新版的試用這一兩天下來，常常會顯示cookie更新失敗，轉為遊客帳戶
重抓新的cookie就會恢復正常

[2021-07-23.log](https://github.com/miyouzi/aniGamerPlus/files/6867132/2021-07-23.log)

**Comment by RyanL-29** [comment]
> > 提供一下 Log
> 
> 我也是新版的試用這一兩天下來，常常會顯示cookie更新失敗，轉為遊客帳戶
> 重抓新的cookie就會恢復正常
> 
> ![螢幕擷取畫面 2021-07-23 152046](https://user-images.githubusercontent.com/87630859/126749447-3d036a43-ea82-4390-a8ed-ac00cb20cb79.jpg)

我也有一樣的情況

**Comment by YFTX2015** [comment]
隔了几天没用，今天用时又出现了双击exe不出现任何内容的情况。无痕cookie与ua都更新过，其它配置与之前一样。

**Comment by miyouzi** [comment]
@YFTX2015 提供一下程序版本和操作系统版本

**Comment by YFTX2015** [comment]
22.3
![屏幕截图(14)](https://user-images.githubusercontent.com/12757305/127958525-5267e293-f15b-4ba7-96d8-c2b2da1a4690.png)
