### ISSUE TITLE
遺失api-ms-win-crt-runtime-l1-1-0-dll

### ISSUE THREAD

**Issue by Ediny0116** [miyouzi/aniGamerPlus#117]
## 問題描述
遺失api-ms-win-crt-runtime-l1-1-0-dll
22.0版本沒遇到該問題
嘗試過該影片方法仍無法修復https://www.youtube.com/watch?v=JXBTUfx7HWc
## 錯誤截圖
![未命名](https://user-images.githubusercontent.com/87802953/126609833-4545fc1e-ab3b-4fea-8b3b-61fd9dcebd96.jpg)

## config.json 配置
```
{
    "bangumi_dir": "",
    "temp_dir": "",
    "classify_bangumi": true,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36",
    "use_proxy": false,
    "proxy": "http://user:passwd@example.com:1000",
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "msg_argument_name": "message",
        "message_suffix": "追加的資訊",
        "query": [
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
        ]
    },
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": false,
    "danmu": false,
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
	"mobile_ads_time": 3,
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 13.0,
    "database_version": 2.0
}
```

**Comment by RyanL-29** [comment]
> ## 問題描述
> 遺失api-ms-win-crt-runtime-l1-1-0-dll
> 22.0版本沒遇到該問題
> 嘗試過該影片方法仍無法修復https://www.youtube.com/watch?v=JXBTUfx7HWc
> 
> ## 錯誤截圖
> ![未命名](https://user-images.githubusercontent.com/87802953/126609833-4545fc1e-ab3b-4fea-8b3b-61fd9dcebd96.jpg)
> 
> ## config.json 配置
> ```
> {
>     "bangumi_dir": "",
>     "temp_dir": "",
>     "classify_bangumi": true,
>     "check_frequency": 5,
>     "download_resolution": "1080",
>     "lock_resolution": false,
>     "default_download_mode": "latest",
>     "use_copyfile_method": false,
>     "multi-thread": 1,
>     "multi_upload": 3,
>     "segment_download_mode": true,
>     "multi_downloading_segment": 2,
>     "segment_max_retry": 8,
>     "add_bangumi_name_to_video_filename": true,
>     "add_resolution_to_video_filename": true,
>     "customized_video_filename_prefix": "【動畫瘋】",
>     "customized_bangumi_name_suffix": "",
>     "customized_video_filename_suffix": "",
>     "video_filename_extension": "mp4",
>     "zerofill": 1,
>     "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36",
>     "use_proxy": false,
>     "proxy": "http://user:passwd@example.com:1000",
>     "upload_to_server": false,
>     "ftp": {
>         "server": "",
>         "port": "",
>         "user": "",
>         "pwd": "",
>         "tls": true,
>         "cwd": "",
>         "show_error_detail": false,
>         "max_retry_num": 15
>     },
>     "user_command": "shutdown -s -t 60",
>     "coolq_notify": false,
>     "coolq_settings": {
>         "msg_argument_name": "message",
>         "message_suffix": "追加的資訊",
>         "query": [
>             "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
>             "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
>         ]
>     },
>     "faststart_movflags": false,
>     "audio_language": false,
>     "use_mobile_api": false,
>     "danmu": false,
>     "check_latest_version": true,
>     "read_sn_list_when_checking_update": true,
>     "read_config_when_checking_update": true,
>     "ads_time": 25,
> 	"mobile_ads_time": 3,
>     "use_dashboard": true,
>     "dashboard": {
>         "host": "127.0.0.1",
>         "port": 5000,
>         "SSL": false,
>         "BasicAuth": false,
>         "username": "admin",
>         "password": "admin"
>     },
>     "save_logs": true,
>     "quantity_of_logs": 7,
>     "config_version": 13.0,
>     "database_version": 2.0
> }
> ```

可以嘗試一下使用管理員權限開啟cmd然後在裏面輸入

sfc /scannow

如果上面那個沒有偵測到錯誤的話是用下面的這個指令

dism /online /cleanup-image /restorehealth

完成所有後請重啟電腦, 然後嘗試再次啟動程式

**Comment by miyouzi** [comment]
@RyanL-29 http://www.zkea.net/codesnippet/detail/python-pyinstaller-missing-api-ms-win-core-path-l1-1-0-dll.html

看到了這篇文章，似乎是 Python3.9 不支援 Win7 的問題，我目前先降級 Python 編譯吧（再找個時間看能不能用Github Actions自動打包）

**Comment by RyanL-29** [comment]
> @RyanL-29 http://www.zkea.net/codesnippet/detail/python-pyinstaller-missing-api-ms-win-core-path-l1-1-0-dll.html
> 
> 看到了這篇文章，似乎是 Python3.9 不支援 Win7 的問題，我目前先降級 Python 編譯吧（再找個時間看能不能用Github Actions自動打包）

辛苦你了

**Comment by miyouzi** [comment]
嘗試 v22.2 版本看看

**Comment by Ediny0116** [comment]
抱歉這麼晚回覆，更新後已經沒問題了，非常感謝。
