### ISSUE TITLE
新增 aniGamerPlus .exe 單集下載功能

### ISSUE THREAD

**Issue by ycs77** [miyouzi/aniGamerPlus#12]
有不少用戶都有在問「aniGamerPlus .exe 的單集下載功能」功能，請問 @miyouzi 可否新增此功能?

**Comment by miyouzi** [comment]
單集下載功能設計是用命令行模式去實現的。
有計劃做Web控制臺，但目前還挺遙遠的。

**Comment by ycs77** [comment]
又或者新增另一種模式：
每一個 sn 碼都對應一集動畫，可以指定一個 sn 碼時，就下載該集影片?

**Comment by miyouzi** [comment]
這個功能命令行模式有實現，或者說命令行模式就是設計給這麼用的。aniGamerPlus.exe 也是有命令行模式的。
對於cmd陌生的用戶，目前可以考慮用 bat 批次檔來引導這些用戶使用命令行模式。

**Comment by ycs77** [comment]
了解
