### ISSUE TITLE
關於v22.1下載偵測到病毒的相關資訊

### ISSUE THREAD

**Issue by mitetsu-kurone** [miyouzi/aniGamerPlus#121]
## 問題描述
#因為處理完了，讓其他載v22.1失敗的人不用再找一次資料#

如果chrome下載以後，顯示 失敗-系統偵測到病毒
這是因為windows本身的防毒掃到木馬

## 如果你不信任作者的exe檔案
請直接用源碼跑

## 如果你信任作者的檔案沒毒想直接下載exe
*我的windows10是日文版，故名稱可能有出入，勿拘泥字句

1.請進入 控制台=>更新與安全=>windows安全性 裡面可以開啟另一個windows安全性設定視窗
2.病毒與威脅的設定=>設定管理=>即時(Real Time)保護 =>開關關閉(下載完後就可以重新開啟，一段時間也會自動跳成開啟)

只要沒有上述動作，windows10判斷成重大病毒一律會直接砍掉
註:為什麼連選項都沒，因為就算是誤判，這次掃到的特徵碼是最嚴重的勒索病毒，所以連接受風險等選項都沒有

雖然關著的狀態就可以執行aniGamerPlus.exe，但沒有多久上述的即時保護會自動打開，就會無法執行
此時需要在下方的除外加白名單，把aniGamerPlus.exe加進去，往後就不會跳

## 補充
這部分作者可能要先確認一下打包程式的最後修改日期等資訊，因為病毒不一定出在源碼，可能出在依賴套件或打包程式被加料

**Comment by miyouzi** [comment]
麻煩看下 v22.2 版本還會不會報毒

**Comment by QKmoon** [comment]
> 麻煩看下 v22.2 版本還會不會報毒
試了下還是會

**Comment by mitetsu-kurone** [comment]
22.3 測試是不會了 用內建的defender掃過沒有問題
