### ISSUE TITLE
嚴重錯誤

### ISSUE THREAD

**Issue by RyanL-29** [miyouzi/aniGamerPlus#126]
@miyouzi Github workflow 打包出來的東西有點問題, 使用時會發生存取錯誤.

需要修改

```
        # 删除临时目录
        shutil.rmtree(temp_dir)
```
變為

```
        # 删除临时目录
        shutil.rmtree(temp_dir, ignore_errors=True)
```

**Comment by miyouzi** [comment]
瞭解

**Comment by RyanL-29** [comment]
@miyouzi 

為何要
```
    - name: Copy exe out
      run: copy /V /Y dist/aniGamerPlus.exe /B .
      shell: cmd
```

這不是更好嗎.... 
```pyinstaller --noconfirm --onefile --distpath %cd%\ --console --icon %cd%\Dashboard\static\img\aniGamerPlus.ico --clean --add-data %cd%;aniGamerPlus/  %cd%\aniGamerPlus.py```

XD

**Comment by miyouzi** [comment]
> --distpath %cd%

試了一下確實可以，我還以為 dist 這個資料夾是固定有的呢 😂

**Comment by RyanL-29** [comment]
😂
