### ISSUE TITLE
V22.3 web手动添加失败

### ISSUE THREAD

**Issue by timk-lalala** [miyouzi/aniGamerPlus#127]
升级到最新版之后手动添加任务报错，web某些设定无法修改。
![image](https://user-images.githubusercontent.com/17139396/127015668-95864753-1ee8-432b-b8e2-33240920fbe1.png)
![image](https://user-images.githubusercontent.com/17139396/127015489-de76b08a-14ec-43dd-ad7d-cc0ea47b0317.png)
![image](https://user-images.githubusercontent.com/17139396/127015533-929794d7-20b2-4622-a6bd-06a016c8853d.png)
以上设置无法修改，同时为空

**Comment by miyouzi** [comment]
尝试关闭广告过滤型插件以及更换浏览器看看？

**Comment by timk-lalala** [comment]
> 尝试关闭广告过滤型插件以及更换浏览器看看？

![image](https://user-images.githubusercontent.com/17139396/127017119-a8568bbb-1966-494a-85ca-2df86839cc2d.png)
未开启

**Comment by timk-lalala** [comment]
> 尝试关闭广告过滤型插件以及更换浏览器看看？

刚才尝试使用另一台从未登陆的设备，发现好像是由于web页面缓存未更新导致的。手动强制更新缓存好了
