### ISSUE TITLE
目前似乎無法抓取cookie

### ISSUE THREAD

**Issue by NanbuShirou** [miyouzi/aniGamerPlus#128]
## 問題描述

看起來是把路徑隱藏起來  導致無法直接看到cookie  不知是否有方式處理?
![messageImage_1628434696312](https://user-images.githubusercontent.com/87841053/128636521-5c3a6bda-b7d6-4fc4-94f3-61a23ce910e4.jpg)

**Comment by miyouzi** [comment]
network介面，不是console，你再看看說明

**Comment by NanbuShirou** [comment]
network現在是一片白  大概是map擋住不給看了

![messageImage_1628434696312](https://user-images.githubusercontent.com/87841053/128637219-526a1bf7-8fdb-4c51-a56b-eac8e4831346.jpg)

不過剛剛試了一下  從這邊還是可以看  只是麻煩一點
![messageImage_1628436534746](https://user-images.githubusercontent.com/87841053/128637276-9c7ae9ce-1c20-48d2-9126-7aed31daf11c.jpg)

需要的欄位大概是
BAHAENUR=
BAHARUNE=
_ga=
_ga_2Q21791Y9D=
_ga_MT7EZECMKQ=
_gat=1;_gid=
ckBAHAADS=
ckBahaAd=
ckBahamutCsrfToken=
ckFORUM_setting=
ckM=

再試試看能不能自動更新cookie 
QwQ

**Comment by miyouzi** [comment]
説明你再研究研究？這裏是沒有填東西的

![image](https://user-images.githubusercontent.com/24269465/128656290-2deed008-7b34-4151-9c9c-6dae624f2adc.png)

**Comment by NanbuShirou** [comment]
好像發現問題在哪 犯傻了

感謝
