### ISSUE TITLE
有没有办法把动画疯番剧的内嵌字幕提取出来？

### ISSUE THREAD

**Issue by YFTX2015** [miyouzi/aniGamerPlus#129]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#

## 錯誤截圖
#在這裏附上錯誤的窗口截圖#

## config.json 配置
```
#將你的config.json内容複製到這裏#
```

## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```

**最好上傳 log 檔案**

**Comment by miyouzi** [comment]
动画疯的字幕是压制进去的，是画面的一部分。

有这个需求请在网上查询 `手抄字幕 教程`
