### ISSUE TITLE
指定解析度不存在

### ISSUE THREAD

**Issue by NanbuShirou** [miyouzi/aniGamerPlus#130]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#
無法找到指定解析度造成無法下載

## 錯誤截圖
#在這裏附上錯誤的窗口截圖#

![messageImage_1630726578390](https://user-images.githubusercontent.com/87841053/132081181-482526ac-aeec-4c43-a28f-d62817755ce1.jpg)

## config.json 配置
```
#將你的config.json内容複製到這裏#
```
{
    "bangumi_dir": "E:\當季新番",
    "temp_dir": "",
    "classify_bangumi": true,
    "check_frequency": 30,
    "download_resolution": "720",
    "lock_resolution": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 1,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": false,
    "add_resolution_to_video_filename": false,
    "customized_video_filename_prefix": "",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 2,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36",
    "use_proxy": false,
    "proxy": "",
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "query": [
            "http://127.0.0.1:5700/send_group_msg?group_id=123456789"
        ],
        "message_suffix": "",
        "msg_argument_name": "message"
    },
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": false,
    "danmu": false,
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 31,
    "mobile_ads_time": 3,
    "use_dashboard": true,
    "dashboard": {
        "host": "192.168.1.101",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 15.3,
    "database_version": 2.0,
    "telebot_notify": false,
    "telebot_token": "",
    "only_use_vip": false
}
## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```
**最好上傳 log 檔案**
[2021-09-04.log](https://github.com/miyouzi/aniGamerPlus/files/7109144/2021-09-04.log)

**Comment by Riridesu** [comment]
我也遇到同樣的問題

2021-09-04 11:45:27 開始下載: sn=24605	《轉生成女性向遊戲只有毀滅 END 的壞人大小姐 X [10]》 識別到VIP賬戶, 立即下載
2021-09-04 11:45:27 任務狀態: sn=24605	指定清晰度不存在, 選取最近可用清晰度: 0P
2021-09-04 11:45:27 下載異常: sn=24605	發生未知錯誤: '0'
2021-09-04 11:45:27 下載異常: sn=24605	異常詳情:
Traceback (most recent call last):
  File "aniGamerPlus.py", line 228, in worker
  File "Anime.py", line 898, in download
  File "Anime.py", line 567, in __segment_download_mode
KeyError: '0'

**Comment by RyanL-29** [comment]
![image](https://user-images.githubusercontent.com/48479346/132082651-180e20eb-ee4f-4e51-8260-dfa9a67aea6d.png)


感覺是巴哈那邊修改了返回的內容

**Comment by miyouzi** [comment]
確認今天早上動畫瘋網站改動，正在適配

**Comment by miyouzi** [comment]
已修復。更新下程式

**Comment by CopanLee** [comment]
@miyouzi 
Config.py aniGamerPlus_version = 'v22.3' 未更新 v22.5
已下載v22.5仍會跳出版本更新通知

**Comment by miyouzi** [comment]
> v22.5

抱歉，忘了改版本了 😓 v22.51 修復（稍後release會自動生成）
