### ISSUE TITLE
能不能新增彈幕過濾功能

### ISSUE THREAD

**Issue by fmnijk** [miyouzi/aniGamerPlus#139]
官方內建有自動過濾彈幕的功能，覺得挺方便的，希望這邊也有。

**Comment by miyouzi** [comment]
彈幕功能要問問 @a20034294 ，其實我覺得彈幕方面用 `彈彈Play ` 可以滿足大部分的彈幕需求

**Comment by a20034294** [comment]
可以加，不過我現在在當兵加不了XD
彈彈 play 第一次聽說，看起來相當不錯，之前曾經想過做一個第三方彈幕平台，看來已經有人做了
