### ISSUE TITLE
無法下載動畫瘋影片

### ISSUE THREAD

**Issue by ycs77** [miyouzi/aniGamerPlus#14]
先放上出錯的畫面......

**自動模式下載錯誤**
![Download Error](https://user-images.githubusercontent.com/38133356/61017099-97f76080-a3c4-11e9-8820-5b41c99c8493.jpg)

**CLI 下載錯誤**
![Download Error](https://user-images.githubusercontent.com/38133356/61017090-9037bc00-a3c4-11e9-8d7d-31244bd0b74f.jpg)

基本上這個錯誤應該是動畫瘋修改了提供影片 `m3u8` 檔的相關程式，現在直接進入 `https://ani.gamer.com.tw/ajax/m3u8.php?sn=[sn]` 時無法獲取 `m3u8` 檔：

![m3u8](https://user-images.githubusercontent.com/38133356/61017359-7ba7f380-a3c5-11e9-99b7-b4b6b7689d94.jpg)

以上......

**Comment by miyouzi** [comment]
動畫瘋似乎修改了廣告處理方式，正在著手解決
目前有個解決方法是在 ```Anime.py```的 331 行 ```time.sleep(3)``` 的 ```3``` 拉到 ```30```

**Comment by miyouzi** [comment]
[v13](https://github.com/miyouzi/aniGamerPlus/releases/tag/v13) 版本已發佈，試試如何

**Comment by ycs77** [comment]
可以下載了！感謝修復！
