### ISSUE TITLE
整個aniGamerPlus控制臺的參數都沒了

### ISSUE THREAD

**Issue by hohhokiki** [miyouzi/aniGamerPlus#141]

**Comment by hohhokiki** [comment]
![圖片1](https://user-images.githubusercontent.com/87378515/145695262-90e28858-3a2c-4371-8ee4-084eeab9a436.png)

**Comment by miyouzi** [comment]
F12 看下 console 和 network ？

**Comment by hohhokiki** [comment]
![圖片1](https://user-images.githubusercontent.com/87378515/145697643-bcdd8b3e-363b-47b6-88ae-8574bc18ba11.png)

**Comment by miyouzi** [comment]
看下network，是不是config.json沒加載出來？

web log 發一下吧

**Comment by hohhokiki** [comment]
![圖片1](https://user-images.githubusercontent.com/87378515/145699693-3a6013c4-d330-4ddc-84de-96e9b44c5dbc.png)

**Comment by hohhokiki** [comment]
HELLO?

**Comment by miyouzi** [comment]
不能複現，你把 log 資料夾打包發一下吧。順便說明一下操作系統是什麼

**Comment by hohhokiki** [comment]
更新玩win11才變這樣

127.0.0.1 - - [2021-12-12 10:01:12] "GET / HTTP/1.1" 200 18470 0.004987
127.0.0.1 - - [2021-12-12 10:01:12] "GET /static/js/jquery-3.4.0.min.js HTTP/1.1" 304 188 0.000996
127.0.0.1 - - [2021-12-12 10:01:12] "GET /static/js/popper.min.js HTTP/1.1" 304 189 0.000000
127.0.0.1 - - [2021-12-12 10:01:12] "GET /static/css/bootstrap-switch.min.css HTTP/1.1" 304 188 0.000000
127.0.0.1 - - [2021-12-12 10:01:12] "GET /static/css/fontawesome.all.min.css HTTP/1.1" 304 189 0.000997
127.0.0.1 - - [2021-12-12 10:01:12] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 189 0.000997
127.0.0.1 - - [2021-12-12 10:01:12] "GET /static/css/bootstrap.rfs.min.css HTTP/1.1" 304 189 0.000998
127.0.0.1 - - [2021-12-12 10:01:12] "GET /static/js/bootstrap-switch.min-3.3.4.js HTTP/1.1" 304 189 0.000996
127.0.0.1 - - [2021-12-12 10:01:12] "GET /static/css/bootstrap-select.min.css HTTP/1.1" 304 189 0.000997
127.0.0.1 - - [2021-12-12 10:01:12] "GET /static/css/aniGamerPlus.css HTTP/1.1" 304 188 0.000998
127.0.0.1 - - [2021-12-12 10:01:12] "GET /static/js/aniGamerPlus.js HTTP/1.1" 304 187 0.000997
127.0.0.1 - - [2021-12-12 10:01:12] "GET /static/js/bootstrap-select.min.js HTTP/1.1" 304 189 0.000999
127.0.0.1 - - [2021-12-12 10:01:12] "GET /static/js/settings_id_list.js HTTP/1.1" 304 187 0.000995
127.0.0.1 - - [2021-12-12 10:01:12] "GET /data/config.json HTTP/1.1" 200 1053 0.000997
127.0.0.1 - - [2021-12-12 10:01:12] "GET /data/sn_list HTTP/1.1" 200 115 0.000000
127.0.0.1 - - [2021-12-12 10:01:12] "GET /static/img/aniGamerPlus.ico HTTP/1.1" 200 5516 0.000995
127.0.0.1 - - [2021-12-12 11:55:07] "GET / HTTP/1.1" 200 18470 0.013963
127.0.0.1 - - [2021-12-12 11:55:07] "GET /data/config.json HTTP/1.1" 200 1053 0.000996
127.0.0.1 - - [2021-12-12 11:55:07] "GET /data/sn_list HTTP/1.1" 200 115 0.000996
127.0.0.1 - - [2021-12-12 11:55:21] "GET / HTTP/1.1" 200 18470 0.000998
127.0.0.1 - - [2021-12-12 11:55:21] "GET /data/config.json HTTP/1.1" 200 1053 0.000000
127.0.0.1 - - [2021-12-12 11:55:21] "GET /data/sn_list HTTP/1.1" 200 115 0.000000
127.0.0.1 - - [2021-12-12 11:55:21] "GET /static/img/aniGamerPlus.ico HTTP/1.1" 200 5516 0.003990

**Comment by miyouzi** [comment]
你的瀏覽器有沒有開啓廣告過濾之類的插件？有的話關閉看看

**Comment by hohhokiki** [comment]
Request URL: http://127.0.0.1:5000/data/config.json
Request Method: GET
Status Code: 200 OK
Remote Address: 127.0.0.1:5000
Referrer Policy: strict-origin-when-cross-origin
Content-Length: 944
Content-Type: application/json
Date: Tue, 14 Dec 2021 13:43:47 GMT
Accept: application/json, text/javascript, */*; q=0.01
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6
Connection: keep-alive
Host: 127.0.0.1:5000
Referer: http://127.0.0.1:5000/
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
X-Requested-With: XMLHttpRequest

**Comment by miyouzi** [comment]
`config.json` 指的是內容

**Comment by hohhokiki** [comment]
剛剛我又試了一下，結果就好了...

**Comment by hohhokiki** [comment]
可是點進來還是會這樣子...

**Comment by miyouzi** [comment]
換個瀏覽器，或者用無痕模式看看還有沒有問題

**Comment by ceres512** [comment]
您好，我使用「aniGamerPlus_v22.6」也有同樣的狀況，變成每下載一次需要再按一次重載配置，以下是我的config.json，謝謝。

{
    "bangumi_dir": "",
    "temp_dir": "",
    "classify_bangumi": true,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": true,
    "only_use_vip": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36",
    "use_proxy": false,
    "proxy": "socks5://:",
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "msg_argument_name": "message",
        "message_suffix": "追加的資訊",
        "query": [
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
        ]
    },
    "telebot_notify": false,
    "telebot_token": "",
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": false,
    "danmu": false,
    "check_latest_version": false,
    "read_sn_list_when_checking_update": false,
    "read_config_when_checking_update": false,
    "ads_time": 25,
    "mobile_ads_time": 3,
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": false,
    "quantity_of_logs": 7,
    "config_version": 15.3,
    "database_version": 2.0
}

**Comment by miyouzi** [comment]
> 您好，我使用「aniGamerPlus_v22.6」也有同樣的狀況，變成每下載一次需要再按一次重載配置，以下是我的config.json，謝謝。
> 
> {
>     "bangumi_dir": "",
>     "temp_dir": "",
>     "classify_bangumi": true,
>     "check_frequency": 5,
>     "download_resolution": "1080",
>     "lock_resolution": true,
>     "only_use_vip": false,
>     "default_download_mode": "latest",
>     "use_copyfile_method": false,
>     "multi-thread": 1,
>     "multi_upload": 3,
>     "segment_download_mode": true,
>     "multi_downloading_segment": 2,
>     "segment_max_retry": 8,
>     "add_bangumi_name_to_video_filename": true,
>     "add_resolution_to_video_filename": true,
>     "customized_video_filename_prefix": "【動畫瘋】",
>     "customized_bangumi_name_suffix": "",
>     "customized_video_filename_suffix": "",
>     "video_filename_extension": "mp4",
>     "zerofill": 1,
>     "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36",
>     "use_proxy": false,
>     "proxy": "socks5://:",
>     "upload_to_server": false,
>     "ftp": {
>         "server": "",
>         "port": "",
>         "user": "",
>         "pwd": "",
>         "tls": true,
>         "cwd": "",
>         "show_error_detail": false,
>         "max_retry_num": 15
>     },
>     "user_command": "shutdown -s -t 60",
>     "coolq_notify": false,
>     "coolq_settings": {
>         "msg_argument_name": "message",
>         "message_suffix": "追加的資訊",
>         "query": [
>             "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
>             "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
>         ]
>     },
>     "telebot_notify": false,
>     "telebot_token": "",
>     "faststart_movflags": false,
>     "audio_language": false,
>     "use_mobile_api": false,
>     "danmu": false,
>     "check_latest_version": false,
>     "read_sn_list_when_checking_update": false,
>     "read_config_when_checking_update": false,
>     "ads_time": 25,
>     "mobile_ads_time": 3,
>     "use_dashboard": true,
>     "dashboard": {
>         "host": "127.0.0.1",
>         "port": 5000,
>         "SSL": false,
>         "BasicAuth": false,
>         "username": "admin",
>         "password": "admin"
>     },
>     "save_logs": false,
>     "quantity_of_logs": 7,
>     "config_version": 15.3,
>     "database_version": 2.0
> }

說明一下瀏覽器是什麼，作業系統版本，以及使用了哪些過濾插件

**Comment by ceres512** [comment]
瀏覽器：Google Chrome( 版本 97.0.4692.99 )

作業系統：Windows 10 專業版( 64位元 )

過濾插件：Adblock for Youtube™
