### ISSUE TITLE
無法合併影片

### ISSUE THREAD

**Issue by QKmoon** [miyouzi/aniGamerPlus#145]
## 問題描述
合併影片時發生錯誤

## 錯誤截圖
![image](https://user-images.githubusercontent.com/87666103/146967520-8920b6a7-fdd8-4dd1-80a9-7641dab420c9.png)
## config.json 配置
{
    "bangumi_dir": "D:\\動畫待補\\新番\\Ani",
    "temp_dir": "",
    "classify_bangumi": true,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": true,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36",
    "use_proxy": false,
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "query": [
            "http://127.0.0.1:5700/send_group_msg?group_id=123456789"
        ],
        "message_suffix": "追加的資訊",
        "msg_argument_name": "message"
    },
    "faststart_movflags": false,
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 15.3,
    "database_version": 2.0,
    "video_filename_extension": "mp4",
    "audio_language": false,
    "proxy": "socks5://127.0.0.1:1080",
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "ads_time": 25,
    "danmu": false,
    "use_mobile_api": false,
    "mobile_ads_time": 3,
    "telebot_notify": false,
    "telebot_token": "",
    "only_use_vip": false
}

## sn_list.txt 配置
@新番
13813 all # 我們真的學不來！第二季 
13803 all # Fate_Grand_Order_絕對魔獸戰線巴比倫尼亞
13644 latest # Dr.STONE 新石紀
13865 all # 萌獸寵物店
13869 all # 這個勇者明明超 TUEEE 卻過度謹慎！
#13940 all # 刀劍神域_Alicization_War_of_Underworld
13816 all # 夢幻之星 Online 2 Episode Oracle
#2020一月新番
14487 all # 索瑪麗與森林之神
14443 all # 戀愛中的小行星
#14445 all # 達爾文遊戲
14453 all # 魔法紀錄 魔法少女小圓外傳
14490 all # 房間露營
14499 all # 怕痛的我，把防禦力點滿就對了
14532 all # 〈Infinite Dendrogram〉-無盡連鎖-
14542 all # 22/7
14546 all # 異世界四重奏 第二季
14568 all # 魔法少女☆伊莉雅 百變嘉年華
15129 latest
#2020四月春番
15161 all # 格萊普尼爾
15298 all # 輝夜姬想讓人告白～天才們的戀愛頭腦戰～ 第二季
15149 all # 昨日之歌
#2020 七月夏番
16229 all # 弩級戰隊 HXEROS
16231 all # Lapis Re：LiGHTs
16233 all # 魔王學院的不適任者～史上最強的魔王始祖，轉生就讀子孫們的學校～
16344 all # Re：從零開始的異世界生活 第二季
#16236 all # 刀劍神域 Alicization War of Underworld -THE LAST SEASON-
16176 all # DECA - DENCE
16396 all # 果然我的青春戀愛喜劇搞錯了。完
16590 all # 布林殺手 -GOBLIN’S CROWN- 
#2020 十月秋番
18370 all # 無能力者娜娜
18422 all # BURN THE WITCH 龍與魔女
18437 all # 魔法科高中的劣等生 來訪者篇
18436 all # 戰翼的希格德莉法
18428 all # 我立於百萬生命之上 
18427 all # 魔女之旅
18484 all # 鐵路浪漫譚
18430 all # 在地下城尋求邂逅是否搞錯了什麼 第三季
18431 all # 王之逆襲：意志的繼承者
18525 all # 在魔王城說晚安
18215 all # 熊熊勇闖異世界
18550 all # 成神之日
18548 all # 請問您今天要來點兔子嗎？BLOOM
#2021 一月新番
20527 all # 關於我轉生變成史萊姆這檔事 第二季
20561 all # 約定的夢幻島 第二季
20555 all # 搖曳露營△ 第二季
20600 all # 轉生成蜘蛛又怎樣！
20612 all # 堀與宮村
20620 all # 無職轉生，到了異世界就拿出真本事
#2021 四月新番
22226 all # Vivy -Fluorite Eye's Song-
22220 all # 戰鬥員派遣中！
22228 all # 轉生史萊姆日記 關於我轉生變成史萊姆這檔事
22235 all # 聖女魔力無所不能
22289 all # 如果究極進化的完全沉浸 RPG 比現實還更像垃圾遊戲的話
22243 all # 持續狩獵史萊姆三百年，不知不覺就練到 LV MAX
22245 all # 86－不存在的戰區－
22246 all # 影宅
22249 all # 青梅竹馬絕對不會輸的戀愛喜劇
#2021 七月新番
23342 all # 桃子男孩渡海而來
23350 all # 轉生成女性向遊戲只有毀滅 END 的壞人大小姐 X
23348 all # 瓦尼塔斯的手札 
23381 all # 女朋友 and 女朋友
23375 all # 我們的重製人生
23362 all # 魔法科高中的優等生
23369 all # 偵探已經，死了。
23346 all # 白沙的 Aquatope
23347 all # 我立於百萬生命之上 第二季
23337 all # 急戰 5 秒殊死鬥
#舊番
12122 all #強襲魔女 501 部隊出動！
18539 all #強襲魔女 通往柏林之路
6419 all #無畏魔女
#2021 十月新番
25490 all #SELECTION PROJECT
25479 all #結城友奈是勇者 大滿開之章
25458 all #異世界食堂 2
25432 all #月與萊卡與吸血公主
25487 all #宿命迴響：命運節拍
25486 all #世界頂尖的暗殺者轉生為異世界貴族
25494 all #大正處女御伽話
25559 all #世界盡頭的聖騎士
25561 all #BUILD-DIVIDE -#000000- CODE BLACK
25496 all #前輩有夠煩

## 錯誤 log 
2021-12-22 00:42:05 開始下載: sn=26988	《宿命迴響：命運節拍 [12]》 識別到VIP賬戶, 立即下載
2021-12-22 00:42:05 正在下載: sn=26988	【動畫瘋】宿命迴響：命運節拍[12][1080P].mp4 title=宿命迴響：命運節拍 [12]
2021-12-22 00:43:51 下載狀態: sn=26988	【動畫瘋】宿命迴響：命運節拍[12][1080P].mp4 下載完成, 正在解密合并……
2021-12-22 00:43:51 下載異常: sn=26988	發生未知錯誤: [WinError 2] 系統找不到指定的檔案。: 'D:\\動畫待補\\新番\\下載器\\temp\\【動畫瘋】宿命迴響：命運節拍[12][1080P].MERGING.mp4'
2021-12-22 00:43:51 下載異常: sn=26988	異常詳情:
Traceback (most recent call last):
  File "aniGamerPlus.py", line 228, in worker
  File "Anime.py", line 906, in download
  File "Anime.py", line 702, in __segment_download_mode
  File "genericpath.py", line 50, in getsize
FileNotFoundError: [WinError 2] 系統找不到指定的檔案。: 'D:\\動畫待補\\新番\\下載器\\temp\\【動畫瘋】宿命迴響：命運節拍[12][1080P].MERGING.mp4'

**Comment by partment** [comment]
將Anime.py第[585](https://github.com/miyouzi/aniGamerPlus/blob/b5c212281584ed86befb23a2320ef3a4d41646cd/Anime.py#L585)行
從`key_uri = re.sub(r'.+URI="', '', key_uri)[0:-1]`
改成`key_uri = re.search(r'(?<=URI=")(.*)(?=")', key_uri).group()`

**Comment by QKmoon** [comment]
> 將Anime.py第[585](https://github.com/miyouzi/aniGamerPlus/blob/b5c212281584ed86befb23a2320ef3a4d41646cd/Anime.py#L585)行 從`key_uri = re.sub(r'.+URI="', '', key_uri)[0:-1]` 改成`key_uri = re.search(r'(?<=URI=")(.*)(?=")', key_uri).group()`

改了之後就解決了 感謝
