### ISSUE TITLE
合并出错

### ISSUE THREAD

**Issue by YFTX2015** [miyouzi/aniGamerPlus#146]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#
从今天开始的片源开始，下载完成合并时会出现如下图错误
## 錯誤截圖
#在這裏附上錯誤的窗口截圖#
![屏幕截图(1)](https://user-images.githubusercontent.com/12757305/146979990-8f3ac171-f37c-4b88-aa72-f505af7109b5.png)

## config.json 配置
```
#將你的config.json内容複製到這裏#
```
{
    "bangumi_dir": "C:\\Users\\YFTX2\\视频",
    "temp_dir": "",
    "classify_bangumi": false,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": true,
    "only_use_vip": true,
    "default_download_mode": "largest-sn",
    "use_copyfile_method": false,
    "multi-thread": 5,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 5,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": false,
    "customized_video_filename_prefix": "",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "ts",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4629.0 Safari/537.36 Edg/95.0.1009.0",
    "use_proxy": false,
    "proxy": " socks5h://127.0.0.1:7890",
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "msg_argument_name": "message",
        "message_suffix": "追加的資訊",
        "query": [
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
        ]
    },
    "faststart_movflags": true,
    "audio_language": false,
    "use_mobile_api": false,
    "danmu": false,
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 0,
    "mobile_ads_time": 0,
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": true,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 15.3,
    "database_version": 2.0,
    "telebot_notify": false,
    "telebot_token": ""
}
## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```
26996
**最好上傳 log 檔案**
[2021-12-22.log](https://github.com/miyouzi/aniGamerPlus/files/7757285/2021-12-22.log)

**Comment by BraveSail** [comment]
巴哈改了 m3u8 的格式，可以将
https://github.com/miyouzi/aniGamerPlus/blob/b5c212281584ed86befb23a2320ef3a4d41646cd/Anime.py#L585
改成
`key_uri = key_uri.split('URI="')[1].split('",IV=')[0]`

**Comment by YFTX2015** [comment]
exe的怎么改？

**Comment by newhy** [comment]
> exe的怎么改？

应急措施就是下载完出错提示后用对应的key【比如key_b5000000.m3u8key（1080P）】重命名替换temp文件夹对应剧的key，然后里面的m3u8【#EXT-X-KEY:METHOD】一行也要注意尾缀为：by-aniGamerPlus\\key.m3u8key" 可能下下来是没用双引号的，之后直接拖进m3u8DL-CLI这类工具里

**Comment by BraveSail** [comment]
> exe的怎么改？

不用  exe ，直接文件夹里 python3 anigamerplus.py
