### ISSUE TITLE
22.6異常錯誤

### ISSUE THREAD

**Issue by s000668** [miyouzi/aniGamerPlus#149]
## 問題描述
#在這裏詳細説明你遇到了什麽問題- [ ] 
Traceback (most recent call last):
  File "shutil.py", line 791, in move
OSError: [WinError 17] 系統無法將檔案移到不同的磁碟機。: 'C:\\Users\\ues\\Desktop\\aniGamerPlus_v22.6_windows_64bit\\temp\\86－不存在的戰區－[21][720P].MERGING.mp4' -> 'D:\\bt\\to\\86－不存在的戰區－\\86－不存在的戰區－[21][720P].mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aniGamerPlus.py", line 228, in worker
  File "Anime.py", line 905, in download
  File "Anime.py", line 711, in __segment_download_mode
  File "shutil.py", line 812, in move
PermissionError: [WinError 5] 存取被拒。: 'C:\\Users\\ues\\Desktop\\aniGamerPlus_v22.6_windows_64bit\\temp\\86－不存在的戰區－[21][720P].MERGING.mp4'

## 錯誤截圖
#在這裏附上錯誤的窗口截圖#
![ScreenShot_20211227095903](https://user-images.githubusercontent.com/96707283/147442529-d09b4bc8-a671-4191-bbff-08c47e340740.png)

## config.json 配置
```
#將你的config.json内容複製到這裏#
```{
    "bangumi_dir": "D:\\bt\\to",
    "temp_dir": "",
    "classify_bangumi": true,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36",
    "use_proxy": false,
    "proxy": "http://user:passwd@example.com:1000",
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "msg_argument_name": "message",
        "message_suffix": "追加的資訊",
        "query": [
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
        ]
    },
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": false,
    "danmu": false,
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "mobile_ads_time": 3,
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 15.3,
    "database_version": 2.0,
    "telebot_notify": false,
    "telebot_token": "",
    "only_use_vip": false
}

## sn_list.txt 配置
```26904 #
#
#
all #

#將你的sn_list.txt内容複製到這裏#
````26904 #
#
#
all #


**最好上傳 log 檔案**
### ``
[2021-12-27.log](https://github.com/miyouzi/aniGamerPlus/files/7778769/2021-12-27.log)

**Comment by miyouzi** [comment]
找到這行並配置 `"use_copyfile_method": true`

**Comment by s000668** [comment]
我的config文件裡面找不到您說的這一行

**Comment by s000668** [comment]
改好了還是一樣
{
    "bangumi_dir": "D:\\bt\\to",
    "temp_dir": "",
    "classify_bangumi": true,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": false,
    "default_download_mode": "latest",
    "use_copyfile_method": true,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36",
    "use_proxy": false,
    "proxy": "http://user:passwd@example.com:1000",
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "msg_argument_name": "message",
        "message_suffix": "追加的資訊",
        "query": [
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
        ]
    },
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": false,
    "danmu": false,
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "mobile_ads_time": 3,
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 15.3,
    "database_version": 2.0,
    "telebot_notify": false,
    "telebot_token": "",
    "only_use_vip": false
}
[2021-12-27.log](https://github.com/miyouzi/aniGamerPlus/files/7778874/2021-12-27.log)
![ScreenShot_20211227151758](https://user-images.githubusercontent.com/96707283/147445708-1560d892-e49f-4f25-b7c2-528e7febaee2.png)

**Comment by miyouzi** [comment]
把程式換個地方放呢？比如放到 D 盘

**Comment by s000668** [comment]
換地方後沒問題了感謝
