### ISSUE TITLE
請問：下面這一串是什麼意思

### ISSUE THREAD

**Issue by ABCDF9565218** [miyouzi/aniGamerPlus#15]
注意警告
Python版本3以上

本專案依賴ffmpeg，請事先將ffmpeg放入系統PATH或者本程序目錄下！

使用前確認已安裝好依賴

pip3 install requests beautifulsoup4 lxml termcolor chardet pysocks

**Comment by miyouzi** [comment]
如果不熟悉python，那麽直接去 [release](https://github.com/miyouzi/aniGamerPlus/releases/latest) 下載 exe檔來使用，并且前往 [ffmpeg 網站](https://ffmpeg.zeranoe.com/builds/)下載 ```ffmpeg.exe``` ，將其放在和 ```aniGamerPlus.exe```同一個資料夾

**Comment by ABCDF9565218** [comment]
請問： 從ffmpeg 網站下載ffmpeg-20190718-ab4795a-win64-static資料夾，之後再下載aniGamerPlus-master資料夾，是把ffmpeg-20190718-ab4795a-win64-static資料夾移到aniGamerPlus-master資料夾理嗎

**Comment by miyouzi** [comment]
不是整個資料夾，只要這個資料夾裏的 ```ffmpeg.exe``` 一個檔案就好

**Comment by ABCDF9565218** [comment]
好的，感謝幫忙
