### ISSUE TITLE
docker版解密合并出错

### ISSUE THREAD

**Issue by RyPoi** [miyouzi/aniGamerPlus#152]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#
docker版解密合并出错，2022-01-13 05:38:46 下載異常: sn=27359	發生未知異常: [Errno 2] No such file or directory: '/app/temp/【動畫瘋】東京 24 區[2][360P].MERGING.mp4'。
## 錯誤截圖
#在這裏附上錯誤的窗口截圖#
![图片](https://user-images.githubusercontent.com/45539440/149273673-15128e77-c670-4bb6-8b9c-0e2ced0bc604.png)

## config.json 配置
```
#將你的config.json内容複製到這裏#
```
{
    "bangumi_dir": "",
    "temp_dir": "",
    "classify_bangumi": true,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": false,
    "only_use_vip": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36",
    "use_proxy": true,
    "proxy": "socks5://192.168.2.12:10808",
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "msg_argument_name": "message",
        "message_suffix": "追加的資訊",
        "query": [
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
        ]
    },
    "telebot_notify": false,
    "telebot_token": "",
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": false,
    "danmu": false,
    "check_latest_version": false,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "mobile_ads_time": 3,
    "use_dashboard": true,
    "dashboard": {
        "host": "0.0.0.0",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 15.3,
    "database_version": 2.0
}
## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```

**最好上傳 log 檔案**
2022-01-13 05:37:46 Dashboard 通過 Web 控制臺下達了手動任務

當前下載模式: 僅下載本集

2022-01-13 05:37:48 正在等待: sn=27359	《東京 24 區 [2]》 由於不是VIP賬戶, 正在等待25s廣告時間

2022-01-13 05:38:20 正在下載: sn=27359	【動畫瘋】東京 24 區[2][360P].mp4 title=東京 24 區 [2]

2022-01-13 05:38:45 下載狀態: sn=27359	【動畫瘋】東京 24 區[2][360P].mp4 下載完成, 正在解密合并……

2022-01-13 05:38:46 下載異常: sn=27359	發生未知異常: [Errno 2] No such file or directory: '/app/temp/【動畫瘋】東京 24 區[2][360P].MERGING.mp4'

2022-01-13 05:38:46 任務失敗: sn=27359	title=東京 24 區 [2] 10s后自動重啓,最多重試三次

Exception in thread Thread-5 (run_cui):

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner

    self.run()

  File "/usr/local/lib/python3.10/threading.py", line 946, in run

    self._target(*self._args, **self._kwargs)

  File "/app/Dashboard/Server.py", line 149, in run_cui

    cui(data['sn'], resolution, mode, thread_limit, [], classify=data['classify'], realtime_show=False, cui_danmu=data['danmu'])

  File "/app/aniGamerPlus.py", line 425, in __cui

    __download_only(sn, cui_resolution, cui_save_dir, realtime_show_file_size=realtime_show_file_size, classify=classify)

  File "/app/aniGamerPlus.py", line 364, in __download_only

    anime.renew()

  File "/app/Anime.py", line 85, in renew

    self.__get_episode_list()

  File "/app/Anime.py", line 204, in __get_episode_list

    ep = p[index_counter[ep]] + ep

IndexError: list index out of range

**Comment by miyouzi** [comment]
你的容器启动参数是什么

**Comment by RyPoi** [comment]
![图片](https://user-images.githubusercontent.com/45539440/149646725-e1a79681-0100-4a91-b6ab-f092e0f1c854.png)
上周用过lingyuily/anigamerplus的容器可以正常使用，就是这几天不行了，现在都是解密合并出错，Dashboard上也是相应的目录，temp也挂载了。

**Comment by miyouzi** [comment]
不要挂载 temp 试一试，另外我看到你 /app/aniGamer.db 没有挂载，容器如果重建的话，历史下载数据会丢失，你现在已经用了一段时间的话，建议把容器里的 db 文件拿出来再去映射，以免重复下载

**Comment by RyPoi** [comment]
我按照你说的不挂载temp，依旧是解密合并出错，还有aniGamer.db也已经挂载了，也是解密合并出错。
![图片](https://user-images.githubusercontent.com/45539440/149656213-02d0302c-7512-4f3c-bdfb-f07794d58c45.png)

![图片](https://user-images.githubusercontent.com/45539440/149656046-19a1115a-2d53-4012-8941-f3bbe9795147.png)
![图片](https://user-images.githubusercontent.com/45539440/149656235-0c52adcb-e575-4143-8ea0-7cee2bdcce52.png)

**Comment by miyouzi** [comment]
可能是  ffmpeg 版本的问题？可以确认容器内的 ffmpeg 版本是多少吗？

可能问问镜像制作者比较快 @TonyPepeBear

**Comment by RyPoi** [comment]
docker版似乎不依赖ffmpeg，我都没安装ffmpeg。我刚刚试下好多次，有成功过几次，但还不知道问题出在哪
![QQ截图20220117140559](https://user-images.githubusercontent.com/45539440/149720463-06ff199a-9c16-4425-ac20-8fc81b51b328.jpg)
![QQ截图20220117140550](https://user-images.githubusercontent.com/45539440/149720487-3b5b4164-ad07-45df-9415-d22bf3621a01.jpg)

**Comment by RyPoi** [comment]
我大概知道了，本季度的动画都不行，旧的就可以。
![图片](https://user-images.githubusercontent.com/45539440/149727438-8cd0a6bf-508f-4a43-85b0-5aab9e78af14.png)

**Comment by TonyPepeBear** [comment]
ffmpeg 是在 build image 時，直接用 apt 安裝的，可以去看 Dockerfile。

另外，我剛剛更新了 image 到最新的 commit (88c1bc6)。

**Comment by RyPoi** [comment]
非常感谢！现在已经可以正常下载了！
![图片](https://user-images.githubusercontent.com/45539440/149826210-7045f92a-e839-4105-80a0-52d2f7a8ef29.png)
