### ISSUE TITLE
aniGamerPlus_v22.6下載影片問題

### ISSUE THREAD

**Issue by ceres512** [miyouzi/aniGamerPlus#153]
您好，我使用「aniGamerPlus_v22.6」下載「幸運女神 劇場版 [電影] 線上看 - 巴哈姆特動畫瘋」畫質為1080P，影片從33:04開始畫面和聲音不同步，720P的則正常，不知是否為個別原因？謝謝。

**Comment by miyouzi** [comment]
說明一下你的 ffmpeg 版本，然後再下載一遍也還有這個問題是嗎

**Comment by ceres512** [comment]
版本是「ffmpeg-N-101367-g98c5d6b845-win64-gpl-shared-vulkan」，再下載一遍也是同樣的問題，還好目前只有此部影片是這樣～但它1月31日就會下架了…

**Comment by miyouzi** [comment]
這部在線觀看有沒有這個問題？

其他劇場版1080P有沒有這個問題？

**Comment by ceres512** [comment]
在線觀看沒問題，其他劇場版1080P也沒問題。

**Comment by miyouzi** [comment]
log 發一下

**Comment by ceres512** [comment]
![2022-01-21_225553](https://user-images.githubusercontent.com/97873210/150548491-1d0a9957-771b-4f14-95f3-a67bb35a5e4f.png)

請問是這裡面的哪個呢？

**Comment by miyouzi** [comment]
你整個資料夾 zip 后上傳吧，我順便看下你另一個 web 控制台的問題

**Comment by ceres512** [comment]
[2022-01-08.log](https://github.com/miyouzi/aniGamerPlus/files/7914592/2022-01-08.log)
[2022-01-09.log](https://github.com/miyouzi/aniGamerPlus/files/7914593/2022-01-09.log)
[2022-01-10.log](https://github.com/miyouzi/aniGamerPlus/files/7914594/2022-01-10.log)
[2022-01-11.log](https://github.com/miyouzi/aniGamerPlus/files/7914595/2022-01-11.log)
[2022-01-12.log](https://github.com/miyouzi/aniGamerPlus/files/7914596/2022-01-12.log)
[2022-01-13.log](https://github.com/miyouzi/aniGamerPlus/files/7914597/2022-01-13.log)
[2022-01-14.log](https://github.com/miyouzi/aniGamerPlus/files/7914598/2022-01-14.log)
[web.log](https://github.com/miyouzi/aniGamerPlus/files/7914599/web.log)
[web.log.2022-01-14.log](https://github.com/miyouzi/aniGamerPlus/files/7914600/web.log.2022-01-14.log)
[web.log.2022-01-15.log](https://github.com/miyouzi/aniGamerPlus/files/7914601/web.log.2022-01-15.log)
[web.log.2022-01-16.log](https://github.com/miyouzi/aniGamerPlus/files/7914602/web.log.2022-01-16.log)
[web.log.2022-01-17.log](https://github.com/miyouzi/aniGamerPlus/files/7914603/web.log.2022-01-17.log)
[web.log.2022-01-18.log](https://github.com/miyouzi/aniGamerPlus/files/7914604/web.log.2022-01-18.log)
[web.log.2022-01-19.log](https://github.com/miyouzi/aniGamerPlus/files/7914605/web.log.2022-01-19.log)
[web.log.2022-01-20.log](https://github.com/miyouzi/aniGamerPlus/files/7914606/web.log.2022-01-20.log)

**Comment by ceres512** [comment]
抱歉，無法上傳壓縮檔耶…

**Comment by miyouzi** [comment]
是壓縮成 zip 格式嗎？（rar 7z 都是不行的）

不會的話，就你剛才一個一個上傳也行吧

**Comment by ceres512** [comment]
不好意思，還是不行上傳zip檔，您方便用Google雲端硬碟下載嗎？

https://drive.google.com/file/d/1beDCOQL3r8hwFvGOdRqzu1DuyK5jzg8e/view?usp=sharing

您看看是否可以使用，謝謝您。

**Comment by ceres512** [comment]
您好，我傳的檔案可以使用嗎？

**Comment by ceres512** [comment]
您好，**幸運女神 劇場版 [電影] 線上看 - 巴哈姆特動畫瘋**下載完後已可順利播放，謝謝。
