### ISSUE TITLE
aniGamerPlus_v22.7 無法下載影片

### ISSUE THREAD

**Issue by ato90045** [miyouzi/aniGamerPlus#155]
## 問題描述
以前還可以正常下載，今天卻一直失敗，手動添加任務時失敗，出現以下Error message :

## 錯誤截圖
![image](https://user-images.githubusercontent.com/99263880/152996532-a64eaaec-a81f-4a77-bb76-9bf129e9f7e5.png)

2022-02-08 21:21:03 開始更新
2022-02-08 21:21:03 更新資訊 本次更新添加了 0 個新任務, 目前列隊中共有 0 個任務
2022-02-08 21:21:03 更新终了

ERROR:Dashboard.Server:Exception on /manualTask [POST]
Traceback (most recent call last):
  File "flask_sockets.py", line 40, in __call__
  File "werkzeug\routing.py", line 1945, in match
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask\app.py", line 2447, in wsgi_app
  File "flask\app.py", line 1952, in full_dispatch_request
  File "flask\app.py", line 1821, in handle_user_exception
  File "flask\_compat.py", line 39, in reraise
  File "flask\app.py", line 1950, in full_dispatch_request
  File "flask\app.py", line 1936, in dispatch_request
  File "Dashboard\Server.py", line 141, in manual_task
    thread = int(data['thread'])
ValueError: invalid literal for int() with base 10: ''

- config檔案
{
    "bangumi_dir": "",
    "temp_dir": "",
    "classify_bangumi": true,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": false,
    "only_use_vip": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36",
    "use_proxy": false,
    "proxy": "http://user:passwd@example.com:1000",
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "msg_argument_name": "message",
        "message_suffix": "追加的資訊",
        "query": [
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
        ]
    },
    "telebot_notify": false,
    "telebot_token": "",
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": false,
    "danmu": false,
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "mobile_ads_time": 3,
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 15.3,
    "database_version": 2.0
}

- log 檔案
[web.log](https://github.com/miyouzi/aniGamerPlus/files/8024147/web.log)

**Comment by miyouzi** [comment]
重新解壓一份出來看看呢？最近瀏覽器或者它的插件有升級之類的嗎

**Comment by ato90045** [comment]
原本我是用22.6版，但因為失敗，所以重新解壓縮22.7版，但還是失敗。chrome 版本是 98.0.4758.81，貌似最近有更新。

**Comment by miyouzi** [comment]
無痕模式看看呢？或者用插件比較少的瀏覽器試試呢？
