### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by xiaoxiaoliya** [miyouzi/aniGamerPlus#158]
你好尊敬的作者，这个在下载双语番剧的时候会出现问题，sn码并不能唯一标识双语动漫的每一集
例如 https://ani.gamer.com.tw/animeVideo.php?sn=26319
sn码26319-28037这是日语
sn码26341-28104这是国语 
当我指定下载26341-28104（国语）时，它会下载重复，也就是说这个两个范围的sn码的交集所对应的集数，它会重复下载两个语言版本，会把日语也下载上

**Comment by miyouzi** [comment]
你是用的是  `sn-range`  模式？這個模式設計上就是只下載給定的 sn ，不會再去判斷是什麽版本的，要達到你的效果，你需要寫成 `aniGamerPlus.py -s 26319 -m sn-range -e 26341-26360,27223-27252,27679-27708,28075-28104`
