### ISSUE TITLE
不知為何每次下載最後合併都會變成"本集 0MB"就失敗了

### ISSUE THREAD

**Issue by zfuchen** [miyouzi/aniGamerPlus#159]
## 問題描述
解密合并完成, 本集 0MB, 正在移至番劇目錄……
2022-02-26 01:09:15 下載完成: sn=16547  [Baha] 寶可夢超級願望[51][1080P].mp4
2022-02-26 01:09:15 任務失敗: sn=16547  title=寶可夢超級願望 [51] 10s后自動重啓,最多重試三次

主要是解密的部分出錯了，怎麼下載都是0MB，然後無法正常合併

## 錯誤截圖
https://imgur.com/SCUNqX1.png

## config.json 配置
"bangumi_dir": "~/Anime",
    "temp_dir": "~/aniGamerPlus/tmp",
    "classify_bangumi": true,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": true,
    "only_use_vip": true,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "[Baha] ",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 2,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,$
    "use_proxy": true,
    "proxy": "個人資料刪除，但確定其能正常使用無誤",
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "msg_argument_name": "message",
        "message_suffix": "追加的資訊",
        "query": [
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=123$
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=876$
        ]
    },
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": false,
    "danmu": false,
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "mobile_ads_time": 3,
    "use_dashboard": false,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5001,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 15.3,
    "database_version": 2.0,
    "telebot_notify": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 15.3,
    "database_version": 2.0,
    "telebot_notify": false,
    "telebot_token": ""
}

## sn_list.txt 配置
無使用

**最好上傳 log 檔案**

**Comment by miyouzi** [comment]
你用的命令可以貼一下嗎

**Comment by zfuchen** [comment]
> 你用的命令可以貼一下嗎

python3 aniGamerPlus.py -s 16547

就只有這行而已 我覺得是環境問題 這在Linux 16.04 LTS上大概都會有問題
(兩台不同機器都是這樣)
我換到Debian 10就沒狀況 不知道為何

**Comment by miyouzi** [comment]
目錄權限問題檢查過了嗎

**Comment by zfuchen** [comment]
[2022-02-26.log](https://github.com/miyouzi/aniGamerPlus/files/8153266/2022-02-26.log)

附上Log 目錄權限部分沒有檢查 不過因為已經用別台可以 就沒深究了

**Comment by miyouzi** [comment]
你在途中按了 `Ctrl C` 麽

**Comment by zfuchen** [comment]
> 

那個是第一part 主要是proxy第一次使用設定有誤 且不是這個issue要討論的問題
後續已設定正常 另ffmpeg確定有安裝 經常使用ffprobe等功能

第一段結束程式後 重新執行兩次 下半可以看見兩個片段都是 0MB的狀況

**Comment by miyouzi** [comment]
> > 
> 
> 那個是第一part 主要是proxy第一次使用設定有誤 且不是這個issue要討論的問題 後續已設定正常 另ffmpeg確定有安裝 經常使用ffprobe等功能
> 
> 第一段結束程式後 重新執行兩次 下半可以看見兩個片段都是 0MB的狀況

ffmpeg 版本是多少呢

**Comment by zfuchen** [comment]
![image](https://user-images.githubusercontent.com/32461811/156109359-3f5dfa43-3431-4cd4-949a-403f15736f3c.png)

ffmpeg version 2.8.17-0ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 20160609

**Comment by miyouzi** [comment]
嘗試升級一下 ffmpeg ？

**Comment by zfuchen** [comment]
> 

目前已無使用需求 故無法配合升級和後續測試

**Comment by miyouzi** [comment]
這樣的話那就先 Close 吧？
