### ISSUE TITLE
使用一段时间后总结出的问题

### ISSUE THREAD

**Issue by YFTX2015** [miyouzi/aniGamerPlus#16]
## 問題描述
1.将sn=12863添加至队列，启动程序，识别出来的却是sn=11394。
2.下载无法续传，一旦遇到网络不佳或中断，就只能重新下载。
3.相同sn只能下载一次，一旦显示任务完成，即已经将文件存入bangumi文件夹中，无论文件是否完整，无法再次下载此剧集。再次启动程序，则显示零任务，即使sn仍然保留。
4.关于自定义番剧存放目录没有详细举例说明是怎样的格式，因此按照我自己的设置，无法保存到我想要的文件夹中，只能保存到默认目录当中。
5.程序窗口不显示下载速度和进度，以及文件大小，因此无法实时掌握下载进程情况。
## 錯誤截圖
#在這裏附上錯誤的窗口截圖#
![屏幕截图(1)](https://user-images.githubusercontent.com/12757305/62510854-5f239d80-b843-11e9-98cd-b3e08b015f86.png)
![屏幕截图(3)](https://user-images.githubusercontent.com/12757305/62511265-5f249d00-b845-11e9-87b7-2a2bfff1f752.png)
![屏幕截图(4)](https://user-images.githubusercontent.com/12757305/62511267-63e95100-b845-11e9-919f-0d9e1f4f0028.png)

## config.json 配置
```
#將你的config.json内容複製到這裏#
```{
    "bangumi_dir": "C:\Users\YFTX2\Videos",（此处曾替换成"视频"）
    "temp_dir": "",
    "classify_bangumi": true,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 99999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18945",
    "use_proxy": false,
    "proxies": {
        "1": "socks5://127.0.0.1:1080",
        "2": "http://user:passwd@example.com:1000"
    },
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 7.0,
    "database_version": 2.0
}

## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```
12863
12731

**最好上傳 log 檔案**
[2019-08-06.log](https://github.com/miyouzi/aniGamerPlus/files/3470370/2019-08-06.log)

**Comment by miyouzi** [comment]
额……你的 ```multi-thread``` 和 ```multi_downloading_segment``` 配置过于夸张了以至于程序不能正常运行，建议 ```multi-thread``` 配置为 ```1```，```multi_downloading_segment``` 配置为 ```3``` 速度就足够快了。

>将sn=12863添加至队列，启动程序，识别出来的却是sn=11394

这个问题与下载模式有关，通过 ```default_download_mode``` 配置默认下载模式，你的配置为 ```latest``` 因此会下载此番剧的最后一集
![image](https://user-images.githubusercontent.com/24269465/62514583-3951c500-b852-11e9-8d02-7c0aaa97ae66.png)


>下载无法续传，一旦遇到网络不佳或中断，就只能重新下载

分段下载模式如果个别分段下载中断会自动重试以应对网络波动

>相同sn只能下载一次

根据你的需求，可以尝试使用命令行模式，详见[相关README](https://github.com/miyouzi/aniGamerPlus#%E5%91%BD%E4%BB%A4%E8%A1%8C%E4%BD%BF%E7%94%A8)

>关于自定义番剧存放目录没有详细举例说明是怎样的格式，因此按照我自己的设置，无法保存到我想要的文件夹中

你的配置 ```"bangumi_dir": "C:\Users\YFTX2\Videos"``` 在格式上没有问题，你的 log 中没有转移至番剧目录过程中相关的错误，因此不好推断这个问题在哪。
你先调整 ```multi-thread``` 和 ```multi_downloading_segment``` 的配置再下载，如果依然遇到此问题，那么再上传 log 看看。


>程序窗口不显示下载速度和进度，以及文件大小

```multi-thread``` 配置为 ```1```，使用命令行模式下载有进度显示，多线程及自动模式受限于目前技术/个人能力尚不能做到
![937400fb9f8991253ba7063185e57ee37873f203](https://user-images.githubusercontent.com/24269465/62514201-04913e00-b851-11e9-8cc6-c228a90c18fc.gif)

**Comment by YFTX2015** [comment]
sn=12863对应的是这部番剧，
![屏幕截图(5)](https://user-images.githubusercontent.com/12757305/62517672-7326c980-b85a-11e9-8eeb-e2962893439b.png)，此页面上的排序按照你刚才的截图说明，如果我要下载的是第5集，是不是应该选择largest-sn?
关于下载线程数和指定目录问题，我用两台电脑分别做了测试，一台家用，一台办公室用，两台的Anigamerplus的config.json配置完全一样，两台电脑即使按照夸张的多线程设置都能成功下载番剧，今天出现分段下载错误完全是因为我这边代理网络不稳定所致，并不是因为多线程设置过高从而导致程序不能正常运行。由于两台电脑config.json配置完全一样，所以指定存放目录也应当完全一致才对。但家用电脑就出现了实际下载目录与指定目录不一致的情况，而办公室电脑却是目录一致。我提交的是办公室电脑的数据，所以看不到log中的错误记录。回家后我会抽空提交家用电脑的log。
另外我想咨询下台湾本地有没有优质的台服代理供应商？我现在使用的HDSOCKS的HINET独立服务器线路貌似不太稳定，时常掉线。

**Comment by miyouzi** [comment]
代理这个emmm，我用的不多，推荐吧也有广告的嫌疑……我自己使用的是 ssrcloud 。

使用配置下载是自动模式，是为大批量下载番剧或监视新番更新自动下载而设计，适用于 24h 挂机运行。

你如果是想下载单集的话，命令行模式更适用，使用以下命令：
```
aniGamerPlus.exe -s 12863
```

关于多线程，即使能够工作也不建议设置得这么夸张，快赶上拒绝服务攻击了（实际上运行受限于资源与语言本身不会那么高，但是我也不知道这时候程序会发生什么）
特别是使用代理的情况，**稳定性会降低，失败率会提高**

**Comment by YFTX2015** [comment]
如果是台湾本地的，自然没必要使用代理。但是像我这种外地的，就必须使用代理，不然无法下载。动画疯不像B站台湾地区，代理断了还可以用大陆线路续传。动画疯和Viu就没法用大陆线路续传。同时最大下载分段改成1500算了，一般单集23、24分钟左右的711到720个分段，最长单集也就48分钟左右，所以1500就差不多。剧场版一般更新不如大陆快，基本上不会下。所以也没必要改得更高。

**Comment by YFTX2015** [comment]
关于代理的选择太深奥了，看了评测感觉相当复杂。我主要想找一家真正不限速的，就是我家庭网络带宽有多大，代理网络带宽也就有多大的那种。

**Comment by miyouzi** [comment]
额……你可能有些误解，```multi_downloading_segment``` 是指同时下载多少分段，而不是总共要下载多少分段，设置为```3```就已经可以接近10M/s了（基本占满我百兆带宽了）
你配置得太高的话，本地IO、代理和动画疯服务器都处于高负载的状态，每一线程都会变得不稳定

**Comment by YFTX2015** [comment]
回去后再次测试保存目录，居然对了，不晓得之前是扯的啥子拐。现在终于调成了自己想要的配置。直接运行.exe程序，不用输命令，再搭配ssrcloud中台专线，基本上能在一分钟之内下完一集。

**Comment by jokin1999** [comment]
简单来说就是不要太贪

**Comment by YFTX2015** [comment]
现在反而更贪了，因为换了机场后问题比我预想的解决得还要好得多

**Comment by jokin1999** [comment]
所以现在是多少线程？




------------------ 原始邮件 ------------------
发件人: "YFTX2015"<notifications@github.com>; 
发送时间: 2019年8月22日(星期四) 中午1:33
收件人: "miyouzi/aniGamerPlus"<aniGamerPlus@noreply.github.com>; 
抄送: "Joe"<327928971@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [miyouzi/aniGamerPlus] 使用一段时间后总结出的问题 (#16)




现在反而更贪了，因为换了机场后问题比我预想的解决得还要好得多

**Comment by YFTX2015** [comment]
还是那么多，没改

**Comment by newhy** [comment]
“相同sn只能下载一次，一旦显示任务完成，即已经将文件存入bangumi文件夹中，无论文件是否完整，无法再次下载此剧集。再次启动程序，则显示零任务，即使sn仍然保留。”

例如exe版本，把aniGamer.db删掉再开程序就好。

**Comment by YFTX2015** [comment]
这个后来面晓得了。然后V15描述的“multi_thread 設置上限為 5, multi_downloading_segment 設置上限為 5”，我还是设置成N个9，也没自动强制改成5，不晓得限制生效没得。

**Comment by miyouzi** [comment]
会在运行时重置，但不会去修改配置文件

**Comment by YFTX2015** [comment]
影不影响下载速度？上个版本平均50m/s以上，这个版本感觉达不到

**Comment by miyouzi** [comment]
在一定程度上这会有限速的效果, 最多并发25个链接, 目的就是为了减轻动画疯的负担, 目前本工具的下载速度是高出在线观看载入速度很多的.

**Comment by YFTX2015** [comment]
那下载出错次数达到一定程度后就会删除已下载数据然后自动重新下载这个问题改善没，这个相当浪费流量啊，希望可以像c0re100的工具一样无下载错误次数限制续传。

**Comment by miyouzi** [comment]
可以将分段重试次数拿出来可以让用户配置, 配置 ```-1``` 无限重试, 但是需要了解可能遇到未知错误而无限重试导致整个任务列队卡死的的情况

**Comment by YFTX2015** [comment]
OK，原来有的啊。我这边出错一般是代理某些个节点不稳定造成，切换节点应该能够解决

**Comment by miyouzi** [comment]
v16 版本已更新

**Comment by YFTX2015** [comment]
已经用了一段时间了，就是下载个别番剧的时候，下载模式选择latest或者largest-sn集数还是会识别错误，上几个版本也没把这个问题彻底解决。目前暂时只有通过切换模式来解决。

**Comment by miyouzi** [comment]
识别错误的问题具体是哪个sn/哪部番？想下载的具体是哪些集数？

**Comment by YFTX2015** [comment]
比较明显的是fate系列，现在正在更新的巴比伦战线，以及上两个季度还有一部，搞忘名字了，反正就是有特别篇的那种，一般就是在正片最新一集跟特别篇之间识别有误。这种好像只有选largest-sn时才能获取正片最新一集，选latest只能获取特别篇。还有一部番是真记不起名字了，没有特别篇，但是选largest-sn得到的却是第一集，只有切换成latest才能获取最新一集，除开上面提到的这几种情况，其它番剧在选largest-sn时均能获取到最新一集。具体的话，等我哪天再次遇到出错的时候及时记录，然后再反馈。

**Comment by YFTX2015** [comment]
一般下载单集，除非有几个动画在同一个时间点或者相近时间点更新，那样就会同时建立几个任务



------------------ 原始邮件 ------------------
发件人: "米柚子"<notifications@github.com>; 
发送时间: 2019年10月24日(星期四) 下午5:03
收件人: "miyouzi/aniGamerPlus"<aniGamerPlus@noreply.github.com>; 
抄送: "アクセラレータ"<443451614@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [miyouzi/aniGamerPlus] 使用一段时间后总结出的问题 (#16)




latest 获取的是网页上排最后的一集，特别篇排在正片的下面，因此会获取到特别篇。
 
largest-sn 获取的是 sn 最大的一集，sn 一般是随着视频上传顺序增大的，因此也可以说是最近更新的视频。
 
你说的 largest-sn 获取到的是第一集猜测可能是第一集有什么问题，事后更换视频导致成了实际上的最近上传。
 
你的情况是全集下载吗？如果是，那么推荐使用 all 模式。
 
如果是单集下载，那推荐使用命令行下载，命令行下载默认单集模式。

**Comment by miyouzi** [comment]
正在连载的新番动画，```largest-sn``` 模式可能会更接近你的需求，你应该是使用自动模式吧？```largest-sn``` 会更新 ```sn_list.txt``` 中的番剧的最近上传，如果番剧途中更新了 SP 之类的，也不会落下，之后正片更新也能正确捕捉。

**Comment by YFTX2015** [comment]
最近当动画疯在同一个时间点更新连续两集的情况下，下载模式除了ALL的其它模式，在list-sn里填入两个编号，最终工具只能识别出一集。举例说明，BANGDREAM!D第三季最近都是逢周二19：00连更两集，比如8、9集，当把两集的编号填入list-sn后，下载模式选择latest或者largest-sn，然后点击exe文件，只能识别出第9集。接着把第9集的编号删除，只保留第8集的编号，结果识别出来的还是第9集。因此建议exe档下载模式增加指定集数下载模式，就像命令行一样。另外，我这边命令行用不起，依赖是安装了的，cmd输入命令回车后直接返回目录，不晓得是咋回事。另外抽时间截图。
