### ISSUE TITLE
discord 通知錯誤

### ISSUE THREAD

**Issue by Hoshino0881118** [miyouzi/aniGamerPlus#167]
## 問題描述
discord通知有正確送出訊息
後臺顯示下載錯誤
影片檔案有正確的進入到我指定位置
![螢幕擷取畫面 2022-03-19 003858](https://user-images.githubusercontent.com/26840198/159046145-f97a3863-d453-4c30-85d5-2c2cd8b08675.png)

## config.json 配置
[config.txt](https://github.com/miyouzi/aniGamerPlus/files/8306314/config.txt)

## sn_list.txt 配置
sn_list是流水號
有重新測試過好幾次
#97 

## log 檔案
[2022-03-19.log](https://github.com/miyouzi/aniGamerPlus/files/8306312/2022-03-19.log)

**Comment by kirbyloco** [comment]
@Hoshino0881118 
已推修正PR，等作者後續合併。

話說sn_list用流水號會增加對動畫瘋的伺服器負擔，
而且在前期檢查的時候也會增加檢查的時間。

如果不嫌棄的話，可以用[https://github.com/kirbyloco/anigamerdatabase/blob/master/sn_list.txt](https://github.com/kirbyloco/anigamerdatabase/blob/master/sn_list.txt)
這是每天早上8點會自動更新的sn_list列表。

**Comment by Hoshino0881118** [comment]
@kirbyloco 
好的

我是幾天才會掃一次
但我還是會嘗試轉用https://github.com/kirbyloco/anigamerdatabase/blob/master/sn_list.txt
謝謝
