### ISSUE TITLE
影片下載不完全

### ISSUE THREAD

**Issue by ceres512** [miyouzi/aniGamerPlus#169]
## 問題描述
您好，我使用「aniGamerPlus_v22.6」下載「劇場版 吸血鬼僕人 -Alice in the Garden- [電影] 線上看 - 巴哈姆特動畫瘋」，畫質為1080P，但下載下來的影片長度只到01:13:38，720P的則正常，線上觀賞也沒問題，不知是否為個別原因？謝謝。

## config.json 配置
[config.json.txt](https://github.com/miyouzi/aniGamerPlus/files/8311083/config.json.txt)

##  log 檔案
[logs.zip](https://github.com/miyouzi/aniGamerPlus/files/8311097/logs.zip)

**Comment by miyouzi** [comment]
更新 ffmpeg 試試？我這測試下載沒問題，另外建議使用最新版測試。

**Comment by ceres512** [comment]
下載下來的影片長度還是只到01:13:38( 影片全長為01:24:42 )，ffmpeg我是在 https://www.gyan.dev/ffmpeg/builds/ 這個網站下載的，版本是**2022-03-17**，軟體也更新到**v23.1**，下載其他影片完全正常。
##


![2022-03-21_190825](https://user-images.githubusercontent.com/97873210/159249405-05667297-e00b-4992-8e37-4bb2c34c7ac8.png)

**Comment by miyouzi** [comment]
你下載的影片 Hash 是多少，我的是 
```
MD5: 25ED976378DF609CEB3A6FA9EDD60DD0
SHA1: 6A6F866D920A72DC68D7672EEAA88467A6A40EE9
CRC32: 53FB3794
```

PS:  Hash 軟體可以從這裏下載 http://keir.net/hash.html

![image](https://user-images.githubusercontent.com/24269465/159267325-97b4a739-65a6-4d90-ac2c-82b59a185a91.png)

**Comment by miyouzi** [comment]
嘗試使用這個版本的 ffmpeg 呢 ？

[ffmpeg.zip](https://github.com/miyouzi/aniGamerPlus/files/8316742/ffmpeg.zip)

**Comment by ceres512** [comment]
這次下載的影片長度是完整的，但有一小段播放起來怪怪的，使用其他播放器也是一樣，如下所示︰

https://user-images.githubusercontent.com/97873210/159434709-8646a390-94f1-4ca7-b9c0-17aae4207746.mp4

**Comment by miyouzi** [comment]
嘗試使用 Potplayer 播放呢？ 另外你的OS是什麼版本呢？CPU使用的是？

**Comment by miyouzi** [comment]
我這邊用瀏覽器在綫看，在這個地方也是播放有問題，可能是動畫瘋本來片源就有問題吧？

**Comment by ceres512** [comment]
用PotPlayer也是一樣。
下載720P是正常的。
好的，我會回報動畫瘋並再繼續下載試試看，謝謝您。
##
![2022-03-22_221627](https://user-images.githubusercontent.com/97873210/159503502-3f101164-e1a6-40ce-a23e-a639fb3a73e8.png)
##
![2022-03-22_221744](https://user-images.githubusercontent.com/97873210/159503543-7506f8b9-77f8-46a0-ba78-7ad5ec6c9bef.png)
