### ISSUE TITLE
想提个小要求：下载完毕自动关机

### ISSUE THREAD

**Issue by wyzsfxy** [miyouzi/aniGamerPlus#17]
能不能添加，下载完毕自动关机的功能呢，
我觉得这个功能还是挺实用的，
本地带宽小，只能靠时间来磨下载了。

**Comment by miyouzi** [comment]
请问用的是自动模式还是命令行模式呢？

这个功能在设计上和自动模式有点出入，自动模式设计上是定时检查更新，并且每次更新都可能添加新的任务。

命令行模式任务数量是固定的，可以考虑加上这个功能，但是命令行模式不会记录下载状态，也就是说如果下一季度的番剧，中途中断了，需要自己再次打命令补上缺少的集数。

**Comment by wyzsfxy** [comment]
我使用的是自动模式
是挺希望在config.json里面加上这样一个开关的
不过如果设计冲突的话，可以不用理会我这个要求

**Comment by miyouzi** [comment]
emmm，似乎挺多人需要单次大批量下载

这样吧，命令行模式再多一个功能，单次读取 sn_list 中的任务，并且记录任务状态，方便重启下载，再附带一个全部下载完成后执行自定义命令选项（可以是关机，启动一个批处理等等）。

这样如何

**Comment by wyzsfxy** [comment]
我觉得可行，那就麻烦你了

**Comment by miyouzi** [comment]
已更新 [v15](https://github.com/miyouzi/aniGamerPlus/releases/tag/v15)

默认命令为一分钟后关机（Windows限定），取消关机使用 ```shutdown -a``` 命令

**Comment by wyzsfxy** [comment]
非常感谢你的工作！
继续撸下载去了233
