### ISSUE TITLE
v23.1 『手動添加任務』會顯示『配置提交失敗』

### ISSUE THREAD

**Issue by nfr472xb** [miyouzi/aniGamerPlus#178]
## 問題描述
aniGamerPlus_v23.1_windows_64bit
在web面板『手動添加任務』會顯示錯誤

## 錯誤截圖
![Snipaste_2022-04-05_16-43-23](https://user-images.githubusercontent.com/26101505/161715061-fdf6b121-3de3-4105-89fe-1c4d3b5c184b.png)

## config.json 配置
```
預設
```

## sn_list.txt 配置
```
預設
```

**最好上傳 log 檔案**
[web.log](https://github.com/miyouzi/aniGamerPlus/files/8416455/web.log)

**Comment by miyouzi** [comment]
最大并发下載數要填，最少 1

**Comment by nfr472xb** [comment]
> 最多下載數要填，最少1個

確實填入就可以了，感謝回覆
