### ISSUE TITLE
希望能支援線上sn_list

### ISSUE THREAD

**Issue by XPRAMT** [miyouzi/aniGamerPlus#180]
因為有多台電腦，需要經常在不同電腦間同步sn_list
希望能在config.json填入sn_list的網址，直接讀取線上的sn_list，省去手動同步的麻煩

**Comment by miyouzi** [comment]
使用 [resilio](https://www.resilio.com/individuals/) 或 [verysync](http://www.verysync.com/) 來同步檔案的方案如何呢？

將 sn_list 放入同步資料夾，再使用 `ln` (Linux) 或 `mklink` (Windows) 命令把 sn_list 鏈接到程式文件夾的方案你看怎麽樣？
