### ISSUE TITLE
英文版Windows作業系統下EXE檔案亂碼

### ISSUE THREAD

**Issue by SpectreAX** [miyouzi/aniGamerPlus#186]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#

英文版Windows作業系統下亂碼
## 錯誤截圖
#在這裏附上錯誤的窗口截圖#
![Snipaste_2022-06-06_14-46-39](https://user-images.githubusercontent.com/39104592/172110900-5865736d-88a0-48ad-a755-04549439d574.png)

**Comment by miyouzi** [comment]
系統有中文字體嗎，在console可以顯示的字體

**Comment by SpectreAX** [comment]
@miyouzi 有的，设置后可以正常显示了，谢谢解答
