### ISSUE TITLE
請問如何只下載彈幕？動畫瘋網站的個人彈幕過濾套用？

### ISSUE THREAD

**Issue by NiGHTsC** [miyouzi/aniGamerPlus#189]
## 問題描述
1. 請問是否一定要下載影片檔才能下載彈幕？
2. 請問彈幕預設是否會自動套用動畫瘋網站的個人彈幕過濾（使用會員cookie的情況下）

謝謝您。

**Comment by gitqwerty777** [comment]
> 請問是否一定要下載影片檔才能下載彈幕？

應該是，可自行修改程式碼

> 請問彈幕預設是否會自動套用動畫瘋網站的個人彈幕過濾（使用會員cookie的情況下）

會

**Comment by miyouzi** [comment]
對於命令行模式，使用 `-i -d` 參數可以只下載彈幕。

如果想更新自動模式下載過的所有彈幕，可以用 `-m db` 參數運行（v24.0以上版本支持）
