### ISSUE TITLE
請教python問題

### ISSUE THREAD

**Issue by hahadown** [miyouzi/aniGamerPlus#19]
## 問題描述
#python3 還是有缺少元件#
我有爬文了還是弄不好
有去readme看過了
首先我有下載FFMPEG 跟 python 3.8版本安裝好了
然後下載源碼跟升級的那兩句是什麼意思?要怎麼安裝
抱歉!謝謝幫忙
## 錯誤截圖
https://imgur.com/q0JAKBv.png

**Comment by miyouzi** [comment]
是否先安裝好依賴？即使用前輸入指令 ```pip3 install requests beautifulsoup4 lxml termcolor chardet pysocks```

**Comment by hahadown** [comment]
我誤打誤撞弄成功了~太感謝了
我把後面指令改aniGamerPlus -s XXX就可以單集模式了
謝謝您
