### ISSUE TITLE
[功能請求] 命令模式增加功能-輸出影片m3u8網址

### ISSUE THREAD

**Issue by Hiura-Souji** [miyouzi/aniGamerPlus#190]
## 問題描述
希望增加命令行模式功能，
給予一組sn或網址，可以只返回單純的M3U8網址（可下載、可播放的）
想用於 本地影音播放器播放
不知是否方便可行？
感謝您~

**Comment by miyouzi** [comment]
影片是加密的，不保證拿到的 m3u8 的網址你可以播放

獲取 m3u8 的方法在這，你可以自己調用 https://github.com/miyouzi/aniGamerPlus/blob/master/Anime.py#L489

範例：
```python
a = Anime('10991')
print(a.get_m3u8_dict())
```

**Comment by Hiura-Souji** [comment]
感謝您~
我對PYTHON不熟
但有從這參考改寫了
是可以取得網址和播放的
只是我卡關在刷新cookie和取得這關
所以才想說能否用命令行調用 ^^"

**Comment by miyouzi** [comment]
鑒於適用面較窄，這邊就不做為新功能了，自行改寫即可
