### ISSUE TITLE
從版本 22.1 到 23.1，aniGamerPlus.exe 就無法正常執行，求解 …

### ISSUE THREAD

**Issue by bossgder** [miyouzi/aniGamerPlus#191]
## 問題描述
從版本 22.1 到 23.1，aniGamerPlus.exe 就無法正常執行 (附圖)，即使從這下載乾淨未任何修改的，直接執行都會出現如附圖的錯誤 

## 錯誤截圖
![2022-07-08](https://user-images.githubusercontent.com/86844456/178001069-59f10560-6bfa-455e-b673-d966f6fd8bb3.png)

## config.json 配置
```
都未修改，直接執行，所以就是預設的
```

## sn_list.txt 配置
```
都未修改，直接執行，所以就是預設的
```

**最好上傳 log 檔案**
所以也沒產生 log 檔 ……

**Comment by miyouzi** [comment]
Windows版本是多少？

**Comment by bossgder** [comment]
可以執行了！miyouzi 感謝您 
我的確關掉更新補丁了。

(我第一次發問，所以我要自已點按 close with comment 嗎？)

**Comment by miyouzi** [comment]
是的
