### ISSUE TITLE
Synology Docker安裝問題

### ISSUE THREAD

**Issue by Arcelibs** [miyouzi/aniGamerPlus#193]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#

嘗試於Synology Nas上面的Docker安裝aniGamerPlus

使用tonypepe/anigamerplus latest

有映射/config.json到NAS資料夾中的config.json
![image](https://user-images.githubusercontent.com/49543451/178144018-159783d5-5b90-4ddf-9554-959517e52197.png)

## 錯誤截圖
#在這裏附上錯誤的窗口截圖#

![image](https://user-images.githubusercontent.com/49543451/178144264-257185a4-501c-46e5-9eeb-7a375f6d520a.png)

## config.json 配置
```
#將你的config.json内容複製到這裏#
```
[confg.json.txt](https://github.com/miyouzi/aniGamerPlus/files/9079017/confg.json.txt)

## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```

**最好上傳 log 檔案**

**Comment by miyouzi** [comment]
confg.json 不能這麽寫，程式讀取的 json 不支持注釋， 你需要將 `config-sample.json` 改名成 `config.json` 再以自己需要去配置

**Comment by Arcelibs** [comment]
> 

這個有教學嗎，不是很懂所謂的config-sample.json 改名成 config.json是什麼意思，Docker新手

**Comment by miyouzi** [comment]
https://github.com/miyouzi/aniGamerPlus/blob/master/config-sample.json

**Comment by Arcelibs** [comment]
解決了，謝謝
