### ISSUE TITLE
購買動畫瘋會員後判斷非VIP會員，無法下載1080P

### ISSUE THREAD

**Issue by Arcelibs** [miyouzi/aniGamerPlus#194]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#

購買動畫瘋會員後判斷非VIP會員，無法下載1080P

## 錯誤截圖
#在這裏附上錯誤的窗口截圖#

![image](https://user-images.githubusercontent.com/49543451/178464203-df10ede6-66e6-486a-8333-9e93f18b40c0.png)

![image](https://user-images.githubusercontent.com/49543451/178464546-8914ce40-404b-4b70-9253-e96cc5554444.png)

## config.json 配置
```
#將你的config.json内容複製到這裏#
```
[config.json.txt](https://github.com/miyouzi/aniGamerPlus/files/9091757/config.json.txt)

## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```

**最好上傳 log 檔案**

**Comment by miyouzi** [comment]
你是用docker吧，有映射cookie嗎？

**Comment by miyouzi** [comment]
@TonyPepeBear 大佬要不救一下這個孩子吧（
