### ISSUE TITLE
控制台一直洗這個訊息，aniGamersPlus控制台網站進不去

### ISSUE THREAD

**Issue by Mina7160** [miyouzi/aniGamerPlus#199]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#
一開始在aniGamerPlus的網站手動添加任務
因為第一次提交時沒反應，所以連續提交了4次，後來就變成這樣了
## 錯誤截圖
#在這裏附上錯誤的窗口截圖#
![螢幕擷取畫面 (35)](https://user-images.githubusercontent.com/99324906/186377051-c3a953a2-15c1-4302-8026-a490a27fbafb.png)

## config.json 配置
```
#將你的config.json内容複製到這裏#
```
{
    "bangumi_dir": "",
    "temp_dir": "",
    "classify_bangumi": false,
    "check_frequency": 0,
    "download_resolution": "1080",
    "lock_resolution": false,
    "only_use_vip": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 0,
    "multi_upload": 3,
    "segment_download_mode": false,
    "multi_downloading_segment": 0,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": false,
    "customized_video_filename_prefix": "",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36",
    "use_proxy": false,
    "proxy": "socks5://:",
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "msg_argument_name": "message",
        "message_suffix": "追加的資訊",
        "query": [
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
        ]
    },
    "telebot_notify": false,
    "telebot_token": "",
    "discord_notify": false,
    "discord_token": "",
    "plex_refresh": false,
    "plex_url": "",
    "plex_token": "",
    "plex_section": "",
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": false,
    "danmu": false,
    "danmu_ban_words": [],
    "check_latest_version": false,
    "read_sn_list_when_checking_update": false,
    "read_config_when_checking_update": false,
    "ads_time": 25,
    "mobile_ads_time": 3,
    "use_dashboard": true,
    "dashboard": {
        "host": "0.0.0.0",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": false,
    "quantity_of_logs": 7,
    "config_version": 16,
    "database_version": 2.0
}
## sn_list.txt 配置
```
10147 all # 前進吧！登山少女 第三季 [1]
@2018十月番
11285 <史萊姆> # 關於我轉生變成史萊姆這檔事
@2019冬季番
11390 all #笑容的代價 01
11388 # BanG Dream！第二季
11465 all <約會大作戰 III> # 約會大作戰 DATE A LIVE 第三季
@
11317 lastest # SSSS.GRIDMAN
#將你的sn_list.txt内容複製到這裏#
```

**最好上傳 log 檔案**

**Comment by miyouzi** [comment]
`"check_frequency": 0`

檢查更新間隔時間太短了

**Comment by Mina7160** [comment]
> `"check_frequency": 0`
> 
> 檢查更新間隔時間太短了

感謝，問題已解決
