### ISSUE TITLE
cookie 不會自動更新

### ISSUE THREAD

**Issue by a0960211197** [miyouzi/aniGamerPlus#2]
已經有用ＣＨＲＯＭＥ擷取 但是過一天之後就會過期 返回訪客模式
這時候還要再重複一次 這樣是否正常?

我的環境是OSX10.14.3
python 3.7.2

**Comment by miyouzi** [comment]
確認从無痕模式拿的cookie嗎？
一個cookie祇有一次刷新機會，因此从無痕模式拿到cookie后，請不要在別的地方使用此cookie。

**Comment by a0960211197** [comment]
確定是從無痕模式取得的！也有勾選（保持登入狀態）！
只有一次更新機會？代表還是會過期？我沒有在其他地方使用這個COOKIE。

**Comment by miyouzi** [comment]
巴哈的cookie大約是一天更新一次。

意思是一個cookie大約可以使用24小時，到期時，巴哈會根據舊cookie給一個新cookie，“一次更新機會”指的是給新cookie的機會只有一次，往後如過再使用舊cookie則不會給新cookie了。

也有可能OSX的環境問題導致新cookie保存失敗（我沒有OSX可以測試），請問有更多資訊可以提供嗎？（是否提示保存失敗之類）

**Comment by a0960211197** [comment]
在終端機上有顯示cookie更新失敗！然後就會使用訪客模式下載，cookie取得也沒有超過24小時。
我在這附上log檔案
時間在 2019-02-08 19:34:33
[2019-02-08.log](https://github.com/miyouzi/aniGamerPlus/files/2847729/2019-02-08.log)

**Comment by miyouzi** [comment]
會不會是```cookie.txt```權限問題呢?

權限改成 ```777``` 呢

**Comment by a0960211197** [comment]
權限問題一開始我就已經設定可讀取寫入了!
我剛剛有用終端機查詢過，也確定是777。

<img width="381" alt="2019-02-09 7 41 55" src="https://user-images.githubusercontent.com/47473831/52520302-0c599680-2ca3-11e9-9ea0-3e777c54dcfa.png">

我是有把程式的主目錄放在ＮＡＳ上 用ＡＦＰ的方式連線，會不會是這個原因？
我把主程式拉回ＭＡＣ上再試試看會不會有這個問題。

**Comment by a0960211197** [comment]
早安！我昨天用的方法還是一樣沒有改善！
[2019-02-10.log](https://github.com/miyouzi/aniGamerPlus/files/2848290/2019-02-10.log)
早上３點為路由器重開時間。

還是有偵錯的方式？

**Comment by miyouzi** [comment]
小更新了一下，添加了幾個 log 項目，你可以升級后再嘗試一下，然後把 log 發上來

新增的清晰度鎖定功能，指定清晰度不存在則放棄下載，可以避免下載到低清源，通過 ```"lock_resolution": true``` 開啓

再嘗試時，保留原來cookie一份，然後cookie更失敗后，對比一下```cookie.txt``` 的内容是否有變化

然後下次把配置文件也發上來看一下

**Comment by a0960211197** [comment]
久等了！
我今天放置了一下 cookie 沒有更新到！裡面有放置舊的cookie 拷貝.txt。
我把檔案配置擋壓縮上傳到這裡。
[aniGamerPlus.zip](https://github.com/miyouzi/aniGamerPlus/files/2848905/aniGamerPlus.zip)

**Comment by miyouzi** [comment]
這個情況的確是從來都沒有收到新cookie，被巴哈强制登出也是一種可能，不過就我目前的使用情況來看，這個可能性比較小，你説了```無痕模式取得的！也有勾選（保持登入狀態）！```且```沒有在其他地方使用這個COOKIE```這兩點都是無誤的話，在登陸時，是否有勾選```記住帳號```呢

**Comment by miyouzi** [comment]
另外，過期cookie雖然不能做登陸用途了，但裏面是包含你的巴哈ID，等級，昵稱的，如果介意的話自行刪除那個檔壓縮吧

**Comment by a0960211197** [comment]
無痕模式 有勾選保持登入狀態、記住帳號。
我試看看不勾選記住帳號試試看！

**Comment by miyouzi** [comment]
我好像有了頭緒，能説明一下你使用的是什麽瀏覽器嗎？UA是什麽呢？
UA可以前往 **https://www.whatismybrowser.com/detect/what-is-my-user-agent** 查詢

**Comment by a0960211197** [comment]
我巴哈是用Chrome，cookie是用Chrome無痕模式抓的。
<img width="612" alt="2019-02-10 10 08 50" src="https://user-images.githubusercontent.com/47473831/52534774-9166ad80-2d80-11e9-9dfe-8d60e6de694d.png">

Safari也會使用，不過我沒有用他的cookie。

**Comment by miyouzi** [comment]
定位到問題了，我的UA寫的是Windows，你的是 Mac OS，不一致導致沒有收到新cookie。
給我一些時間修復這個問題：新增配置項目，可以讓用戶自定義UA，此UA需要和你拿cookie的瀏覽器的UA一致。

**Comment by miyouzi** [comment]
更新了，再試試如何（readme已更新）

**Comment by a0960211197** [comment]
目前已經正常了！也有自動更新cookie。
感謝你的協助！
