### ISSUE TITLE
命令列下載時的命名

### ISSUE THREAD

**Issue by zacharyptt** [miyouzi/aniGamerPlus#20]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#

我用命令列下載時,番劇名稱最後會有"線上看"三個字,
使用命令列有辦法自訂名稱嗎?

我看README裡面的截圖沒有"線上看"三個字

**Comment by miyouzi** [comment]
已確認是巴哈的改動，事後會進行更新。

**Comment by miyouzi** [comment]
[v16.1](https://github.com/miyouzi/aniGamerPlus/releases/tag/v16.1)  已更新
