### ISSUE TITLE
Docker image build `gevent` error

### ISSUE THREAD

**Issue by JuenTingShie** [miyouzi/aniGamerPlus#201]
## 問題描述
armhf build Docker image `gevent` will error

## 錯誤截圖
error message like this: (https://github.com/gevent/gevent/issues/1801)

change requirement.txt `gevent` version like this: (https://github.com/reddit/experiments.py/pull/61/files#diff-f9d77b6d40ed3892a4d93df2b3fd88a012ab9844f6e143842b86f47e199c4611R11) fix build problem. 
Don't know if this problem only effected on armhf device?

Also, based on some tutorial, I forked repo and use Github Action to create armhf version's Docker image.

```bash
docker pull sating/anigamerplus:armhf
```

It takes action a lot of time to build(46m 46s), but after all, it build successfully.

**Comment by miyouzi** [comment]
@TonyPepeBear Please check

**Comment by JacobLinCool** [comment]
There is a PR that fixed the problem: https://github.com/miyouzi/aniGamerPlus/pull/200

And I have pushed an image (`amd64` / `arm64`) here: https://hub.docker.com/r/jacoblincool/anigamerplus

But I didn't try `armhf` on that branch.

**Comment by TonyPepeBear** [comment]
why use port `5001` but `5000`?

**Comment by JacobLinCool** [comment]
> why use port `5001` but `5000`?

Because port `5000` has been occupied by AirPlay on macOS since Monterey.

> I noticed that this breaking change may have a larger impact than I thought. Maybe just adding some troubleshooting section in the document is better?

**Comment by JuenTingShie** [comment]
Well I think port is not the problem that this issue for.

In my opinion, so this problem might cause by CPython's version, so if change `gevent` version will fix it and all works OK, maybe you can consider upgrade it.

**Comment by JacobLinCool** [comment]
Sorry for the off-topic comments, we are talking about another change in the PR. I marked it as off-topic.

I agree with you, the breaking change of CPython interface caused the build process failed on all platform, not only on `arm/v7`, so I have upgraded `gevent` version to `21.12.0` in the PR. And the build process works fine on both `amd64` and `arm64`.

I just tested to build the PR for `arm/v7`, it fails on `python:slim` base image but works on `python:latest` base image.

I would like to check it later.

**Comment by JacobLinCool** [comment]
I pushed new commits to the [PR](https://github.com/miyouzi/aniGamerPlus/pull/200).

The new dockerfile works on `amd64`, `arm64`, and `armhf`.

Also, my image is updated with the new version, feel free to test it. [Docker Hub](https://hub.docker.com/r/jacoblincool/anigamerplus/tags)

**Comment by TonyPepeBear** [comment]
Thanks for your working.

But you modify port in PR #200, I think @miyouzi will no merge these changes.

Maybe you can let #200 focus on fixing docker building errors. Let @miyouzi merge #200, then I will rebuild the official docker image.

**Comment by TonyPepeBear** [comment]
And if you want to change the default port to `5000`, I think you can discuss it with @miyouzi and create another PR.
