### ISSUE TITLE
下載錯誤(AttributeError: 'NoneType' object has no attribute 'h1')

### ISSUE THREAD

**Issue by NiGHTsC** [miyouzi/aniGamerPlus#204]
## 問題描述
2022-10-03 17:44:58 讀取cookie 發現cookie檔案
2022-10-03 17:44:58 讀取cookie 已讀取cookie
2022-10-03 17:44:58 解析模式: sn=20530	Web解析
2022-10-03 17:44:59 ERROR: 該 sn 下真的有動畫？: sn=20530	
2022-10-03 17:44:59 抓取失敗: sn=20530	抓取影片信息時發生未知錯誤: 1
2022-10-03 17:44:59 抓取異常: sn=20530	異常詳情:
Traceback (most recent call last):
  File "Anime.py", line 137, in __get_title
AttributeError: 'NoneType' object has no attribute 'h1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aniGamerPlus.py", line 55, in build_anime
  File "Anime.py", line 67, in __init__
  File "Anime.py", line 142, in __get_title
SystemExit: 1

## 錯誤截圖
![Screenshot 2022-10-03 181721](https://user-images.githubusercontent.com/16272968/193696219-43960dee-1790-4d39-877c-77f1c8612069.jpg)

## config.json 配置
```
{
    "bangumi_dir": "R:\\",
    "temp_dir": "R:\\",
    "classify_bangumi": true,
    "classify_season": false,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": true,
    "only_use_vip": true,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 3,
    "multi_upload": 1,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "[BhT]",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
    "use_proxy": false,
    "proxy": "http://user:passwd@example.com:1000",
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "msg_argument_name": "message",
        "message_suffix": "追加的資訊",
        "query": [
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
        ]
    },
    "telebot_notify": false,
    "telebot_token": "",
    "telebot_use_chat_id": false,
    "telebot_chat_id": "",
    "discord_notify": false,
    "discord_token": "",
    "plex_refresh": false,
    "plex_url": "",
    "plex_token": "",
    "plex_section": "",
    "plex_naming": false,
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": false,
    "danmu": true,
    "danmu_ban_words": [],
    "check_latest_version": false,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "mobile_ads_time": 3,
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 3000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 17.0,
    "database_version": 2.0
}
```

**最好上傳 log 檔案**
[2022-10-03.log](https://github.com/miyouzi/aniGamerPlus/files/9701409/2022-10-03.log)
[web.log](https://github.com/miyouzi/aniGamerPlus/files/9701411/web.log)

謝謝，辛苦了。

**Comment by miyouzi** [comment]
用瀏覽器去登錄看看是不是被機器人認證擋了，然後嘗試把 UA 設置成你常用的瀏覽器看看

**Comment by NiGHTsC** [comment]
> 用瀏覽器去登錄看看是不是被機器人認證擋了，然後嘗試把 UA 設置成你常用的瀏覽器看看

用Firefox/Chrome重新登入，切換兩個的UA，還是同樣的錯誤訊息…

**Comment by miyouzi** [comment]
瀏覽器能直接觀看嗎？

**Comment by NiGHTsC** [comment]
> 瀏覽器能直接觀看嗎？

1080p，限付費番都沒問題。

**Comment by miyouzi** [comment]
`"use_mobile_api": true`  嘗試用 APP API 來解析看看

**Comment by miyouzi** [comment]
能更換 IP 能不能解決，比如重新 PPPoE 撥號

**Comment by kirbyloco** [comment]
@NiGHTsC 
你地區和IP是在台灣?

**Comment by NiGHTsC** [comment]
不是，我是掛付費VPN，PureVPN

**Comment by kirbyloco** [comment]
@NiGHTsC 
那請先確定VPN是全局模式，
另外你用瀏覽器的時候會遇到是否為機器人的頁面嗎?

**Comment by NiGHTsC** [comment]
> @NiGHTsC 
那請先確定VPN是全局模式， 

PureVPN應該是預設全局的，我FF/Chrome兩邊都能看，一個沒登入有廣告一個有登入沒廣告

> 另外你用瀏覽器的時候會遇到是否為機器人的頁面嗎?

沒掛VPN的話有時候會出現

**Comment by kirbyloco** [comment]
@NiGHTsC 
你VPN是裝windows exe的還是瀏覽器的擴充套件?

**Comment by NiGHTsC** [comment]
是直接安裝軟體exe的，所以正常來說是整台的網路
我再跑一次沒掛VPN的，訊息是如下
![Screenshot 2022-10-04 131516](https://user-images.githubusercontent.com/16272968/193884477-abaff5b8-0a22-432b-946b-129708ce7096.jpg)
```
2022-10-04 13:14:36 自動模式啓動aniGamerPlus 當前aniGamerPlus版本: v24.1 
2022-10-04 13:14:36 工作目錄: C:\Users\NiGHTs\Desktop\aniGamerPlus\!NEW 
2022-10-04 13:14:40 Web控制面板已啓動 訪問地址: http://127.0.0.1:3000
2022-10-04 13:14:40 開始更新 
2022-10-04 13:14:40 讀取cookie 發現cookie檔案
2022-10-04 13:14:40 讀取cookie 已讀取cookie
2022-10-04 13:14:40 解析模式: sn=20530	APP解析
2022-10-04 13:14:42 更新資訊: sn=20530	正在檢查《關於我轉生變成史萊姆這檔事 第二季》
2022-10-04 13:14:42 解析模式: sn=20527	APP解析
2022-10-04 13:14:42 加入任务列隊: sn=20527	
2022-10-04 13:14:42 更新資訊 本次更新添加了 1 個新任務, 目前列隊中共有 1 個任務
2022-10-04 13:14:42 更新终了 
2022-10-04 13:14:42 解析模式: sn=20527	APP解析
2022-10-04 13:14:44 下載異常: sn=20527	發生未知錯誤: Expecting value: line 1 column 1 (char 0)
2022-10-04 13:14:44 下載異常: sn=20527	異常詳情:
Traceback (most recent call last):
  File "requests\models.py", line 971, in json
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aniGamerPlus.py", line 262, in worker
  File "Anime.py", line 862, in download
  File "Anime.py", line 447, in __get_m3u8_dict
  File "Anime.py", line 349, in get_device_id
  File "requests\models.py", line 975, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2022-10-04 13:14:44 任务失敗: sn=20527	title="關於我轉生變成史萊姆這檔事 第二季 [1] [特別篇]" 從任務列隊中移除, 等待下次更新重試.
```

**Comment by kirbyloco** [comment]
@NiGHTsC 
PureVPN有提供Proxy模式，
嘗試把Proxy填入config.json試試看

或嘗試使用PureVPN提供另外的使用方式，
[PureVPN WireGuard](https://support.purevpn.com/setup-wireguard-on-windows) 

如果上述的方法不行，
那基本確定是被機器人認證擋下來了。

**Comment by NiGHTsC** [comment]
Proxy也沒用
Wireguard則是要等PureVPN移機完成，要4~~`~~~~-6個禮拜…

**Comment by miyouzi** [comment]
> Proxy也沒用 Wireguard則是要等PureVPN移機完成，要4~~`~~~~-6個禮拜…

你的proxy設置是什麼樣的？協議應該是 http

**Comment by NiGHTsC** [comment]
就照你提供的連結，找到TW代理 - prox-tw.pointtoserver.com
再加上帳密輸入到config.json
![Proxy](https://user-images.githubusercontent.com/16272968/193979148-278471b4-9276-42b8-a106-69bd660c6b3d.png)

**Comment by miyouzi** [comment]
> 就照你提供的連結，找到TW代理 - prox-tw.pointtoserver.com 再加上帳密輸入到config.json ![Proxy](https://user-images.githubusercontent.com/16272968/193979148-278471b4-9276-42b8-a106-69bd660c6b3d.png)

還是一樣的報錯嗎？

這個代理在 Windows 的設置上（或者用Chrome擴充套件SwitchyOmega）確認是可以使用的嗎？

**Comment by NiGHTsC** [comment]
抱歉，這麼晚才回覆，最近才又有下載的需求

有發現可以下載的方法了，但希望以下的內容不會造成您們的不愉快
－－－
就是我剛剛手動用Addon截取m3u8網址，再用**N_m3u8DL-CLI**下載，是可以順利下載1080p檔的
但畢竟**N_m3u8DL-CLI**只是下載器，m3u8網址還是要手動一集一集打開截取…

希望這個有幫助到您們。
PS: Wireguard有試過了，還是不行
![Screenshot 2023-01-06 131412](https://user-images.githubusercontent.com/16272968/211073303-40b06a98-e50f-4345-b2da-4576a38f77c4.jpg)
PS2: SwitchyOmega我弄不出來，一直顯示Time out…
