### ISSUE TITLE
十月十二号后是不是下载分辨率也限制

### ISSUE THREAD

**Issue by asd01234** [miyouzi/aniGamerPlus#209]
## 問題描述
#十二号之后我用的所有台湾节点都只能下载360p的分辨率了，不管是不是登录账号都一样一样的，我用的是aniGamerPlus_v23.7_ryan_fork_windows_64bit#

## 錯誤截圖
#
![Y SOZTF)X2 K0NA26XWS0HD](https://user-images.githubusercontent.com/115143930/195825708-c5b99c7d-a621-4011-8eff-86e37a2146be.png)
![E4QDD9%DXS 3}IL(U$ENC@4](https://user-images.githubusercontent.com/115143930/195825758-a59fd1aa-e936-4e5e-ad40-20e04a7b87fa.png)
![`PW I_R{{EN7{V$OJG Q C2](https://user-images.githubusercontent.com/115143930/195825819-d7f9c745-084f-4ed5-9f13-
![2$EO7G~K9}W(XPC3U8Y0~{T](https://user-images.githubusercontent.com/115143930/195825911-c368450b-e8e0-4ca1-b4bc-5fd3a6cb30dd.png)
0678025e86e6.png)
![MJ`_8V}G8YI6{U}N TJN`XT](https://user-images.githubusercontent.com/115143930/195826139-9ccf0401-c34e-4953-bd2a-ee714ef37120.png)
![%J)SI74GZ``_%(4)3AXO)FC](https://user-images.githubusercontent.com/115143930/195826203-2dfc6d7e-234e-4b6f-a361-f971942f9d70.png)
![NBZ3QLIHES(2 }RZE02A% 8](https://user-images.githubusercontent.com/115143930/195826250-95240120-0ea9-41c3-96fc-4a82e77c2a52.png)
#

## config.json 配置
```
#{
    "bangumi_dir": "F:\\电影视频",
    "temp_dir": "F:\\电影视频\\temp",
    "classify_bangumi": true,
    "classify_season": false,
    "check_frequency": 10,
    "download_resolution": "1080",
    "lock_resolution": false,
    "only_use_vip": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_bangumi_name_to_video_meta": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.37",
    "use_proxy": false,
    "proxy": "http://user:passwd@example.com:1000",
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "msg_argument_name": "message",
        "message_suffix": "追加的資訊",
        "query": [
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
        ]
    },
    "telebot_notify": false,
    "telebot_token": "",
    "telebot_use_chat_id": false,
    "telebot_chat_id": "",
    "discord_notify": false,
    "discord_token": "",
    "plex_refresh": false,
    "plex_url": "",
    "plex_token": "",
    "plex_section": "",
    "plex_naming": false,
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": false,
    "danmu": false,
    "danmu_ban_words": [],
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "mobile_ads_time": 3,
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 16.2,
    "database_version": 2.0
}#
```

## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```

**最好
[2022-10-14.log](https://github.com/miyouzi/aniGamerPlus/files/9785235/2022-10-14.log)
上傳 log 檔案**

**Comment by kongrui05** [comment]
应该是网站更新了 重置cookie也报错
`
2022-10-13 23:47:11 收到cookie重置響應: sn=31637	
2022-10-13 23:47:13 下載異常: sn=31637	發生未知異常: 'BAHARUNE'
2022-10-13 23:47:13 下載異常: sn=31637	異常詳情:
Traceback (most recent call last):
  File "D:\Soft\aniGamerPlus\aniGamerPlus.py", line 377, in __download_only
    anime.download(dl_resolution, dl_save_dir, realtime_show_file_size=realtime_show_file_size, classify=classify)
  File "D:\Soft\aniGamerPlus\Anime.py", line 867, in download
    self.__get_m3u8_dict()  # 获取 m3u8 列表
  File "D:\Soft\aniGamerPlus\Anime.py", line 452, in __get_m3u8_dict
    get_device_id()
  File "D:\Soft\aniGamerPlus\Anime.py", line 353, in get_device_id
    f = self.__request(req)
  File "D:\Soft\aniGamerPlus\Anime.py", line 303, in __request
    old_BAHARUNE = self._cookies['BAHARUNE']
KeyError: 'BAHARUNE'

`

**Comment by miyouzi** [comment]
目前游客（非登录）只有 360P 了

Cookie 报错问题，检查一下是不是 Cookie 抓错了，Cookie 中应该有 `BAHARUNE` 关键字

**Comment by RyanL-29** [comment]
另外提醒一下, 已登錄狀態, 請不要大量下載, 避免帳戶被封鎖.
