### ISSUE TITLE
更新到V24.2 版本后下载提示错误,23.1版本正常下载

### ISSUE THREAD

**Issue by testabcc** [miyouzi/aniGamerPlus#211]
## 問題描述
更新到V24.2 版本后下载提示错误,23.1版本正常下载

## 錯誤截圖
![image](https://user-images.githubusercontent.com/115860651/195973241-0a09aa41-331a-4762-b9a5-827138d130a4.png)

## config.json 配置
```
{
    "bangumi_dir": "",
    "temp_dir": "",
    "classify_bangumi": false,
    "classify_season": false,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": false,
    "only_use_vip": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36",
    "use_proxy": false,
    "proxy": "http://user:passwd@example.com:1000",
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "msg_argument_name": "message",
        "message_suffix": "追加的資訊",
        "query": [
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
        ]
    },
    "telebot_notify": false,
    "telebot_token": "",
    "telebot_use_chat_id": false,
    "telebot_chat_id": "",
    "discord_notify": false,
    "discord_token": "",
    "plex_refresh": false,
    "plex_url": "",
    "plex_token": "",
    "plex_section": "",
    "plex_naming": false,
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": false,
    "danmu": false,
    "danmu_ban_words": [],
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "mobile_ads_time": 3,
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 17.0,
    "database_version": 2.0
}
```

## sn_list.txt 配置
```
这个应该是没有,没找到
```

LOG日志

2022-10-15 12:25:46 檢查更新 檢查更新成功
2022-10-15 12:25:46 自動模式啓動aniGamerPlus 當前aniGamerPlus版本: v24.2 
2022-10-15 12:25:46 工作目錄: C:\bahav24.2 
2022-10-15 12:25:48 Web控制面板已啓動 訪問地址: http://127.0.0.1:5000
2022-10-15 12:25:48 開始更新 
2022-10-15 12:25:48 讀取cookie 未發現cookie檔案
2022-10-15 12:25:48 更新資訊 本次更新添加了 0 個新任務, 目前列隊中共有 0 個任務
2022-10-15 12:25:48 更新终了 
2022-10-15 12:26:21 Dashboard 通過 Web 控制臺更新了 config.json
2022-10-15 12:26:40 Dashboard 通過 Web 控制臺下達了手動任務
2022-10-15 12:26:40 解析模式: sn=31594	Web解析
2022-10-15 12:26:50 任務狀態: sn=31594	ERROR: 请求失败！except：
HTTPSConnectionPool(host='ani.gamer.com.tw', port=443): Max retries exceeded with url: /animeVideo.php?sn=31594 (Caused by ProxyError('Cannot connect to proxy.', timeout('The handshake operation timed out')))
3s后重试(最多重试3次)
2022-10-15 12:27:03 任務狀態: sn=31594	ERROR: 请求失败！except：
HTTPSConnectionPool(host='ani.gamer.com.tw', port=443): Max retries exceeded with url: /animeVideo.php?sn=31594 (Caused by ProxyError('Cannot connect to proxy.', timeout('The handshake operation timed out')))
3s后重试(最多重试3次)
2022-10-15 12:27:16 任務狀態: sn=31594	ERROR: 请求失败！except：
HTTPSConnectionPool(host='ani.gamer.com.tw', port=443): Max retries exceeded with url: /animeVideo.php?sn=31594 (Caused by ProxyError('Cannot connect to proxy.', timeout('The handshake operation timed out')))
3s后重试(最多重试3次)
2022-10-15 12:27:29 抓取失敗: sn=31594	影片信息抓取失敗!

**Comment by asd01234** [comment]
终于有和我一样遭遇人出现了！

**Comment by miyouzi** [comment]
使用代理的话建议用程序自身的设置

**Comment by testabcc** [comment]
> 使用代理的话建议用程序自身的设置
在软件上没有配置使用代理,一直都是本地计算机用VPN软件
而且这程序我用了一看多了,也更新了挺多版本的
目前就发现这个版本有这个错误,应该不会是我配置错误

**Comment by testabcc** [comment]
> 使用代理的话建议用程序自身的设置

在软件上没有配置使用代理,一直都是本地计算机用VPN软件
而且这程序我用了一看多了,也更新了挺多版本的
目前就发现这个版本有这个错误,应该不会是我配置错误

**Comment by testabcc** [comment]
我是使用的windows的EXE版本

**Comment by testabcc** [comment]
改 本地VPN  软件的设置后解决了

**Comment by asd01234** [comment]
@testabcc 
卧槽，可以说说是怎么修改设置吗？软件是SSR？还是ClashR？我也是正为了这个问题犯愁呢！

**Comment by testabcc** [comment]
软件是 QuickQ 模式设置成专家(WIN7)以上就行
