### ISSUE TITLE
16.1 檔名有多餘的文字造成無法搬移。

### ISSUE THREAD

**Issue by a0960211197** [miyouzi/aniGamerPlus#22]
檔名後面有多merging的文字造成找不到檔案搬移。

<img width="1920" alt="截圖 2019-11-03 下午4 18 00" src="https://user-images.githubusercontent.com/47473831/68082326-2a30e200-fe56-11e9-991f-0f66cd47270c.png">

[config.json.txt](https://github.com/miyouzi/aniGamerPlus/files/3801360/config.json.txt)
[2019-11-03.log](https://github.com/miyouzi/aniGamerPlus/files/3801361/2019-11-03.log)

**Comment by miyouzi** [comment]
v16.2 已更新。

**Comment by miyouzi** [comment]
可以提供 ```config.json``` 和 log 檔案嗎?

**Comment by a0960211197** [comment]
我有附上了。

**Comment by miyouzi** [comment]
已確認為 bug，正在修復

**Comment by a0960211197** [comment]
目前正常了！
感謝！
