### ISSUE TITLE
这种命令行形式的工具是不是没法一键更新？

### ISSUE THREAD

**Issue by YFTX2015** [miyouzi/aniGamerPlus#221]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#

## 錯誤截圖
#在這裏附上錯誤的窗口截圖#

## config.json 配置
```
#將你的config.json内容複製到這裏#
```

## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```

**最好上傳 log 檔案**

**Comment by miyouzi** [comment]
你指的是使用命令行模式？

更新指的是弹幕还是番剧更新？

**Comment by YFTX2015** [comment]
就是指的aniGamerPlus这个程序啊。

**Comment by miyouzi** [comment]
程序本身只会检查是否有新版本，不会自动更新，更新程序需要手动

**Comment by YFTX2015** [comment]
一般只需要把旧版的config.json，sn-list跟cookie移到新版文件夹里面就行了吧，该替换的就替换。

**Comment by miyouzi** [comment]
> 一般只需要把旧版的config.json，sn-list跟cookie移到新版文件夹里面就行了吧，该替换的就替换。

是的

**Comment by YFTX2015** [comment]
好
