### ISSUE TITLE
Docker 更新

### ISSUE THREAD

**Issue by MCchiMo** [miyouzi/aniGamerPlus#222]
Docker 裡的 tonypepe/anigamerplus 是不是只有到24.1版本而已  這樣沒辦法使用冷卻效果

**Comment by TonyPepeBear** [comment]
最近 build 會失敗，有人能協助解決一下嗎？

畢業將近..時間不是很多

https://github.com/TonyPepeBear/aniGamerPlus/actions/runs/3491421137/jobs/5844032851


<img width="1065" alt="CleanShot 2022-11-18 at 03 41 15@2x" src="https://user-images.githubusercontent.com/41405045/202543429-64012df0-14b0-43ef-913a-92468ae6dc9b.png">

**Comment by cyrus0880** [comment]
> 最近 build 會失敗，有人能協助解決一下嗎？
> 
> 畢業將近..時間不是很多
> 
> https://github.com/TonyPepeBear/aniGamerPlus/actions/runs/3491421137/jobs/5844032851
> 
> <img alt="CleanShot 2022-11-18 at 03 41 15@2x" width="1065" src="https://user-images.githubusercontent.com/41405045/202543429-64012df0-14b0-43ef-913a-92468ae6dc9b.png">

你的套件管理requirements.txt 有部分套件的版本有問題

termcolor
flask
requests
chardet
gevent
flask_basicauth
flask_sockets
bs4
gevent_websocket
pysocks
pyhttpx
lxml

我這樣改後就能build了

**Comment by JuenTingShie** [comment]
Hi, I can confirm that changing 

https://github.com/miyouzi/aniGamerPlus/blob/a2387121a47a2d83e268875c829a194606564f9a/requirements.txt#L5

gevent from 21.12.0 to 22.08.0

will successful build on Github Action, you can check by my fork's commit

https://github.com/JuenTingShie/aniGamerPlus/commit/4b8b7e11fd9ee759c085550709fc571428c3ba24

this issue I had already mention in #214 , please have a check for more details. Thank you.
