### ISSUE TITLE
無法下載：本項目依賴於ffmpeg, 但ffmpeg未找到

### ISSUE THREAD

**Issue by dj09032112** [miyouzi/aniGamerPlus#225]
## 問題描述
如題，系統顯示本項目依賴於ffmpeg, 但ffmpeg未找到。
請問該如何解決呢？

## 錯誤截圖
![image](https://user-images.githubusercontent.com/115106580/204004485-1e243dcc-82a0-4850-bd70-db9ae6ac1bfb.png)

## config.json 配置
```
{
    "bangumi_dir": "",
    "temp_dir": "",
    "classify_bangumi": true,
    "classify_season": false,
    "check_frequency": 5,
    "download_cd": 60,
    "parse_sn_cd": 5,
    "download_resolution": "1080",
    "lock_resolution": false,
    "only_use_vip": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36",
    "use_proxy": false,
    "proxy": "http://user:passwd@example.com:1000",
    "no_proxy_akamai": false,
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "msg_argument_name": "message",
        "message_suffix": "追加的資訊",
        "query": [
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
        ]
    },
    "telebot_notify": false,
    "telebot_token": "",
    "telebot_use_chat_id": false,
    "telebot_chat_id": "",
    "discord_notify": false,
    "discord_token": "",
    "plex_refresh": false,
    "plex_url": "",
    "plex_token": "",
    "plex_section": "",
    "plex_naming": false,
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": false,
    "danmu": false,
    "danmu_ban_words": [],
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "mobile_ads_time": 25,
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 17.2,
    "database_version": 2.0
}
```

## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```

**最好上傳 log 檔案**
2022-11-25 22:15:49 檢查更新 檢查更新成功
2022-11-25 22:15:49 自動模式啓動aniGamerPlus 當前aniGamerPlus版本: v24.5 
2022-11-25 22:15:49 工作目錄: D:\Software\aniGamerPlus_v24.5 
2022-11-25 22:15:54 Web控制面板已啓動 訪問地址: http://127.0.0.1:5000
2022-11-25 22:15:54 開始更新 
2022-11-25 22:15:54 讀取cookie 發現cookie檔案
2022-11-25 22:15:54 讀取cookie 已讀取cookie
2022-11-25 22:15:54 更新資訊 本次更新添加了 0 個新任務, 目前列隊中共有 0 個任務
2022-11-25 22:15:54 更新终了 
2022-11-25 22:16:07 Dashboard 通過 Web 控制臺下達了手動任務
2022-11-25 22:16:07 解析模式: sn=31587	Web解析
2022-11-25 22:16:08 收到新cookie: sn=31587	
2022-11-25 22:16:08 用戶cookie刷新  : sn=31587	
2022-11-25 22:16:08 收到新cookie: sn=31587	
2022-11-25 22:16:08 用戶cookie刷新 ANIME_SIGN : sn=31587	
2022-11-25 22:16:08 開始下載: sn=31587	《路人超能 100 第三季 [1]》 識別到VIP賬戶, 立即下載
2022-11-25 22:16:08 本項目依賴於ffmpeg, 但ffmpeg未找到 
2022-11-25 22:16:08 下載異常: sn=31587	發生未知異常: 
2022-11-25 22:16:08 下載異常: sn=31587	異常詳情:
Traceback (most recent call last):
  File "aniGamerPlus.py", line 395, in __download_only
  File "Anime.py", line 911, in download
FileNotFoundError

2022-11-25 22:16:08 任務失敗: sn=31587	title=路人超能 100 第三季 [1] 10s后自動重啓,最多重試三次

**Comment by miyouzi** [comment]
https://github.com/miyouzi/aniGamerPlus#%E6%B3%A8%E6%84%8Fwarning

![image](https://user-images.githubusercontent.com/24269465/204012302-0c9685f4-b7a7-448e-a7a0-68cc320167ae.png)

**Comment by KuoHsiangYu2** [comment]
看樣子你是用 Windows作業系統，你要先去下載 ffmpeg.exe執行檔案。然後把這個檔案放置在專案根目錄裡面。
或者是這個 ffmpeg.exe檔案所在的資料夾路徑 要放置在系統環境變數裡面。

舉例來說我的 ffmpeg.exe檔案 在這個資料夾。
![圖片](https://user-images.githubusercontent.com/60570519/204117310-7db6ab4f-f1c8-4b35-88d5-d87438967ce8.png)

然後我要開啟 設定 -> 關於 -> 進階系統設定 -> 系統內容 -> 環境變數(N)... -> 系統變數 然後勾選Path -> 編輯Path 裡面的值，接著添加 ffmpeg.exe檔案所在位置的資料夾路徑在內。
![圖片](https://user-images.githubusercontent.com/60570519/204117370-9be6e9e3-e317-40c2-9267-765be92321d7.png)

做完這些操作，您就能繼續使用 aniGamerPlus專案 下載影片。

**Comment by dj09032112** [comment]
感謝樓上兩位，裝了新版本但忘記把ffmpeg放進去，是我的疏忽，非常感謝兩位
