### ISSUE TITLE
下載格式

### ISSUE THREAD

**Issue by Hiura-Souji** [miyouzi/aniGamerPlus#23]
## 請問能新增供選擇下載副檔名嗎？
#這裡預設為*.MP4，請問能開放選擇其他附檔名嗎？例如*.TS

## 目前提供的UA網站進不去
#替代：[http://service.spiritsoft.cn/ua.html](http://service.spiritsoft.cn/ua.html)

## 無法自動從LIST中下載
#已經依照格式將要下載的SN填入，可是一直沒有下載...

感謝~

## 錯誤截圖
當前aniGamerPlus版本: v16.2

2019-11-04 03:29:50 開始更新
2019-11-04 03:29:50 更新資訊 本次更新添加了 0 個新任務, 目前列隊中共有 0 個任務
2019-11-04 03:29:50 更新终了

## config.json 配置
```
{
    "bangumi_dir": "D:\\MyDownload",
    "temp_dir": "",
    "classify_bangumi": true,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": true,
    "default_download_mode": "all",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "segment_max_retry": 8,
    "multi_downloading_segment": 3,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36",
    "use_proxy": false,
    "proxies": {
        "1": "socks5://127.0.0.1:1080",
        "2": "http://user:passwd@example.com:1000"
    },
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "host": "127.0.0.1",
        "port": "5700",
        "SSL": false,
        "api": "send_group_msg",
        "query": {
            "group_id": "123456789"
        }
    },
    "faststart_movflags": false,
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 9.0,
    "database_version": 2.0
}
```

## sn_list.txt 配置
```
@aniGamerPlus16.2
10810 all #庫洛魔法使 第二季
9357 all #庫洛魔法使 透明牌篇
```

**最好上傳 log 檔案**
2019-11-04 03:31:07 檢查更新 檢查更新成功
2019-11-04 03:31:07 自動模式啓動aniGamerPlus 當前aniGamerPlus版本: v16.2 
2019-11-04 03:31:07 工作目錄: D:\Admin\Desktop\aniGamerPlus_v16.2_windows_64bit 
2019-11-04 03:31:07 開始更新 
2019-11-04 03:31:07 讀取cookie 發現cookie檔案
2019-11-04 03:31:07 讀取cookie 已讀取cookie
2019-11-04 03:31:07 更新資訊 本次更新添加了 0 個新任務, 目前列隊中共有 0 個任務
2019-11-04 03:31:07 更新终了

**Comment by miyouzi** [comment]
需要更改副檔名是在什麽情境下需要呢？

你的 ```sn_list.txt``` 的内容我試了下沒有問題，是不是檔名不正確呢？能否熒幕截取一下 aniGamerPlus 所在的資料夾呢？

**Comment by Hiura-Souji** [comment]
> 需要更改副檔名是在什麽情境下需要呢？
> 
> 你的 `sn_list.txt` 的内容我試了下沒有問題，是不是檔名不正確呢？能否熒幕截取一下 aniGamerPlus 所在的資料夾呢？

真的是檔名的問題呢><
我是使用預設檔名沒有改到XD
sn_list-sample.txt >> sn_list.txt  就OK了

更改附檔名主要是因為我習慣儲存.ts檔
想在自動或是命令列使用
想說可否在config加個開關可以選擇預設或是自定義XD

感謝您~

**Comment by miyouzi** [comment]
aniGamerPlus 對影片的處理只是合并封裝，並未重編碼，mp4 格式用的比較多所以選擇 mp4

雖然個人覺得改封裝沒什麽差別，但是既然你有需求的話，我找個時間嘗試加上吧。

**Comment by Hiura-Souji** [comment]
> aniGamerPlus 對影片的處理只是合并封裝，並未重編碼，mp4 格式用的比較多所以選擇 mp4
> 
> 雖然個人覺得改封裝沒什麽差別，但是既然你有需求的話，我找個時間嘗試加上吧。

了解了
感謝您~

**Comment by miyouzi** [comment]
[v17](https://github.com/miyouzi/aniGamerPlus/releases/tag/v17) 已更新

**Comment by Hiura-Souji** [comment]
> [v17](https://github.com/miyouzi/aniGamerPlus/releases/tag/v17) 已更新

正常使用中
感謝您~
