### ISSUE TITLE
無法正常下載

### ISSUE THREAD

**Issue by silviayc** [miyouzi/aniGamerPlus#232]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#
HTTPSConnectionPool(host='bahamut.akamaized.net', port=443): Read timed out.

## 錯誤截圖
#在這裏附上錯誤的窗口截圖#
![image](https://user-images.githubusercontent.com/23229898/214412334-f661e2ed-7214-4014-816b-e463677fd780.png)

## config.json 配置
```
#將你的config.json内容複製到這裏#
```
[config.json.txt](https://github.com/miyouzi/aniGamerPlus/files/10493925/config.json.txt)

## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```
#2023-01
32344 all # 魔王學院的不適任者～史上最強的魔王始祖，轉生就讀子孫們的學校～第二季
32429 all # 最強陰陽師的異世界轉生記
32340 all # 關於我在無意間被隔壁的天使變成廢柴這件事
32337 all # 異世界悠閒農家
32379 all # 冰劍的魔術師將要統一世界
32346 all # 虛構推理 第二季
32328 all # 轉生公主與天才千金的魔法革命
32345 all # 眾神眷顧的男人 2
32368 all # 擁有超常技能的異世界流浪美食家
32327 all # 不相信人類的冒險者們好像要去拯救世界
32372 all # 怕痛的我，把防禦力點滿就對了 第二季
32428 all # 被解僱的暗黑士兵（30多歲）開始了慢生活的第二人生

**最好上傳 log 檔案**
[err.log.txt](https://github.com/miyouzi/aniGamerPlus/files/10493934/err.log.txt)

**Comment by miyouzi** [comment]
網頁是否能正常觀看？

**Comment by silviayc** [comment]
可以

**Comment by silviayc** [comment]
應該是 dosker 內 DNS 解析異常的問題
目前排除了

**Comment by Kevin-Liou** [comment]
有類似的問題...

![image](https://user-images.githubusercontent.com/30136362/214809651-589171f1-1a25-4f08-b151-1ee51fcde581.png)

**Comment by miyouzi** [comment]
@TonyPepeBear Docker問題有空的話麻煩幫忙看看，看是不是需要在 Dockerfile 裏添加設定 DNS

**Comment by TonyPepeBear** [comment]
我無法重現問題，我在容器內嘗試 `curl https://bahamut.akamaized.net/` 也沒遇到問題

**Comment by miyouzi** [comment]
請嘗試 https://github.com/miyouzi/aniGamerPlus/issues/228#issuecomment-1416767116
