### ISSUE TITLE
cookies 無法自動更新，需手動重新取得

### ISSUE THREAD

**Issue by Hulen** [miyouzi/aniGamerPlus#233]
## 問題描述
cookies 無法自動更新，需手動重新取得。

不確定是否需要每日進行更新，但目前遇到確實是換日後就會需要重新手動取得一次。

**最好上傳 log 檔案**
[2023-02-12-01.log](https://github.com/miyouzi/aniGamerPlus/files/10715304/2023-02-12-01.log)

**Comment by miyouzi** [comment]
`config.json` 也提供一下，配置的UA有沒有做修改？

**Comment by Hulen** [comment]
先附上 config.json 檔案

Web 解析可能要等過兩天測試才能確定是不是有一樣的問題

[config.json.txt](https://github.com/miyouzi/aniGamerPlus/files/10715576/config.json.txt)

**Comment by Hulen** [comment]
目前疑似修改成 wrb 解析後就可以正常刷新 cookies 了解析
