### ISSUE TITLE
只能下載360p

### ISSUE THREAD

**Issue by ne02eon** [miyouzi/aniGamerPlus#235]
我的賬號有VIP, 但是還是只能下載360p 並顯示"指定清晰度不存在, 選取最近可用清晰度"
亦無法正確顯示VIP賬戶信息: "由於不是VIP賬戶, 正在等待25s廣告時間

![image](https://user-images.githubusercontent.com/127636199/224517345-3b48d3ef-8c72-4674-967d-72cb0141d375.png)

config.json 沒有動過, sn_list 為空白

** log 檔案**
[2023-03-12.log](https://github.com/miyouzi/aniGamerPlus/files/10949732/2023-03-12.log)

**Comment by miyouzi** [comment]
先升級到最新版本再測試一下

**Comment by ne02eon** [comment]
> 先升級到最新版本再測試一下

更新成最新版本之後問題解決了, 感謝
