### ISSUE TITLE
遇到CODE=1007 問題 

### ISSUE THREAD

**Issue by zero20089** [miyouzi/aniGamerPlus#238]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#
最近遇到紅色錯誤 不知道怎麼回事 關掉重開就正常

## 錯誤截圖
#在這裏附上錯誤的窗口截圖#
![image](https://user-images.githubusercontent.com/49590648/232259152-bc7d3e54-5af1-4e2d-ae69-422bf777911b.png)

## config.json 配置
```
#將你的config.json内容複製到這裏#
```
{
    "bangumi_dir": "",
    "temp_dir": "",
    "classify_bangumi": true,
    "classify_season": false,
    "check_frequency": 5,
    "download_cd": 400,
    "parse_sn_cd": 0,
    "download_resolution": "1080",
    "lock_resolution": true,
    "only_use_vip": false,
    "default_download_mode": "all",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
    "use_proxy": false,
    "proxy": "http://user:passwd@example.com:1000",
    "no_proxy_akamai": false,
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "msg_argument_name": "message",
        "message_suffix": "追加的資訊",
        "query": [
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
        ]
    },
    "telebot_notify": false,
    "telebot_token": "",
    "telebot_use_chat_id": false,
    "telebot_chat_id": "",
    "discord_notify": false,
    "discord_token": "",
    "plex_refresh": false,
    "plex_url": "",
    "plex_token": "",
    "plex_section": "",
    "plex_naming": false,
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": true,
    "danmu": false,
    "danmu_ban_words": [],
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "mobile_ads_time": 25,
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 17.2,
    "database_version": 2.0
}

## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```

**最好上傳 log 檔案**
[2023-04-16.log](https://github.com/miyouzi/aniGamerPlus/files/11240927/2023-04-16.log)

**Comment by miyouzi** [comment]
關閉“模擬手機端解析”

**Comment by zero20089** [comment]
有關閉模擬手機解析~ 有時候會顯示錯誤

**Comment by zero20089** [comment]
之前關掉手機模擬解析之後
看機率隨機會出現

2023-04-04 08:54:08 解析模式: sn=33525	Web解析
2023-04-04 08:54:08 收到新cookie: sn=33525	
2023-04-04 08:54:08 用戶cookie刷新  : sn=33525	
2023-04-04 08:54:09 ERROR: 該 sn 下真的有動畫？: sn=33525	
2023-04-04 08:54:09 抓取失敗: sn=33525	抓取影片信息時發生未知錯誤: 1
2023-04-04 08:54:09 抓取異常: sn=33525	異常詳情:
Traceback (most recent call last):
  File "Anime.py", line 155, in __get_title
AttributeError: 'NoneType' object has no attribute 'h1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aniGamerPlus.py", line 55, in build_anime
  File "Anime.py", line 74, in __init__
  File "Anime.py", line 160, in __get_title
SystemExit: 1

開手機模擬解析 還是會顯示CODE=1007
關閉程式重開恢復正常..

**Comment by miyouzi** [comment]
下載太多被限制了吧，調整一下“下載冷卻時間(秒)”，“SN解析冷卻時間(秒)”，“更新間隔”，“最大并發下載數”

**Comment by zero20089** [comment]
我找到原因   COOKIE 太久沒更新... 造成會顯示錯誤 直接跑去開無痕模式F12 複製貼上
測試之後不再錯誤問題
剛剛注意到老舊COOKIE  會顯示未知錯誤
然後把COOKIE更新就正常了

沒有在下載太多 我帳號正常 
下載冷卻時間 我是設定 400秒

**Comment by bossgder** [comment]
我也是在 關掉手機模擬解析之後，出現 ERROR: 該 sn 下真的有動畫？
也是在更新 cookie 之後就正常。
目前使用的版本是 24.3
