### ISSUE TITLE
影片無法下

### ISSUE THREAD

**Issue by w0853** [miyouzi/aniGamerPlus#24]
## 問題描述
超過1hr以上的影片是不是就無法下

## 錯誤截圖
[(https://imgur.com/sR3zAOc)]

## config.json 配置
```
#將你的config.json内容複製到這裏#
```
{
    "bangumi_dir": "",
    "temp_dir": "",
    "classify_bangumi": true,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36",
    "use_proxy": false,
    "proxies": {
        "1": "socks5://127.0.0.1:1080",
        "2": "http://user:passwd@example.com:1000"
    },
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "host": "127.0.0.1",
        "port": "5700",
        "SSL": false,
        "api": "send_group_msg",
        "query": {
            "group_id": "123456789"
        }
    },
    "faststart_movflags": false,
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 10.0,
    "database_version": 2.0
}

## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```
9242 all # 刀劍神域 劇場版 序列爭戰 [電影]

**最好上傳 log 檔案**
[2019-11-26.log](https://github.com/miyouzi/aniGamerPlus/files/3887666/2019-11-26.log)

**Comment by miyouzi** [comment]
初步排查可能是 pyinstaller 編譯32位元可執行檔出現的問題，正在嘗試處理。

你可以嘗試使用64位元的可執行檔或者源碼運行。

**Comment by w0853** [comment]
64成功,感謝
