### ISSUE TITLE
docker內cookies無法自動更新

### ISSUE THREAD

**Issue by SakurajimaMai-1202** [miyouzi/aniGamerPlus#242]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#
docker內cookies無法自動更新
## 錯誤截圖

#在這裏附上錯誤的窗口截圖#
![image](https://user-images.githubusercontent.com/56517823/235066868-d665a833-2ad2-4d77-8e96-dbbba0481aa6.png)

## config.json 配置
```
#將你的config.json内容複製到這裏#
```
{
    "bangumi_dir": "",
    "temp_dir": "",
    "classify_bangumi": true,
    "check_frequency": 180,
    "download_cd": 60,
    "parse_sn_cd": 3,
    "download_resolution": "1080",
    "lock_resolution": false,
    "only_use_vip": false,
    "default_download_mode": "largest-sn",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": false,
    "customized_video_filename_prefix": "",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 2,
    "ua": "rawUa: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.0.0",
    "use_proxy": false,
    "proxy": "http://user:passwd@example.com:1000",
    "no_proxy_akamai": false,
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "msg_argument_name": "message",
        "message_suffix": "追加的資訊",
        "query": [
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
        ]
    },
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": false,
    "danmu": false,
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "mobile_ads_time": 25,
    "use_dashboard": true,
    "dashboard": {
        "host": "0.0.0.0",
        "port": 500,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 17.2,
    "database_version": 2.0,
    "classify_season": false,
    "plex_naming": true,
    "telebot_notify": false,
    "telebot_token": "",
    "telebot_use_chat_id": false,
    "telebot_chat_id": "",
    "discord_notify": true,
    "discord_token": ,
    "plex_refresh": false,
    "plex_url": "",
    "plex_token": "",
    "plex_section": "",
    "danmu_ban_words": []
}
## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```
@2023 4月
33249 all #和山田談場 Lv999 的戀愛 
33255 all #帶著智慧型手機闖蕩異世界。2 
33283 all #絆之 Allele
33258 all #在異世界獲得超強能力的我，在現實世界照樣無敵～等級提升改變人生命運～
33253 all #為美好的世界線上爆焰
33312 all #我推的孩子
33250 all #我內心糟糕的念頭
33307 all #屍體如山的死亡遊戲
**最好上傳 log 檔案**

[anigamerplus.log](https://github.com/miyouzi/aniGamerPlus/files/11350502/anigamerplus.log)

**Comment by miyouzi** [comment]
docker啓動參數貼一下

**Comment by SakurajimaMai-1202** [comment]
是指這個執行指令嗎? 因為我是用群暉的Docker 然後用的 Image是這個https://registry.hub.docker.com/r/sating/anigamerplus/
不過我也有改用過底下文檔tonypepe的 Image 也是一樣狀況

![image](https://github.com/miyouzi/aniGamerPlus/assets/56517823/3017c41d-3738-44b7-958e-5e0e57ca4bbd)

**Comment by miyouzi** [comment]
`cookie.txt` 你是做了映射嗎？

Docker問題咨詢一下 @TonyPepeBear

**Comment by JuenTingShie** [comment]
> 是指這個執行指令嗎? 因為我是用群暉的Docker 然後用的 Image是這個https://registry.hub.docker.com/r/sating/anigamerplus/ 不過我也有改用過底下文檔tonypepe的 Image 也是一樣狀況
> 
> ![image](https://user-images.githubusercontent.com/56517823/239678911-3017c41d-3738-44b7-958e-5e0e57ca4bbd.png)

你使用的是我自行 build 的 armhf 版本 docker image，他並不是原作者維護的版本。
目前已經重新同步最新的 commit，等待 CI 完成 build 之後再重試看看。

關於 cookit.txt 映射，請確定在執行 docker 時有將 cookie.txt 對應到 docker image 內的對應路徑，請參考 [下載官方 Image](https://github.com/miyouzi/aniGamerPlus#%E4%B8%8B%E8%BC%89%E5%AE%98%E6%96%B9-image)。

**Comment by SakurajimaMai-1202** [comment]
有的 cookie.txt 有做映射 
![image](https://github.com/miyouzi/aniGamerPlus/assets/56517823/40190430-cbdc-438e-abd6-f37c72e3e9b7)

**Comment by SakurajimaMai-1202** [comment]
目前看起來狀況是一樣🤔不知道問題出在哪?
![image](https://github.com/miyouzi/aniGamerPlus/assets/56517823/e628c2c5-1b40-41d9-a762-d95258071a9b)

**Comment by SakurajimaMai-1202** [comment]
目前看起來是解決了 不知道為甚麼 config裡面的UA 的後面多了一個"rawua" 後來刪除後 看了一下日誌就正常更新了
![image](https://github.com/miyouzi/aniGamerPlus/assets/56517823/d3ee674f-248a-4ee7-92a5-d5321d0023d8)
