### ISSUE TITLE
code=1007 message: 裝置驗證異常

### ISSUE THREAD

**Issue by ntutcsie01** [miyouzi/aniGamerPlus#253]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#
第一次開啟aniGamerPlus.exe，解析完SN要進行下載任務都會出現的錯誤
code=1007 message: 裝置驗證異常
下載異常 發生未知的錯誤
但關掉再重新打開就可以下載了

## 錯誤截圖
#在這裏附上錯誤的窗口截圖#
![Screenshot 2023-07-17 151935](https://github.com/miyouzi/aniGamerPlus/assets/101080595/7c48ab21-43be-43a7-950f-ebab20d12129)

## config.json 配置
```
#將你的config.json内容複製到這裏#
```
{
    "bangumi_dir": "C:\\Users\\LEO\\Videos\\animeplus\\anime",
    "temp_dir": "",
    "classify_bangumi": true,
    "classify_season": false,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": false,
    "only_use_vip": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 5,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "use_proxy": false,
    "proxy": "http://user:passwd@example.com:1000",
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "msg_argument_name": "message",
        "message_suffix": "追加的資訊",
        "query": [
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
        ]
    },
    "telebot_notify": false,
    "telebot_token": "",
    "telebot_use_chat_id": false,
    "telebot_chat_id": "",
    "discord_notify": false,
    "discord_token": "",
    "plex_refresh": false,
    "plex_url": "",
    "plex_token": "",
    "plex_section": "",
    "plex_naming": false,
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": true,
    "danmu": true,
    "danmu_ban_words": [
        "胖虎"
    ],
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "mobile_ads_time": 30,
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 17.2,
    "database_version": 2.0,
    "no_proxy_akamai": false,
    "download_cd": 60,
    "parse_sn_cd": 5
}

## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```
33258 all # 在異世界獲得超強能力的我，在現實世界照樣無敵～等級提升改變人生命運～ 
33252 all # 熊熊勇闖異世界 PUNCH！
33255 all # 帶著智慧型手機闖蕩異世界。
33251 all # 轉生貴族的異世界冒險錄～不知自重的眾神使徒
33257 all # 我家的英雄
33253 all # 為美好的世界獻上爆焰！
33318 all # Dr. STONE 新石紀 第三季
33355 all # 第二次被異世界召喚
33448 all # 無神世界的神明活動 
33349 all # 鬼滅之刃 刀匠村篇
33330 all # 肌肉魔法使
33275 all # 無意間變成狗，被喜歡的女生撿回家。 [年齡限制版] [2] [特別篇]
33370 all # 勇者死了！
33307 all # 屍體如山的死亡遊戲
33521 all # 我推的孩子

34092 all # 無職轉生～到了異世界就拿出真本事 第二季
34090 all # 殭屍 100～在成為殭屍前要做的 100 件事～
34125 all # 政宗君的復仇 R
34123 all # LV1 魔王與獨居廢勇者
34133 all # 我喜歡的女孩忘記戴眼鏡
34138 all # 不死少女的謀殺鬧劇
34155 all # 神劍闖江湖 ―明治劍客浪漫譚―
34158 all # 聖者無雙～上班族的異世界生存之道～
34198 all # 妙廟美少女
34186 all # 雖然等級只有 1 級但固有技能是最強的 
34189 all # 謊言遊戲

**最好上傳 log 檔案**
[2023-07-17.log](https://github.com/miyouzi/aniGamerPlus/files/12066874/2023-07-17.log)

**Comment by RyanL-29** [comment]
請嘗試把 use_mobile_api 改為 false

**Comment by miyouzi** [comment]
#238
