### ISSUE TITLE
抓取失敗: sn=14826  抓取影片信息時發生未知錯誤: 'BAHARUNE'

### ISSUE THREAD

**Issue by Bill920405** [miyouzi/aniGamerPlus#255]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#
抓取影片信息時發生未知錯誤: 'BAHARUNE'
## 錯誤截圖
#在這裏附上錯誤的窗口截圖#
![image](https://github.com/miyouzi/aniGamerPlus/assets/131909614/365c7ca0-7f66-4f16-8e2a-bcbafc97cd7d)

## config.json 配置
```
#將你的config.json内容複製到這裏#
```{
    "bangumi_dir": "",
    "temp_dir": "",
    "classify_bangumi": true,
    "classify_season": false,
    "check_frequency": 5,
    "download_cd": 60,
    "parse_sn_cd": 5,
    "download_resolution": "1080",
    "lock_resolution": false,
    "only_use_vip": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
    "use_proxy": false,
    "proxy": "http://user:passwd@example.com:1000",
    "no_proxy_akamai": false,
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "msg_argument_name": "message",
        "message_suffix": "追加的資訊",
        "query": [
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
        ]
    },
    "telebot_notify": false,
    "telebot_token": "",
    "telebot_use_chat_id": false,
    "telebot_chat_id": "",
    "discord_notify": false,
    "discord_token": "",
    "plex_refresh": false,
    "plex_url": "",
    "plex_token": "",
    "plex_section": "",
    "plex_naming": false,
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": false,
    "danmu": false,
    "danmu_ban_words": [],
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "mobile_ads_time": 25,
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 17.2,
    "database_version": 2.0
}
## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
[sn_list-sample.txt](https://github.com/miyouzi/aniGamerPlus/files/12468774/sn_list-sample.txt)

**最好上傳 log 檔案**

**Comment by testabcc** [comment]
遇到同樣問題，不知道什麼時候能有新版本。

**Comment by miyouzi** [comment]
Log 和 config.json 發一下

**Comment by wibe01204** [comment]
@miyouzi 我也遇到一樣的問題，以下是log與config
```
2023-09-04 00:23:13 Dashboard 通過 Web 控制臺下達了手動任務
2023-09-04 00:23:13 解析模式: sn=27345	Web解析
2023-09-04 00:23:13 收到新cookie: sn=27345	
2023-09-04 00:23:13 用戶cookie刷新  : sn=27345	
2023-09-04 00:23:14 收到cookie重置響應: sn=27345	
2023-09-04 00:23:16 抓取失敗: sn=27345	抓取影片信息時發生未知錯誤: 'BAHARUNE'
2023-09-04 00:23:16 抓取異常: sn=27345	異常詳情:
Traceback (most recent call last):
  File "aniGamerPlus.py", line 55, in build_anime
  File "Anime.py", line 73, in __init__
  File "Anime.py", line 141, in __get_src
  File "Anime.py", line 361, in __request
  File "Anime.py", line 326, in __request
KeyError: 'BAHARUNE'
```
```
{
    "bangumi_dir": "C:\\Users\\wibe0\\OneDrive\\桌面",
    "temp_dir": "",
    "classify_bangumi": true,
    "classify_season": false,
    "check_frequency": 5,
    "download_cd": 60,
    "parse_sn_cd": 5,
    "download_resolution": "720",
    "lock_resolution": true,
    "only_use_vip": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
    "use_proxy": false,
    "proxy": "http://user:passwd@example.com:1000",
    "no_proxy_akamai": false,
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "msg_argument_name": "message",
        "message_suffix": "追加的資訊",
        "query": [
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
        ]
    },
    "telebot_notify": false,
    "telebot_token": "",
    "telebot_use_chat_id": false,
    "telebot_chat_id": "",
    "discord_notify": false,
    "discord_token": "",
    "plex_refresh": false,
    "plex_url": "",
    "plex_token": "",
    "plex_section": "",
    "plex_naming": false,
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": false,
    "danmu": false,
    "danmu_ban_words": [],
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "mobile_ads_time": 25,
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 17.2,
    "database_version": 2.0
}
```

**Comment by Bill920405** [comment]
> Log 和 config.json 發一下
> 
> 另外 `sn_list-sample.txt` 要重命名成 `sn_list.txt` 才會生效
[2023-09-04.log](https://github.com/miyouzi/aniGamerPlus/files/12506619/2023-09-04.log)
{
    "bangumi_dir": "",
    "temp_dir": "",
    "classify_bangumi": true,
    "classify_season": false,
    "check_frequency": 5,
    "download_cd": 60,
    "parse_sn_cd": 5,
    "download_resolution": "1080",
    "lock_resolution": false,
    "only_use_vip": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0",
    "use_proxy": false,
    "proxy": "http://user:passwd@example.com:1000",
    "no_proxy_akamai": false,
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "msg_argument_name": "message",
        "message_suffix": "追加的資訊",
        "query": [
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
        ]
    },
    "telebot_notify": false,
    "telebot_token": "",
    "telebot_use_chat_id": false,
    "telebot_chat_id": "",
    "discord_notify": false,
    "discord_token": "",
    "plex_refresh": false,
    "plex_url": "",
    "plex_token": "",
    "plex_section": "",
    "plex_naming": false,
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": false,
    "danmu": false,
    "danmu_ban_words": [],
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "mobile_ads_time": 25,
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 17.2,
    "database_version": 2.0
}

**Comment by wibe01204** [comment]
好像是cookie的關係
我把cookie拿掉就可以正常下載
![image](https://github.com/miyouzi/aniGamerPlus/assets/90883053/7c9db1ab-d6f3-46bb-8e34-95f7ffa6dae5)

**Comment by takodoko** [comment]
一樣的問題,請問怎麼解決
cookie拔掉可以載但就變成他不能登入只有360p
會是cookie的問題嗎?
原文步驟:
輸入allow pasting

接著輸入document.cookie按Enter，就會印出目前的cookie (下圖打碼部份)

我用EDGE,第一個跑出error,但二個還是顯示出來了

**Comment by wibe01204** [comment]
@takodoko 是cookie的問題沒錯
我的cookie幾乎每天都不一樣
不過我的解決了
我直接用f12進去後慢慢找，然後找到的那串可以用 用指令找的反而不行
我晚點再補位置的圖片

**Comment by miyouzi** [comment]
檢查一下是不是 cookie.txt 中是不是沒有 BAHARUNE

**Comment by wibe01204** [comment]
我現在是直接到這邊抓
![image](https://github.com/miyouzi/aniGamerPlus/assets/90883053/2d2107b9-98b2-4cfe-be09-e5d715a050b3)

**Comment by takodoko** [comment]
> 我現在是直接到這邊抓 ![image](https://user-images.githubusercontent.com/90883053/270163696-2d2107b9-98b2-4cfe-be09-e5d715a050b3.png)

感謝,從這邊用就能720下載

**Comment by takodoko** [comment]
https://cdn.discordapp.com/attachments/655420905148776454/1157952006493843566/image.png?ex=651a7a58&is=651928d8&hm=e9789ec05f316c98d217e47f3fb09d43b18d561d196b09f3a69bcc98ed41af79&
突然有了新問題 不好意思
使用前有更新UA跟替換cookie,但他好像讀到了卻抓不到720
