### ISSUE TITLE
使用一切安好，好奇為什麼list模式不支援single下載模式

### ISSUE THREAD

**Issue by af8662** [miyouzi/aniGamerPlus#26]
如標題，單純好奇為什麼不支援single下載模式

**Comment by miyouzi** [comment]
是支援的，但是需要在cmd中敲指令使用。詳情見 README 中的 ```命令行使用``` 。

**Comment by af8662** [comment]
剛才有看到cmd使用方式了，使用-s參數沒問題
使用sn_list.txt的list模式沒辦法使用single模式下載是嗎，因為這是吃config.json的模式，但是config.json的選項沒有single這項。主要就是問為什麼指令可以下但是config.json無法設，謝謝。

**Comment by af8662** [comment]
另外剛剛發現在資料夾中還沒有db檔案的情況下第一次執行`aniGamerPlus.exe-m list` 會出錯，似乎是無法成功建立aniGamer.db。如果先雙擊執行exe建立好資料庫再下一次指令就沒問題，不知道算不算個bug

**Comment by af8662** [comment]
另外還想請問如果想用-e參數下載24.5集或是特別篇這種的有辦法嗎，例如sn=12067, 12671, 14304這三個，不好意思問題有點多。

**Comment by miyouzi** [comment]
single 模式的定位是單次單集下載，比如你覺得某集很好，只想下載這個別集，那麽就打開cmd指令下載這集。

自動模式（使用```sn_list.txt```）的定位是全天候挂機自動下載，定位是放在伺服器或者NAS對新番監控更新，並在更新后自動下載。

如果你有對 ```sn_list.txt``` 中的内容進行單次的批量下載需求，那麽你可以在 cmd 中使用 ```list``` 模式，這個模式會讀取你 ```sn_list.txt``` 中的配置並記錄任務狀態，與自動模式的區別是所有任務下載完成后就推出，不再監控更新。

你的需求是對一些番劇最新一集進行下載呢，還是無規律對某些集數進行下載？

>在資料夾中還沒有db檔案的情況下第一次執行aniGamerPlus.exe-m list 會出錯，似乎是無法成功建立aniGamer.db

確實這是BUG，需要修復。

>如果想用-e參數下載24.5集或是特別篇這種的有辦法嗎

考慮到這類基本只有一兩個，所以 ```range模式``` 不包含這類，用 ```single模式``` 即可，```all模式``` 則可以覆蓋這些。

**Comment by af8662** [comment]
我的需求是無規律下載檔案中的sn集數，比如說以下的`sn_list.txt`
```
# 關於我轉生變成史萊姆這檔事
12067
12671
14304
```
執行`aniGamerPlus.exe -m list`會讀取到這三個是同一部作品，然後只會下載這部作品的最新一集，我希望的是下載這三個我指定的集數
```
未设定下载解析度, 将使用配置文件指定的清晰度: 1080P
2020-01-15 21:37:30 加入任务列隊: sn=14304
2020-01-15 21:37:30 任務資訊 共 1 個任務

2020-01-15 21:37:31 正在等待: sn=14304 《關於我轉生變成史萊姆這檔事 [特別篇2]》 由於不是VIP賬戶, 正在等待8s廣告時間


2020-01-15 21:37:34 你終止了程序!
```
另外`config.json`裡的default_download_mode我有改成single，但是就如README寫的，會自動默認為latest模式

`"default_download_mode": "single",`

如果我不能用`sn_list.txt`無規律下載，有辦法做到`aniGamerPlus.exe -s [sn, sn, sn]`類似的事情嗎

**Comment by miyouzi** [comment]
>有辦法做到aniGamerPlus.exe -s sn[, sn, sn]類似的事情嗎

下一個版本將嘗試加入這一功能

**Comment by af8662** [comment]
了解，感謝你的回覆。
所以`-m list`自動模式是不打算增加single下載模式或是有技術上的困難嗎?
如上一則回覆說的給三個sn但是都只讀取到共同的lastest的一集

**Comment by miyouzi** [comment]
>所以```-m list```自動模式是不打算增加single下載模式或是有技術上的困難嗎?

技術上應該可行，那就 ```config.json``` 增加 ```single``` 模式配合```-m list```實現使用  ```sn_list.txt``` 單集下載。

另外會考慮加入bat檔案，方便使用命令行模式及方面啓動```-m list```

**Comment by af8662** [comment]
# 猜測可能會碰到的問題
## 例如以下的`sn_list.txt`，使用自動模式
```
# 關於我轉生變成史萊姆這檔事
12067 single
12671 lastest
14304 # 無註記 使用config.json的設定
```
single的下載完畢後，因為前面有提到自動模式的設計是為了24小時全天候自動下載，掛機要不要繼續監看那部設定為single的作品就看作者的設計了。
## -s -e 參數的衝突
例如以下命令
`aniGamerPlus.exe -s 11990, 12067 -e 1-3, 5`
1.當初設計-s 只能指定一部作品，如果增加能指定多部作品，配合-e 的使用可能要注意一下。
2.或者乾脆就直接無視直接用個for迴圈將兩部作品的指定episode都下載，即使如此可能還是要檢查兩個編號是不是同部作品，避免重複下載。
3.或是另外增加一個-multi 之類的參數，使用這個參數時不可搭配-e 使用等等。

**Comment by miyouzi** [comment]
你說的問題確實值得注意，我在修改時會注意這幾個問題。謝謝！

**Comment by miyouzi** [comment]
考慮使用```--multi```實現多 sn 的下載，你覺得這個模式是否需要將任務狀態記錄在資料庫呢？

**Comment by af8662** [comment]
應該是指cmd下的使用吧?
我覺得不論用cmd下`--multi`或是
```
# sn_list.txt
12067 # config.json中下載模式預設為single
12671
14304
```
都可以記錄在database中。這樣使用掛機模式時，先前用`--multi`下載的sn也都會被忽略
## 
我印象中使用cmd下載指定sn時(single)會無視db的記錄強制重新下載。
應該可以比照相同方式，雖然都有記錄起來(原本的single有記錄嗎?)，但是用cmd下`--multi`時會強制重新下載一次。

不過這邊我不清楚你原本的做法，因為強制下載可能會有同sn出現在db中兩次，還是要看你維護更新資料庫的方式。
##
被你這麼一問，突然好奇原本使用cmd下載單一sn會記錄到db嗎?
我的想法是可以記錄起來

**Comment by miyouzi** [comment]
命令行祇有 list 模式會將任務狀態記錄在資料庫，其他模式我想的情景是小數量的下載，不記錄任務狀態比較合。

將任務狀態記錄在資料庫，重複的任務就不會重複下載，如果下載過了還需要再下載則需要刪除資料庫，或者打開資料庫刪除對應的任務記錄。

**Comment by af8662** [comment]
不然就維持命令行只有 list 模式會記錄，`--multi`就不用記錄。
list 模式新增了single以後也可以下載多個隨機指定的sn和`--multi`功能基本相同，差別就是一個會記錄一個不記錄。不過README中可能可以寫清楚一些，說只有使用`sn_list.txt`下載的檔案會記錄到資料庫
(或是其實只是我沒有看清楚?)
##
這邊我想請你再多做一個功能，list 模式中的強制下載，如下
```
# sn_list.txt
12067 force # 類似single 但無視資料庫 強制重新下載指定sn
12671 single # 如資料庫中有記錄則不下載
```
不過可能是我不習慣list模式的用法，這個你可以斟酌一下，因為我主要是偶爾會需要下一兩部的小需求而已。

**Comment by miyouzi** [comment]
目前已實現：
 - 不記錄在資料庫，下載多個 sn，在命令行輸入：
```
aniGamerPlus.py -m multi -e 14479,14518,14511
```
當模式為```multi```時```-e```參數後面接sn號，使用英文```,```分割

---

- 記錄在資料庫，從```sn_list.txt```中讀取sn，在命令行輸入：
```
aniGamerPlus.py -m sn-list
```
```sn_list.txt```中，sn后不用加 ```single```，sn後面的模式設定會被忽略，僅下載單個sn

---

>這邊我想請你再多做一個功能，list 模式中的強制下載

```list```模式用於單次的大量下載，遇到需要重下的情況，我覺得是個別幾個檔案損壞，或者幾乎全部需要重下（比如買了會員想再下載1080P版本），前者用命令行單集下載即可，後者的話直接刪除資料庫吧。

目前你覺得可以滿足需求嗎？

**Comment by af8662** [comment]
所以`aniGamerPlus.py -m sn-list`和原本的`aniGamerPlus.py -m list`等於是兩者獨立的功能嗎
- `list`模式 是原本的掛機模式
- `sn-list`模式 則是這次新增的用於單次下載多個指定sn，會忽視sn後面的模式設定

是這樣嗎?
##
強制下載的部分，這樣看起來應該還OK，如果有其他的問題再來請你解決，謝謝

**Comment by miyouzi** [comment]
是的。```sn-list```和```list```模式功能不同。

>```list```模式 是原本的掛機模式

```list```模式不是挂機模式，他是命令行模式，它只對```sn_list.txt```檢查一次，任務下載完后就結束。

挂機模式是雙擊啓動的（不加任何參數），它會每隔一段時間檢查一次，即使所有任務完成，也不會退出，而是持續監控是否有更新。

>```sn-list```模式 則是這次新增的用於單次下載多個指定sn，會忽視sn後面的模式設定

這點是的

**Comment by miyouzi** [comment]
[v18](https://github.com/miyouzi/aniGamerPlus/releases/tag/v18) 已發佈。

由於改動較大，可能存在一些 bug，因此發佈為 Pre-release，歡迎進行測試

**Comment by craze429** [comment]
應用情境：追舊番、季中才追新番時，使用命令行下載前幾集，確認要追整季後，再用掛機模式下載全部的
問題：因命令行下載模式的single、range等不會記錄到資料庫，再使用掛機模式時，會重複下載
可能解決的方法：
1. 命令行加入選項：下載前檢查資料庫並將任務狀態記錄在資料庫中
2. 命令行加入選項：-m/-e不實際下載，僅做資料庫的修改，例如：刪除該sn已下載記錄、新增該sn已下載記錄
3. config.json中加入選項：當下載存放目錄已有該檔案時，跳過該任務

**Comment by miyouzi** [comment]
@craze429 我覺得你的```使用命令行下載前幾集```可以用新添加的功能```-m sn-list```下載這幾集時就記錄到資料庫，這樣可以避免後續重複下載。
