### ISSUE TITLE
功能請求：希望有指定集數範圍下載

### ISSUE THREAD

**Issue by syfeng911** [miyouzi/aniGamerPlus#264]
看到有人說下載太多會被鎖帳號，是否能新增個指定集數下載。
這樣能分多個帳號下載，比較不會被鎖

**Comment by KuoHsiangYu2** [comment]
有阿，這個功能已經有推出了。
你可以用 command line 下指令執行。

以下指令是在 Windows 10環境測試，
所以我把 python3 改成 python

假設我想要下載「神劍闖江湖 ―明治劍客浪漫譚」第 19,20,21 集
下指令
python aniGamerPlus.py -r 1080 -d -s 35812 -e 19,20,21

-r 1080 指定 1080P解析度
-d 下載彈幕
-s 35812 神箭闖江湖 第19集SN編號 35812
-e 19,20,21 指定下載第 19、20、21集

**Comment by KuoHsiangYu2** [comment]
可能就一天偷偷下載1~5集，第二天偷偷下載6~10集，能降低被 巴哈姆特動畫瘋 鎖住帳號的機率。

**Comment by syfeng911** [comment]
好的，我先這樣用看看，不過還是私心大大能有介面直接點 XDD

**Comment by gitqwerty777** [comment]
下載一集的間隔調長一點，可以有效減少被ban的可能性

像是設定檔內的 `download_cd` 調高  `multi_downloading_segment` 調到1

**Comment by Patttaaa** [comment]
> 我感覺可以建議增加一個當天最高下載量。 搭配模擬人類觀看速度，完美

我認同這個做法，才不會今天可以下載，隔天就突然被ban帳號了><那可是非常無言的...

**Comment by miyouzi** [comment]
CLI 已有此功能
