### ISSUE TITLE
裝置檢驗異常 發生未知異常：1 有無解決方案？

### ISSUE THREAD

**Issue by 54Jezz** [miyouzi/aniGamerPlus#266]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#
裝置檢驗異常 發生未知異常：1
## 錯誤截圖
#在這裏附上錯誤的窗口截圖#
![2023_12_21_23_12_IMG_0006](https://github.com/miyouzi/aniGamerPlus/assets/138966247/ae8ee7d0-d9ec-47ca-882e-3df68cba3261)

## config.json 配置
```
#將你的config.json内容複製到這裏#
```

## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```

**最好上傳 log 檔案**

**Comment by Patttaaa** [comment]
一次下載超過100多話就會這樣，把它使用範圍下載就解決了

**Comment by 54Jezz** [comment]
我明白原因了 是因爲我點了那個模擬手機端解析才會這樣的 取消掉就沒有出現問題了 但我不明白那個鍵的作用是什麽？

**Comment by miyouzi** [comment]
> 我明白原因了 是因爲我點了那個模擬手機端解析才會這樣的 取消掉就沒有出現問題了 但我不明白那個鍵的作用是什麽？
> 

這是和網頁端不同的解析方式，準備兩種解析方式是為了一個方式掛掉的時候還有另一個能用
