### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by Jacky346** [miyouzi/aniGamerPlus#27]
## 問題描述
m3u8获取失败

## 錯誤截圖
#在這裏附上錯誤的窗口截圖#

## config.json 配置
```默认
#將你的config.json内容複製到這裏#
```

## sn_list.txt 配置
```默认
#將你的sn_list.txt内容複製到這裏#
```

**最好上傳 log 檔案**

**Comment by miyouzi** [comment]
问题描述能详细一点吗？

**Comment by Jacky346** [comment]
2020-01-20 20:14:08 任務狀態: sn=11927 ERROR: 请求失败！except：
('Connection aborted.', OSError(0, 'Error'))
3s后重试(最多重试3次)
2020-01-20 20:14:11 任務狀態: sn=11927 ERROR: 请求失败！except：
('Connection aborted.', OSError(0, 'Error'))
3s后重试(最多重试3次)
2020-01-20 20:14:14 任務狀態: sn=11927 ERROR: 请求失败！except：
('Connection aborted.', OSError(0, 'Error'))
3s后重试(最多重试3次)
2020-01-20 20:14:17 下載狀態: sn=11927 獲取 m3u8 失敗!

**Comment by Jacky346** [comment]
Termux运行的，之前可以

**Comment by miyouzi** [comment]
我测试使用没问题。你的错误是网络因素导致的。

你是有使用代理吗？检查一下代理是否正常？

**Comment by Jacky346** [comment]
正常啊😯

**Comment by Jacky346** [comment]
这会可以了

**Comment by Jacky346** [comment]
尴尬了

**Comment by Jacky346** [comment]
另外，能不能支持下下载弹幕ass啊

**Comment by miyouzi** [comment]
暂不打算支持巴哈弹幕下载，你可以通过弹弹Play去加载巴哈的弹幕。

**Comment by Jacky346** [comment]
那个项目我知道，但好像不是所有的动漫都有，下载弹幕麻烦些，虽然也有一个火狐的插件，感觉不如命令行方便

**Comment by miyouzi** [comment]
弹弹Play支持通过链接获取弹幕
![image](https://user-images.githubusercontent.com/24269465/72731871-81ca2880-3bcf-11ea-99e3-cca34e1a278f.png)

**Comment by Jacky346** [comment]
感谢提醒
