### ISSUE TITLE
一直出現抽取失敗（Issue #269）

### ISSUE THREAD

**Issue by a9689071224** [miyouzi/aniGamerPlus#271]
您要我提供config.json但無法開啟
![螢幕擷取畫面 2024-04-05 004617](https://github.com/miyouzi/aniGamerPlus/assets/165942530/a159a6d8-62a8-4f18-a260-5410f778d5bd)
![螢幕擷取畫面 2024-04-05 004726](https://github.com/miyouzi/aniGamerPlus/assets/165942530/a556715e-e340-430b-9b31-89fbad7bfa62)
![螢幕擷取畫面 2024-04-05 004750](https://github.com/miyouzi/aniGamerPlus/assets/165942530/955e35c0-3ee8-4b8f-adc8-22dd4cd2085c)
![螢幕擷取畫面 2024-04-05 120257](https://github.com/miyouzi/aniGamerPlus/assets/165942530/a812a029-ea98-4884-9026-5cf272036f46)
![螢幕擷取畫面 2024-04-05 120348](https://github.com/miyouzi/aniGamerPlus/assets/165942530/4fc460e5-5361-4238-bcbc-cd3fd77851d5)

**Comment by miyouzi** [comment]
同一個問題請不要反復建新 issue ！

json 檔案可以用記事本打開。

你的 cookie 中缺少 `BAHARUNE` ，請使用 `readme` 中説明的方式獲取 cookie

![image](https://github.com/miyouzi/aniGamerPlus/assets/24269465/069c518e-1d95-44ed-8d33-f198a0497146)
