### ISSUE TITLE
一直出現抽取失敗（Issue #269） (Issue #271)

### ISSUE THREAD

**Issue by a9689071224** [miyouzi/aniGamerPlus#272]
抱歉.依您的方法.目前出現錯誤如下
![螢幕擷取畫面 2024-04-05 155323](https://github.com/miyouzi/aniGamerPlus/assets/165942530/d36a72a4-af70-4683-a2f0-afa455008683)

**Comment by JuenTingShie** [comment]
請讀readme

**Comment by KuoHsiangYu2** [comment]
假設你用的是 Windows作業系統。
依照 readme文件 ，
這個程式依賴 ffmpeg.exe 這個執行檔。
您需要下載並把 ffmpeg.exe執行檔 放置在專案資料夾的位置。
