### ISSUE TITLE
無法下載動畫-(已解決)

### ISSUE THREAD

**Issue by kevim31416** [miyouzi/aniGamerPlus#278]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#
不知道為甚麼會跑出這個錯誤訊息

ERROR: 请求失败！except：
HTTPSConnectionPool(host='ani.gamer.com.tw', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', timeout('The handshake operation timed out')))
3s后重试(最多重试3次)

## 錯誤截圖
#在這裏附上錯誤的窗口截圖#

## config.json 配置
```
#將你的config.json内容複製到這裏#
```

## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```

**最好上傳 log 檔案**

**Comment by kevim31416** [comment]
不好意思 突然發現是我電腦的問題 現在已經解決了 但不知道要要怎麼刪帖 能的話可以麻煩您幫忙刪帖嗎?謝謝

**Comment by JuenTingShie** [comment]
You couldn't delete issues, just close it.

**Comment by kevim31416** [comment]
> ## 問題描述
> #在這裡詳細說明您遇到了什麼問題# 不知道為什麼會出現這個錯誤訊息
> 
> ERROR: 請求失敗 ！ The握手操作超時'))) 3s後重試(最多重試3次)
> 
> ## 錯誤截圖
> #這裡附上錯誤的視窗截圖#
> 
> ## config.json 配置
> ```
> #將你的config.json内容複製到這裏#
> ```
> 
> ## sn_list.txt 配置
> ```
> #將你的sn_list.txt内容複製到這裏#
> ```
> 
> **最好 上傳日誌文件**



> You couldn't delete issues, just close it.

請問要怎麼關閉?

**Comment by kevim31416** [comment]
> You couldn't delete issues, just close it.

請問要怎麼關閉?

**Comment by kevim31416** [comment]
> You couldn't delete issues, just close it.
請問要怎麼關閉?
How do I close it?

**Comment by KuoHsiangYu2** [comment]
> > You couldn't delete issues, just close it.
> > 請問要怎麼關閉?
> > How do I close it?

直接按 close issue 就行了。  
可參考下述網站  
https://docs.github.com/en/enterprise-cloud@latest/issues/tracking-your-work-with-issues/closing-an-issue

**Comment by KuoHsiangYu2** [comment]
> > You couldn't delete issues, just close it.
> > 請問要怎麼關閉?
> > How do I close it?

你就滑到最下面，
就有 close issue 的按鈕。
填入訊息，按下 close issue按鈕 就可以關閉這張 issue 。

**Comment by kevim31416** [comment]
> > > You couldn't delete issues, just close it.
> > > 請問要怎麼關閉?
> > > How do I close it?
> 
> 你就滑到最下面， 就有 close issue 的按鈕。 填入訊息，按下 close issue按鈕 就可以關閉這張 issue 。

喔喔喔 有找到了 謝謝

**Comment by kevim31416** [comment]
問題已解決
