### ISSUE TITLE
config.json問題

### ISSUE THREAD

**Issue by w0853** [miyouzi/aniGamerPlus#28]
## 問題描述
我直接copy官網語法並將ua放進生成config.json文件,打開主程式跳掉.
以前我來過貴網站用這程式(v16的樣子),我記得當時也是主程式跳掉(試了好幾次),最後放棄使用.後來去年11月有再試(v17),當時沒管config.json用法-
對不起,我知道這對你來說是很麻煩的事,但我還是想知道語法是要怎樣copy(我是用滑鼠反白)?-因為我copy3,4次,ua也進去,但就是開主程式一直跳掉,
還有這次版本32成功了https://github.com/miyouzi/aniGamerPlus/issues/24
感謝

## 錯誤截圖
#在這裏附上錯誤的窗口截圖#
[https://streamable.com/cin57](url)
用影片給你看會比較清楚-這種狀況我不知該怎麼截圖=_=|||

## config.json 配置
```
#將你的config.json内容複製到這裏#
```
{
    "bangumi_dir": "",  # 下載存放目錄, 動畫將會以番劇為單位分資料夾存放
    "temp_dir": "",  # 臨時目錄位置, v9.0 開始下載中文件將會放在這裏, 完成後再轉移至番劇目錄, 留空默認在程序所在目錄的 temp 資料夾下
    "classify_bangumi": true,  # 控制是否建立番劇資料夾
    "check_frequency": 5,  # 檢查更新頻率, 單位為分鐘
    "download_resolution": "1080",  # 下載選取清晰度, 若該清晰度不存在將會選取最近可用清晰度, 可選 360 480 540 576 720 1080
    "lock_resolution": false,  # 鎖定清晰度, 如果指定清晰度不存在, 則放棄下載
    "default_download_mode": "latest",  # 默認下載模式, 另一可選參數為 all 和 largest-sn. latest 為僅下載最後一集, all 下載番劇全部劇集, largest-sn 下載最近上傳的一集
    "use_copyfile_method": false,  # 轉移影片至番劇資料夾時使用複製方法, 適用於保存到 rclone 掛載盤的情況
    "multi-thread": 1,  # 最大并發下載數, 最高為 5, 超過將重置為 5
    "multi_upload": 3,  # 最大并發上傳數
    "segment_download_mode": true,  # 分段下載模式, 速度更快, 容錯率更高
    "segment_max_retry": 8,  # 在分段下載模式時有效, 每個分段最大重試次數, -1 為無限重試
    "multi_downloading_segment": 3,  # 每個影片最大并發下載分段數, 僅在 "segment_download_mode" 為 true 時有效, 最高為 5, 超過將重置為 5
    "add_bangumi_name_to_video_filename": true,  # 如果為 false, 則只有劇集名, 若劇集名為個位數字, 則補零
    "add_resolution_to_video_filename": true,  # 是否在影片檔名中添加清晰度, 格式舉例: [1080P]
    "customized_video_filename_prefix": "【動畫瘋】",  # 影片檔名前綴
    "customized_bangumi_name_suffix": "",  # 影片檔名中番劇名的后缀, 在劇集名之前
    "customized_video_filename_suffix": "",  # 影片檔名後綴
    "video_filename_extension": "mp4",  # 影片檔副檔名, ts, mov, mkv 經過測試可以使用, 但 flv 不支援, 非 mp4 副檔名 faststart_movflags 將强制為 false
    "zerofill": 1,  # 劇集名補零, 填寫補足位數, 例: 填寫 2 劇集名為 01, 填寫 3 劇集名為 001
    "ua": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36",  #  請求UA, 需要和獲取cookie的瀏覽器相同
    "use_proxy": false,  # 代理開關
    "proxies": {
        "1": "socks5://127.0.0.1:1080",  # 代理配置
        "2": "http://user:passwd@example.com:1000"  # 支援鏈式代理
    },
    "upload_to_server": false,  # 上傳功能開關
    "ftp": {  # FTP配置
        "server": "",  # FTP Server IP
        "port": "",  # 端口
        "user": "",  # 使用者名
        "pwd": "",  # 密碼
        "tls": true,  # 是否是 FTP over TLS
        "cwd": "",  # 登陸後首先進入的目錄
        "show_error_detail": false,  # 是否顯示細節錯誤信息
        "max_retry_num": 15  # 最大重傳數, 支援續傳
    },
    "user_command": "shutdown -s -t 60"  # 命令行模式使用 -u 參數有效, 在命令行模式下完成所有任務后執行的命令
    "coolq_notify": false,  # 是否向酷Q推送下載完成訊息
    "coolq_settings": {
        "host": "127.0.0.1",  # 酷Q HTTP API 地址
        "port": "5700",  # 酷Q HTTP API Port
        "SSL": false,  # 是否是 https
        "api": "send_group_msg",  # 所使用的 API
        "query": {  # 使用 GET 方法, 這裏配置 query 字段
            "group_id": "123456789"
        }
    },
    "faststart_movflags": false,  # 是否將影片 metadata 前置, 啓用此功能時在綫觀看會更快播放, 僅在 video_filename_extension 為 mp4 時有效
    "check_latest_version": true,  # 是否檢查更新
    "read_sn_list_when_checking_update": true,  # 是否在檢查更新時讀取sn_list.txt, 開啓後對sn_list.txt的更改將會在下次檢查更新時生效而不用重啓程序
    "read_config_when_checking_update": true,  # 是否在檢查更新時讀取配置文件, 開啓後對配置文件的更改將會在下次檢查時更新生效而不用重啓程序
    "save_logs": true,  # 是否記錄日志, 一天一個日志
    "quantity_of_logs": 7,  # 日志保留數量, 正整數值, 必須大於等於 1, 默認為 7
    "config_version": 7.0,  # 配置文件版本
    "database_version": 2.0  # 資料庫版本
}

*ua已放進
## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```
9242 all # 刀劍神域 劇場版
**最好上傳 log 檔案**
跳掉後沒產生log+temp2個資料夾+aniGamer.db這檔案

不過成功的我還是想給你當作下個版本的參考 
當時跑了幾次
2020-01-28 18:41:30 更新資訊: sn=9242 正在檢查《刀劍神域 劇場版 序列爭戰》
我還以為會失敗=_=

[2020-01-28成功的.log](https://github.com/miyouzi/aniGamerPlus/files/4122930/2020-01-28.log)

如果可以請回答我的問題-我還是希望自己能生成config.json(記事本),而不是開主程式(aniGamerPlus.exe)生成

**Comment by miyouzi** [comment]
json檔案是不支援使用注釋的（就是```#```後面的内容），readme那樣寫是爲了方面説明。

正確的使用方式是將```config-sample.json```改名為```config.json``` 后進行編輯。

**Comment by w0853** [comment]
謝謝
