### ISSUE TITLE
 影片編碼選擇? H264? X264? X265?

### ISSUE THREAD

**Issue by jim12050521** [miyouzi/aniGamerPlus#283]
## 問題描述
請問此專案可以選擇編碼器嗎? 目前統一是H264
想到以下可能:  
    
    1. 無法，直接抓取片源的內容封包，所以當然不用多此一舉轉碼，只要用ffmpeg合併即可。
    2. 可能可，因為下載後有經過ffmpeg轉碼。

**Comment by miyouzi** [comment]
本專案的ffmpeg僅做解密合併用途，並不會對影片進行二次轉碼，動畫瘋給什麼就是什麼。

建議有轉碼需求使用其他專業工具。

**Comment by jim12050521** [comment]
冒昧請問，您能做出此專案，是因是資工本科系?

**Comment by miyouzi** [comment]
興趣而已，有興趣可以自學
