### ISSUE TITLE
編碼錯誤

### ISSUE THREAD

**Issue by yumeinori** [miyouzi/aniGamerPlus#286]
## 問題描述
編碼錯誤

## 錯誤截圖
![image](https://github.com/user-attachments/assets/6f179149-e047-407f-bcfb-084b0be8b826)

**最好上傳 log 檔案**
[2024-10-02.log](https://github.com/user-attachments/files/17230377/2024-10-02.log)

**Comment by miyouzi** [comment]
檢查cookie.txt不含特殊字符

**Comment by yumeinori** [comment]
> 檢查cookie.txt不含特殊字符

謝謝 
更換後已解決
