### ISSUE TITLE
can't start new tread

### ISSUE THREAD

**Issue by JuenTingShie** [miyouzi/aniGamerPlus#29]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#
can't start new tread
## 錯誤截圖
#在這裏附上錯誤的窗口截圖#
<img src=https://i.imgur.com/k2R5LeV.png>
## config.json 配置
```
#將你的config.json内容複製到這裏#
```
{
    "bangumi_dir": "/media//pi//e0db58f3-c2b0-495b-99c2-8b3f5395cfa7//Anime//",
    "temp_dir": "/media//pi//e0db58f3-c2b0-495b-99c2-8b3f5395cfa7//Anime//temp//",
    "classify_bangumi": true,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": false,
    "default_download_mode": "all",
    "use_copyfile_method": false,
    "multi-thread": 2,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0",
    "use_proxy": false,
    "proxies": {
        "1": "socks5://127.0.0.1:1080",
        "2": "http://user:passwd@example.com:1000"
    },
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "host": "127.0.0.1",
        "port": "5700",
        "SSL": false,
        "api": "send_group_msg",
        "query": {
            "group_id": "123456789"
        }
    },
    "faststart_movflags": true,
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 10.0,
    "database_version": 2.0
}
## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```

**最好上傳 log 檔案**

開啟"segment_download_mode"就會一直報錯，關掉之後會是正常的，想請問是哪邊有設置錯誤或沒注意到的地方。

有嘗試過reboot, delete temp folder

環境是raspbian, raspberry pi 4B

**Comment by miyouzi** [comment]
你的python使用的是32bit的版本是嗎？

**Comment by JuenTingShie** [comment]
> 
> 
> 你的python使用的是32bit的版本是嗎？

Hmm,在樹梅派上執行 
```shell
$ python3
Python 3.7.3 (default, Dec 20 2019, 18:57:59)
[GCC 8.3.0] on linux
```
只有顯示GCC 8.3.0 on linux

```python
>>> import struct
>>> print(struct.calcsize("P") * 8)
32
```
查到用這一段script檢查，所以我也不太清楚是32bit 還是64bit 的。
那假定是32bit 的話，有甚麼解決辦法呢?

**Comment by miyouzi** [comment]
更新了代碼 git pull 一下

**Comment by JuenTingShie** [comment]
Pull之後正常執行
segment_download_mode=true

感謝您的更新
