### ISSUE TITLE
增加「番劇資料夾開關」設定

### ISSUE THREAD

**Issue by ycs77** [miyouzi/aniGamerPlus#3]
現在每次下載一部番劇，就會增加一個番劇資料夾，然後裡面才會有該劇影片檔。而我大部分時候都是下載新番，每次都還要進資料夾裡複製出來，如果可以增加一個開關，會方便不少。不知可不可以增加此設定?

**Comment by ycs77** [comment]
對了，如果更新了之後，可以順便更新首頁 readme 的設定部分。

**Comment by miyouzi** [comment]
你是用的是命令行模式麽？那在命令行模式裏新增一個開關控制是否新建文件夾如何呢？

**Comment by ycs77** [comment]
不是，我是用Windows執行exe檔自動下載影片

**Comment by miyouzi** [comment]
直接雙擊運行，通過配置文件配置就不是命令行模式（我稱作自動模式）
建立番劇資料夾，是爲了在自動更新多個番劇時方便查找。
取消建立資料夾，所有番劇影片檔將在一個資料夾下，你確定嗎？
我的設計是希望下載到番劇資料夾后，用戶就可以直接觀看了，你説的下載後要再複製出來的使用情景是什麽樣的呢？

**Comment by ycs77** [comment]
確定，如果是可開關，也不會影響其他人使用

使用情景：只要看新番的時候，每一部都各一集，沒有資料夾會比較方便 (對我個人而言 ~ 哈)

**Comment by miyouzi** [comment]
好的，下一個版本將會更新這個功能，將添加至自動模式和命令行模式

**Comment by ycs77** [comment]
非常感謝~~

**Comment by miyouzi** [comment]
v10.0 已新增番劇資料夾控制開關
自動模式在```config.json```中配置```"classify_bangumi": false```開啓
命令行模式通過```-n```參數開啓

**Comment by ycs77** [comment]
功能正常
