### ISSUE TITLE
想问下有没有设置某一个sn下完即止，不再检查更新的选项?

### ISSUE THREAD

**Issue by BakaNoble** [miyouzi/aniGamerPlus#30]
使用的是exe版本，下载一些完结番剧和连载番剧一起的时候会连完结一起检查更新 所以想问下可不可以设置某一个sn只检查一次?

**Comment by miyouzi** [comment]
建議拷貝成兩個，一個負責單次的下載完結番劇，一個負責監控下載連載番劇。

下載完結番劇可以使用```-m list```，下載完成後就退出，詳情見 readme 的 命令行使用 部分的説明。

**Comment by BakaNoble** [comment]
> 建议拷贝成两个，一个负责单次的下载完结番剧，一个负责监控下载连载番剧。
> 
> 下载完结番剧剧可以使用`-m list`，下载完成后就退出，详情见readme的命令行使用部分的说明。

我记得动画疯好像只能同时观看一个番剧吧？双开的话会冲突么

**Comment by miyouzi** [comment]
如果你有使用 cookie 的話，記得使用兩個獨立的 cookie。

對於 aniGamerPlus 來説，是可以多個同時下載的，但是你的瀏覽器在綫觀看可能稍微受到影響，具體表現是觀看途中突然提示別處在觀看並中斷，遇到這種情況瀏覽器刷新就行。

**Comment by BakaNoble** [comment]
好的，我试下 感谢回复!
