### ISSUE TITLE
關於 "#" 號 在sn_list @ 行中失效，請問是feature還是bug

### ISSUE THREAD

**Issue by we684123** [miyouzi/aniGamerPlus#32]
## 問題描述

如題 原本預計是不會顯示在資料夾上的啦
但他就是上去了(ó﹏ò｡)
## 錯誤截圖
![Imgur](https://i.imgur.com/JtOsl6Y.png)

## sn_list.txt 配置
```
@幼女戰記  #有電影版帶沒上動畫瘋
7148  #幼女戰記 
```

**Comment by miyouzi** [comment]
額……```@分類名``` 是```@```後面的所有路徑合法字符都會包括進去的，算feature，需要注釋的話，在上一行或者下一行```#```開頭注釋吧

**Comment by we684123** [comment]
啊 好的 謝謝解答
