### ISSUE TITLE
关于同一时间连续更新集数只能识别出一集的问题

### ISSUE THREAD

**Issue by YFTX2015** [miyouzi/aniGamerPlus#35]
最近当动画疯在同一个时间点更新连续两集的情况下，下载模式除了ALL的其它模式，在list-sn里填入两个编号，最终工具只能识别出一集。举例说明，BANGDREAM!D第三季最近都是逢周二19：00连更两集，比如8、9集，当把两集的编号填入list-sn后，下载模式选择latest或者largest-sn，然后点击exe文件，只能识别出第9集。接着把第9集的编号删除，只保留第8集的编号，结果识别出来的还是第9集。因此建议exe档下载模式增加指定集数下载模式，就像命令行一样。另外，我这边命令行用不起，依赖是安装了的，cmd输入命令回车后直接返回目录，不晓得是咋回事。另外抽时间截图。

_Originally posted by @YFTX2015 in https://github.com/miyouzi/aniGamerPlus/issues/16#issuecomment-598513749_

**Comment by YFTX2015** [comment]
![QQ截图20200314232530](https://user-images.githubusercontent.com/12757305/76684990-366e4c80-664b-11ea-8603-10b082de2d0e.png)

**Comment by miyouzi** [comment]
exe档也是支援命令行的，你嘗試使用命令```aniGamerPlus -h```命令看看。

PS：你給的圖情況有點奇怪，什麽都沒有報。

**Comment by YFTX2015** [comment]
好了，终于弄懂了，可以关闭此issue了。

**Comment by YFTX2015** [comment]
要是我想在命令行输入连续的两个sn号从而建立连续两集的下载任务，该输入怎样的命令？比如14995,14996,我尝试输入anigamerplus.exe -s 14995,14996就显示错误。

**Comment by miyouzi** [comment]
尝试```anigamerplus.exe -m multi -e 14995,14996```

**Comment by YFTX2015** [comment]
测试成功，多谢！

**Comment by YFTX2015** [comment]
上个版本重试次数改成-1之后不是无限重试，最新版还没测
