### ISSUE TITLE
影片處理問題

### ISSUE THREAD

**Issue by hgalytoby** [miyouzi/aniGamerPlus#39]
請問我自己看Network的影片網址每一段續傳影片都會接一個key網址..
是怎麼跟ts影片做處理的?
研究了您的程式碼..
只曉得開了現程 !
將處理好的url丟進去之後就等載好影片了??
想知道原理怎麼處理影片網址的 可以指教嗎?

**Comment by miyouzi** [comment]
動畫瘋用的是帶key的m3u8，可以去瞭解一下。

本專案是使用ffmpeg來進行解密与合併的。

**Comment by hgalytoby** [comment]
謝謝 我稍微了解m3u8了
我看巴哈有個網址裡有 m3u8的檔 裡面有全部ts的網址
我用ffmepg後 會發生
![image](https://i.imgur.com/fYBOkO9.png)
請問 我有什麼該處理的沒處理嗎?

**Comment by miyouzi** [comment]
參見 [Anime.py 中的 **__ffmpeg_download_mode** 方法](https://github.com/miyouzi/aniGamerPlus/blob/5f8e050b1bf15db1caf8dca31ef68364f93c6988/Anime.py#L568)

裏面包含構造 ffmpeg 指令。
