### ISSUE TITLE
下載過後的檔案無法重複下載

### ISSUE THREAD

**Issue by snoopyzx963** [miyouzi/aniGamerPlus#40]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#
下載過後的檔案無法重複下載

## 錯誤截圖
#在這裏附上錯誤的窗口截圖#
![image](https://user-images.githubusercontent.com/64859195/81093946-680de080-8f35-11ea-833e-9c6ba39fc5d5.png)
圖中已完成下載第一集，若再次執行(原檔案刪除)，則無法再次下載第一集

## config.json 配置
```
#將你的config.json内容複製到這裏#
```

## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```

**最好上傳 log 檔案**
![image](https://user-images.githubusercontent.com/64859195/81093856-43196d80-8f35-11ea-8029-70a73d78c118.png)

**Comment by miyouzi** [comment]
設計上是這樣的，你想重新下載第一集的話，以下幾個方法你可以選擇：

1. 刪除 ```aniGamer.db``` 檔案，但這樣所有集數的狀態記錄將會丟失！

2. 使用 SQLite Expert 這類工具，編輯 ```aniGamer.db```，將你需要重新下載的集數狀態記錄刪除。

3. 使用命令行模式，手動添加下載任務，如果你需要重下的集數不多，推薦使用此方法。

**Comment by snoopyzx963** [comment]
謝謝! 2的話也滿直觀的，十分感謝。
