### ISSUE TITLE
1080p解析度是否能使用?

### ISSUE THREAD

**Issue by andy613** [miyouzi/aniGamerPlus#5]
您好 想請問1080p解析度下載是否能使用
我用暴力猴裡面腳本抓M3U8 連結，可以抓到1080P的
但是用aniGamerPlus抓不到 只能抓到720

感謝

**Comment by miyouzi** [comment]
支援的，需要提供cookie，請閲讀 https://github.com/miyouzi/aniGamerPlus#cookietxt

本專案不需要自己抓m3u8，只需提供sn碼

**Comment by andy613** [comment]
您好，我有提供cookie
我之前是有正常使用720p下載
但是我今天剛購買付費方案，也有再次更新了cookie，卻還是只能下載720

**Comment by miyouzi** [comment]
可以提供一下log嗎？可以的話同時附上 config.json

**Comment by andy613** [comment]
[2019-03-11.log](https://github.com/miyouzi/aniGamerPlus/files/2956388/2019-03-11.log)

[config.txt](https://github.com/miyouzi/aniGamerPlus/files/2956391/config.txt)

**Comment by miyouzi** [comment]
檢查檔案名是否正確，配置的檔名是```config.json```，而不是```config.txt```，cookie的檔名是```cookie.txt```

另外，通過配置```"lock_resolution": false```可以避免下載非指定的解析度

**Comment by andy613** [comment]
你好，因為github無法上傳`.json`檔案，所以我上傳時改成`.txt`
`cookie.txt`檔案名也是正確
另外我有嘗試更改成`"lock_resolution":true` 去指定下載1080解析度
但是他也是寫說 `指定清晰度不存在, 因當前鎖定了清晰度, 下載取消`
下面是我更改成`lock_resolution":true`的 `log`以及`config.json `
一樣我把`config.json `更改成`config.txt `上傳 
謝謝
[2019-03-12.log](https://github.com/miyouzi/aniGamerPlus/files/2956522/2019-03-12.log)
[config.txt](https://github.com/miyouzi/aniGamerPlus/files/2956529/config.txt)

**Comment by miyouzi** [comment]
請問你能在巴哈的歷史記錄看到 aniGamerPlus 下載的影片記錄嗎？

**Comment by andy613** [comment]
不好意思 請問指的是巴哈的登入狀態顯示嗎?
[ https://home.gamer.com.tw/login_devices.php ](url) 您文中的這個網址?

**Comment by miyouzi** [comment]
指的是這裏 https://ani.gamer.com.tw/viewList.php ，如果 aniGamerPlus 正確讀取了 cookie 了，那麽 aniGamerPlus 所抓的所有影片都會顯示在這

**Comment by andy613** [comment]
沒有顯示 aniGamerPlus 的下載紀錄 

我重新抓cookie試試

**Comment by andy613** [comment]
您好，我全部重新設置了一次，也是跟之前一樣只能下載720，不知道原因

動畫瘋，也沒有 aniGamerPlus 的下載紀錄

我後來去動畫瘋測試，發現只有點擊播放，才會有觀看紀錄

如果直接獲取 "M3U8 連結" ，則不會留下觀看紀錄

**Comment by miyouzi** [comment]
可以截圖一下 aniGamerPlus 所在的資料夾麽？

**Comment by andy613** [comment]
![image](https://user-images.githubusercontent.com/48446011/54200218-d4de4400-4505-11e9-9464-35134c434d97.png)

我試試看 改成英文資料夾

**Comment by miyouzi** [comment]
額……你的系統隱藏了副檔名了，也就是你的cookie檔案實際上是```cookie.txt.txt```，你把 ```.txt```刪除試試

**Comment by andy613** [comment]
恩..刪除後就可以正常使用了 

非常感謝您的協助！

**Comment by andy613** [comment]
再次謝謝您提供這樣方便的腳本！

**Comment by miyouzi** [comment]
謝謝你的支持，這個問題我會考慮進防呆，下一個版本會自動處理這種情況
