### ISSUE TITLE
發生未知錯誤 audio_language_jpn

### ISSUE THREAD

**Issue by bhetsdfg** [miyouzi/aniGamerPlus#51]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#
發生未知錯誤 audio_language_jpn 怎麼辦 

## 錯誤截圖
![註解 2020-06-20 192015](https://user-images.githubusercontent.com/61273590/85200597-62c0f580-b32b-11ea-95d5-eb87db642952.png)

## config.json 配置
{
    "bangumi_dir": "C:\\Users\\user\\OneDrive\\OneDrive - Sky University of Technology\\動漫檔",
    "temp_dir": "",
    "classify_bangumi": true,
    "check_frequency": 60,
    "download_resolution": "1080",
    "lock_resolution": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 4,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "❤",
    "customized_video_filename_suffix": "٩(●˙▿˙●)۶…⋆ฺ",
    "video_filename_extension": "mp4",
    "zerofill": 2,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36",
    "use_proxy": false,
    "proxies": {
        "1": "socks5://127.0.0.1:1080",
        "2": "http://user:passwd@example.com:1000"
    },
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "host": "127.0.0.1",
        "port": "5700",
        "SSL": false,
        "api": "send_group_msg",
        "query": {
            "group_id": "123456789"
        }
    },
    "faststart_movflags": false,
    "audio_language": false,
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 11.0,
    "database_version": 2.0
}

## sn_list.txt 配置
15298 <輝夜姬第2季>
15148 <辣妹與恐龍>
15745 <郭台銘與恐龍>

**Comment by miyouzi** [comment]
我這邊無法復現，你可以嘗試使用命令行模式下載看看有沒有更詳細的報錯資訊嗎？

**Comment by bhetsdfg** [comment]
重載後問題已解決
感謝
