### ISSUE TITLE
為甚麼無法順利下載??

### ISSUE THREAD

**Issue by ErenYeagerGuo** [miyouzi/aniGamerPlus#52]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#
無法順利下載??
## 錯誤截圖
#在這裏附上錯誤的窗口截圖#
![Snipaste_2020-07-12_15-32-03](https://user-images.githubusercontent.com/60354391/87241350-dfd81a00-c454-11ea-8bfb-2e29e3a74a18.png)

## config.json 配置
```
#將你的config.json内容複製到這裏#
```
{
    "bangumi_dir": "",
    "temp_dir": "",
    "classify_bangumi": true,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36",
    "use_proxy": false,
    "proxies": {
        "1": "socks5://127.0.0.1:1080",
        "2": "http://user:passwd@example.com:1000"
    },
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "host": "127.0.0.1",
        "port": "5700",
        "SSL": false,
        "api": "send_group_msg",
        "query": {
            "group_id": "123456789"
        }
    },
    "faststart_movflags": false,
    "audio_language_jpn": false,
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 11.0,
    "database_version": 2.0
}
## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```
16344 all # Re：從零開始的異世界生活 第二季 [1] 
@2020七月番
10147 all # 前進吧！登山少女 第三季 [1]
@2018十月番
11285 <史萊姆> # 關於我轉生變成史萊姆這檔事
@2019冬季番
11390 all #笑容的代價 01
11388 # BanG Dream！第二季
11465 all <約會大作戰 III> # 約會大作戰 DATE A LIVE 第三季
@
11317 lastest # SSSS.GRIDMAN
**最好上傳 log 檔案**
[2020-07-12.log](https://github.com/miyouzi/aniGamerPlus/files/4908171/2020-07-12.log)

**Comment by miyouzi** [comment]
檢查一下 FFmpeg 的版本
