### ISSUE TITLE
有缺陷

### ISSUE THREAD

**Issue by mikcc123** [miyouzi/aniGamerPlus#53]
不能重複下載統一部視頻..就算是更換cookie或者更換帳號都不行，就是之前下載的不能再重複下載..就算刪了下載的文件想重新下載也不行，之前下載的有的無法合成（因為代理梯子的原因，刪了重新下載..不料無法重新下載....）

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by miyouzi** [comment]
下載狀態儲存在 aniGamer.db ，刪除它或者編輯它，要麽選擇命令行模式下載

**Comment by mikcc123** [comment]
> 下載狀態儲存在 aniGamer.db ，刪除它或者編輯它，要麽選擇命令行模式下載
好像真有這個文件···我刪了再試試

**Comment by mikcc123** [comment]
我刪了之後重新打開下載也是只能下載最後一集。。。aniGamer.db這個文件打開是亂碼的。。應該怎麽編輯啊？命令行模式不會用

**Comment by miyouzi** [comment]
完整的看一下 Readme，裏面有説明 aniGamer.db 的打開方法和下載模式

**Comment by mikcc123** [comment]
![image](https://user-images.githubusercontent.com/52337606/87634848-a4995c00-c770-11ea-8b62-5a0cfcad47d4.png)

**Comment by mikcc123** [comment]
![image](https://user-images.githubusercontent.com/52337606/87634883-bc70e000-c770-11ea-9ffc-d5cb7f2a12e2.png)
哪里chu'wen'ti'l出问题了？

**Comment by mikcc123** [comment]
![image](https://user-images.githubusercontent.com/52337606/87636276-17a3d200-c773-11ea-82e5-af1416b56fac.png)
![image](https://user-images.githubusercontent.com/52337606/87636295-1ecae000-c773-11ea-9ebe-e93e14f4d658.png)
没有找到教程说的这几项数值~~`

**Comment by mikcc123** [comment]
解决了···在#后面没有空格---嘻嘻嘻
