### ISSUE TITLE
请教个跟ffmpeg相关的问题，因与anigamerplus无直接联系，如作者不愿回答可以无视并直接关闭

### ISSUE THREAD

**Issue by YFTX2015** [miyouzi/aniGamerPlus#57]
## 問題描述
我的电脑不晓得咋个就自动安装上了旧版本的ffmpeg，而且即使用新版本添加到系统PATH，也无法替换老版本，从PATH里面删除也不行，运行ffmpeg -version仍然会显示旧版本的信息。

## 錯誤截圖

![屏幕截图(3)](https://user-images.githubusercontent.com/12757305/89717408-0738ed00-d9e9-11ea-80f9-431362d0be34.png)

有没有办法查看此旧版本的ffmpeg安装路径并卸载?

**Comment by miyouzi** [comment]
可能是安装什么软件自带了ffmpeg放到了path吧

试试```where ffmpeg```。另外提醒一下，ffmpeg 20200515及其之后的版本在合并分段视频的时候处理方式改了，导致aniGamerPlus无法合并分段，最新版不知道还有没有这个问题，如果你有遇到这个问题，尝试使用20200515之前的版本

**Comment by YFTX2015** [comment]
OK
