### ISSUE TITLE
有關廣告時間的建議

### ISSUE THREAD

**Issue by ShinoharaHare** [miyouzi/aniGamerPlus#58]
## 有關廣告時間的建議
使用手機版的API，廣告時間可以降至3秒，但m3u8也得使用手機版API
開始: https://api.gamer.com.tw/mobile_app/anime/v1/stat_ad.php?sn={sn}
結束: https://api.gamer.com.tw/mobile_app/anime/v1/stat_ad.php?sn={sn}&ad=end
M3U8: https://api.gamer.com.tw/mobile_app/anime/v2/m3u8.php?sn={sn}&device={deviceID}

## 順便的爆料
這陣子廣告時間一直改動應該是我害的XD，因為我在GreasyFork發了一個跳過廣告的腳本，起初發現使用類型為 facebook 的廣告 ID 作為 s 參數可以完全不用等待時間，但幾天後就被改成強制20秒了，陸陸續續更新幾個版本後，動畫瘋官方打電話給我，希望我停止更新腳本，我答應後，他們為了讓最後一個版本的腳本失效所以又改成25秒

**Comment by miyouzi** [comment]
😂 那有時間試試手機API解析吧

**Comment by mikcc123** [comment]
> 😂 那有時間試試手機API解析吧

quantumultX有個動畫瘋的規則完美去廣告不知道能不能加入到軟件裡面

**Comment by miyouzi** [comment]
@mikcc123 大概看了一下，quantumult X這個軟件是iOS限定的？

**Comment by mikcc123** [comment]
> @mikcc123 大概看了一下，quantumult X這個軟件是iOS限定的？

是啊，但是安卓好像也有这样的工具，叫clash X

**Comment by mikcc123** [comment]
是啊，但是安卓好像也有这样的工具，叫clash X



> @mikcc123 大概看了一下，quantumult X這個軟件是iOS限定的？

是啊，但是安卓好像也有这样的工具，叫clash X,好像也支持動畫瘋规则，但是我没用过。

**Comment by mikcc123** [comment]
https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Filter/StreamingMedia/Video/Bahamut.list

# > Bahamut
USER-AGENT,Anime*,巴哈姆特動畫瘋
DOMAIN-SUFFIX,bahamut.com.tw,巴哈姆特動畫瘋
DOMAIN-SUFFIX,gamer.com.tw,巴哈姆特動畫瘋
DOMAIN,gamer-cds.cdn.hinet.net,巴哈姆特動畫瘋
DOMAIN,gamer2-cds.cdn.hinet.net,巴哈姆特動畫瘋

这是quantumult X

**Comment by ShinoharaHare** [comment]
前幾天好像連手機版的時間都被改成25秒了
#69 的應該也會無法作用
這邊先close好了
