### ISSUE TITLE
V20突然会闪退不知道怎么回事

### ISSUE THREAD

**Issue by mikcc123** [miyouzi/aniGamerPlus#59]
[##](url) 問題描述
#在這裏詳細説明你遇到了什麽問題#

## 錯誤截圖
#在這裏附上錯誤的窗口截圖#
![image](https://user-images.githubusercontent.com/52337606/90184903-739c5d80-dde8-11ea-966b-666da855e22b.png)

## config.json 配置
```

#將你的config.json内容複製到這裏#
```
{
    "bangumi_dir": "",
    "temp_dir": "",
    "classify_bangumi": true,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 2,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36",
    "use_proxy": false,
    "proxy": "http://user:passwd@example.com:1000",
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "host": "127.0.0.1",
        "port": "5700",
        "SSL": false,
        "api": "send_group_msg",
        "query": {
            "group_id": "123456789"
        }
    },
    "faststart_movflags": false,
    "audio_language": false,
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 14.1,
    "database_version": 2.0
}

## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```
9507 all # 罪惡王冠
10210 all # 工作細胞
8321 all # 單蠢女孩
16557 all # 名偵探柯南：江戶川柯南失蹤事件 ～史上最糟糕的兩天～
16831 all # 富豪刑警 Balance: UNLIMITED
**最好上傳 log 檔案**
[web.log.2020-08-08.log](https://github.com/miyouzi/aniGamerPlus/files/5071330/web.log.2020-08-08.log)
[web.log.2020-08-09.log](https://github.com/miyouzi/aniGamerPlus/files/5071331/web.log.2020-08-09.log)
[web.log.2020-08-10.log](https://github.com/miyouzi/aniGamerPlus/files/5071332/web.log.2020-08-10.log)
[web.log.2020-08-11.log](https://github.com/miyouzi/aniGamerPlus/files/5071333/web.log.2020-08-11.log)
[web.log.2020-08-12.log](https://github.com/miyouzi/aniGamerPlus/files/5071334/web.log.2020-08-12.log)
[web.log.2020-08-13.log](https://github.com/miyouzi/aniGamerPlus/files/5071335/web.log.2020-08-13.log)
[2020-08-14.log](https://github.com/miyouzi/aniGamerPlus/files/5071336/2020-08-14.log)
[web.log](https://github.com/miyouzi/aniGamerPlus/files/5071337/web.log)

**Comment by miyouzi** [comment]
关于你截图里的错误，可能是个Bug，程序把web log和aniGamerPlus log混在一起了。

如果很急的话，目前的可以删除旧的web日志，或者把配置里的```quantity_of_logs```的值调大一点。

**Comment by mikcc123** [comment]
> 关于你截图里的错误，可能是个Bug，程序把网页日志和aniGamerPlus日志混在一起了。
> 
> 如果很急的话，目前的可以删除旧的网络日志，或者把配置里的`quantity_of_logs`的值调大一点。

我重新解压之后正常了，幸好这版本支持控制台，用控制台把之前下载的剩余部分下载了~

**Comment by miyouzi** [comment]
[v20.1](https://github.com/miyouzi/aniGamerPlus/releases/tag/v20.1) 已发布

**Comment by mikcc123** [comment]
> [v20.1](https://github.com/miyouzi/aniGamerPlus/releases/tag/v20.1) 已发布

感谢作者🙏..已经爬完了..几个月之后养养再爬
