### ISSUE TITLE
最近两个版本是不是限速了?还是说动画疯限速了?

### ISSUE THREAD

**Issue by YFTX2015** [miyouzi/aniGamerPlus#61]
从v20开始，下载速度明显不如v19.2快。

**Comment by miyouzi** [comment]
那如果现在回到v19.2速度如何？

从v19.2到v20.1没有做限速的改动，顺便问问用的是自动模式还是手动模式？

**Comment by YFTX2015** [comment]
之前把19.2删了，现在又重下了19.2，自动手动都测了下，发现下载速度较以前均降低了不少，因此排除软件问题，怀疑是动画疯自身限速200M。我持相同的台湾线路在B站仅限台湾地区用idm下载番剧，测出带宽大于400M。另外，作者如果能增加查看，复制并导出视频M3U8链接的功能的话，我还可以用其它专门的M3U8下载工具进行测试，进一步确定原因。

**Comment by miyouzi** [comment]
emmm，另外下m3u8的话，还以为注意需要附带上一些 http header，UA 和 ```Origin: https://ani.gamer.com.tw```，建议可以尝试用其他的工具试看看，比如隔壁的 https://github.com/c0re100/BahamutAnimeDownloader 或者网页脚本 https://greasyfork.org/zh-CN/scripts/408562

**Comment by YFTX2015** [comment]
之前当动画疯1080P还是免费的时候，有大佬在greasyfork上放出了获取1080Pm3u8链接的脚本，不过现在实行会员制之后，就没再看到有这种脚本了。其实我是想用nilaoda的N_m3u8DL-CLI_来测试。

**Comment by miyouzi** [comment]
实际上，Anime.py （Anime对象）里有 get_m3u8_dict() 方法会返回可拿到的各清晰度的m3u8，如果会Python的话，可以创建一个 Anime
实例，然后调用 get_m3u8_dict()

比如把如下代码写到 Anime.py 的最后，然后执行 Anime.py
```
a = Anime(【这里输入一个sn码，纯数字】)
a.get_m3u8_dict()
```

**Comment by YFTX2015** [comment]
Anime. py是现成的程序还是完全需要自己创建?

**Comment by miyouzi** [comment]
现成的，你看下源码，就是源码运行
