### ISSUE TITLE
部分無法下載

### ISSUE THREAD

**Issue by Xari999** [miyouzi/aniGamerPlus#62]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#
抓取影片信息時發生未知錯誤: 'NoneType' object has no attribute 'h1'
異常詳情:
Traceback (most recent call last):
  File "aniGamerPlus.py", line 48, in build_anime
  File "Anime.py", line 55, in __init__
  File "Anime.py", line 111, in __get_title
AttributeError: 'NoneType' object has no attribute 'h1'
## 錯誤截圖
#在這裏附上錯誤的窗口截圖#
![image](https://user-images.githubusercontent.com/69845500/90496701-c4a9aa00-e178-11ea-8f48-a840e7799111.png)

## config.json 配置
```
#將你的config.json内容複製到這裏#
{
    "bangumi_dir": "",
    "temp_dir": "",
    "classify_bangumi": true,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36",
    "use_proxy": false,
    "proxy": "http://user:passwd@example.com:1000",
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "host": "127.0.0.1",
        "port": "5700",
        "SSL": false,
        "api": "send_group_msg",
        "query": {
            "group_id": "123456789"
        }
    },
    "faststart_movflags": false,
    "audio_language": false,
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 14.1,
    "database_version": 2.0
}

## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
460 all
85081 all
110700 all
95849 all
105050 all
78981 all
91971 all
106077 all
101412 all
108006 all
94006 all
103898 all
101403 all
103323 all
94718 all
101812 all
92527 all
96378 all
90088 all
92275 all
90501 all
82332 all
79961 all
79942 all
77234 all
74321 all
71238 all
68752 all
68751 all
64979 all
60976 all
52207 all
56339 all
52874 all
30703 all
103621 all
98322 all
94679 all
91344 all
82333 all
103427 all
104523 all
84866 all
107757 all
106587 all
104191 all
108032 all
108889 all
106807 all
105416 all
106082 all
71917 all
72058 all
61840 all
57498 all
101997 all
63560 all
104419 all
101857 all
106392 all
104526 all
99491 all
437 all
79112 all
79011 all
81932 all
47821 all
84783 all
102099 all
85337 all
33770 all
82573 all
91566 all
90117 all
10733 all
102102 all
78883 all
63284 all
97962 all
90714 all
93688 all
112412 all
112414 all
17962 all
108566 all
108367 all

**最好上傳 log 檔案**
[2020-08-18.log](https://github.com/miyouzi/aniGamerPlus/files/5089639/2020-08-18.log)

**Comment by miyouzi** [comment]
你的sn列表有的動畫已經不存在了，提示“目前無此動畫或動畫授權已到期！”，建議確認報錯的sn上網頁去看一下是不是動畫還在

**Comment by Xari999** [comment]
好的，謝謝

米柚子 <notifications@github.com> 於 2020年8月18日 週二 下午6:28寫道：
