### ISSUE TITLE
下載的時候ffmpeg可以先設定好位元速率嗎?

### ISSUE THREAD

**Issue by nk971111** [miyouzi/aniGamerPlus#64]
我下載1080的影片不過下載下來的總位元速率有5Mbps，導致一部都是900MB左右。
我現在都是在下載完後用ffmpeg來修改總位元速率，不過這樣改要改很久。

**Comment by miyouzi** [comment]
動畫瘋的元速率是和解析度綁定的，不能自行設定元速率，你説的要很久那是轉碼的問題，是另一回事了。

**Comment by nk971111** [comment]
了解
謝謝你的回覆
