### ISSUE TITLE
下載問題

### ISSUE THREAD

**Issue by w0853** [miyouzi/aniGamerPlus#65]
## 問題描述
https://ani.gamer.com.tw/animeVideo.php?sn=14745
無痕模式, 登陸動畫瘋, 勾選保持登入狀態-有做
cookie.txt好像會自己不見,不知為何(在下限制級動畫發現)
明明沒刪除

還有我想問遇到這種網址我該怎麼下cmd指令
我想下14440的1A-9B(共18集）
C:\Users\小美\Desktop\aniGamerPlus_v20.1_windows_32bit\aniGamerPlus.exe -s 14440 -e 1A-9B
結果下載不了

## 錯誤截圖
[](https://imgur.com/a/gucF1PU)

## config.json 配置
{
    "bangumi_dir": "",
    "temp_dir": "",
    "classify_bangumi": true,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36 Edg/84.0.522.63",
    "use_proxy": false,
    "proxy": "http://user:passwd@example.com:1000",
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "host": "127.0.0.1",
        "port": "5700",
        "SSL": false,
        "api": "send_group_msg",
        "query": {
            "group_id": "123456789"
        }
    },
    "faststart_movflags": false,
    "audio_language": false,
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 14.1,
    "database_version": 2.0
}

## sn_list.txt 配置
```因為我用cmd,所以 sn_list.txt我把它淨空
#將你的sn_list.txt内容複製到這裏#
```

**最好上傳 log 檔案**
[log.zip](https://github.com/miyouzi/aniGamerPlus/files/5157797/log.zip)

**Comment by miyouzi** [comment]
> 我想下14440的1A-9B(共18集）

抱歉，目前還不支援非純數字的範圍，未來會考慮支援用 sn 的範圍

> cookie.txt好像會自己不見,不知為何(在下限制級動畫發現)

你的 Log 顯示 cookie 被動畫瘋拒絕了：
```
2020-08-31 02:07:42 Dashboard 通過 Web 控制臺下達了手動任務
2020-08-31 02:07:43 收到cookie重置響應: sn=12083	
2020-08-31 02:07:45 讀取cookie: sn=12083	cookie.txt最後修改時間: 2020-08-30 08:53:57 第0次嘗試
2020-08-31 02:07:45 讀取cookie: sn=12083	新cookie讀取失敗
2020-08-31 02:07:49 讀取cookie: sn=12083	cookie.txt最後修改時間: 2020-08-30 08:53:57 第1次嘗試
2020-08-31 02:07:49 讀取cookie: sn=12083	新cookie讀取失敗
2020-08-31 02:07:51 讀取cookie: sn=12083	cookie.txt最後修改時間: 2020-08-30 08:53:57 第2次嘗試
2020-08-31 02:07:51 讀取cookie: sn=12083	新cookie讀取失敗
2020-08-31 02:07:56 用戶cookie更新失敗! 使用游客身份訪問 
2020-08-31 02:07:57 cookie狀態 已成功標記失效cookie
```

當程式發現 cookie 是無效的時候，會改名成 ```invalid_cookie.txt```，你檢查一下你用來獲取cookie的瀏覽器 UA 是不是和配置文件裏的 ```ua``` 寫的一樣
