### ISSUE TITLE
能否在sn-list增加支援sn範圍的下載方式?

### ISSUE THREAD

**Issue by fs910175** [miyouzi/aniGamerPlus#67]
能否在sn-list增加支援sn範圍的下載方式?
windows版的話沒辦法支援指令下載模式，但最近雙語版本激增，用all抓來補番的話會把雙語都抓下來。

另外請問作者開放斗內嗎?

**Comment by miyouzi** [comment]
在 #65 有提到這個，有計劃支援sn範圍下載，最近比較忙，過幾天寫寫吧，另外Windows也是支援指令下載模式的，需要在 cmd 裏使用。

donate 的話覺得有點麻煩，目前先不考慮吧。

**Comment by miyouzi** [comment]
新版已支援

**Comment by yuzheng14** [comment]
sn_list.txt 能支持范围下载吗？使用的 docker 部署的，通过 sn_list.txt 制定下载目录，比如进击的巨人这部番有双语，想要只下载原版的不想要国语版，README 似乎没有提到 sn_list.txt 可以这么用，只有命令行可以。
