### ISSUE TITLE
下載有時會出錯

### ISSUE THREAD

**Issue by danny740211** [miyouzi/aniGamerPlus#7]
請問為何有些動畫下載會有問題用cmd是可以下載windows版本打開就退掉
看問題應該是會在bangumi裡面連續兩層都有動畫名字
![image](https://user-images.githubusercontent.com/29675187/54522443-34c26800-49a8-11e9-985d-6a1daba0e9e2.png)
![image](https://user-images.githubusercontent.com/29675187/54522493-57548100-49a8-11e9-81b0-6dfc2ed6f344.png)

**Comment by miyouzi** [comment]
可以提供一下 log 嗎？

**Comment by danny740211** [comment]
[2019-03-18.log](https://github.com/miyouzi/aniGamerPlus/files/2977547/2019-03-18.log)

**Comment by danny740211** [comment]
打開windows版本就退掉的那個錯誤訊息不知道為何log不會記錄

**Comment by miyouzi** [comment]
可以貼一下你的配置嗎？```打開windows版本就退掉```是指雙擊打開閃退嗎？你嘗試在cmd中不使用參數直接運行看看有什麽錯誤

**Comment by danny740211** [comment]
關於windows閃退的問題我找到了因為chrome更新版本的關係UA 改一下就正常
現在有問題就是久久會發生 那個下載異常

**Comment by danny740211** [comment]
還是有些怪怪的我用電腦的事件錄影的抓取問題 ,請問這是甚麼問題

錄製工作階段: 2019/3/19 下午 07:16:06 - 下午 07:16:12

問題步驟: 2, 遺失的步驟: 0, 其他錯誤: 0

作業系統: 7601.24387.amd64fre.win7sp1_ldr_escrow.190305-1700 6.1.1.0.2.1

問題步驟 1: 使用者在 "名稱 (可編輯的文字)" (於 "aniGamerPlus" 中) 按一下左鍵
程式: Windows 檔案總管, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft Corporation, EXPLORER.EXE, EXPLORER.EXE
UI 元素: 名稱, aniGamerPlus, 項目檢視, DirectUIHWND, ShellView, SHELLDLL_DefView, CtrlNotifySink, DirectUIHWND, DUIViewWndClassName, aniGamerPlus, ShellTabWindowClass, aniGamerPlus, CabinetWClass

問題步驟 2: 使用者在 "名稱 (可編輯的文字)" (於 "aniGamerPlus" 中) 按兩下左鍵
程式: Windows 檔案總管, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft Corporation, EXPLORER.EXE, EXPLORER.EXE
UI 元素: 名稱, aniGamerPlus, 項目檢視, DirectUIHWND, ShellView, SHELLDLL_DefView, CtrlNotifySink, DirectUIHWND, DUIViewWndClassName, aniGamerPlus, ShellTabWindowClass, aniGamerPlus, CabinetWClass

**Comment by danny740211** [comment]
配置檔ua都更新到新的阿但還是會發生閃退

[config.zip](https://github.com/miyouzi/aniGamerPlus/files/2982997/config.zip)

**Comment by miyouzi** [comment]
額……事件錄影看不出來什麽，閃退問題你在cmd裏不帶參數直接回車，和你雙擊左鍵是一樣的，看看提示什麽。

**Comment by danny740211** [comment]
好怪喔我找到是哪個問題
sn_list 這明明是txt應該用記事本就可以啊
我拿sample重新另存新檔軟體又恢復了

**Comment by miyouzi** [comment]
使用系統自帶的記事本編輯txt會帶上 BOM 頭，BOM 頭會給程序的處理帶來不便，推薦是使用 notepad++ 進行編輯，aniGamerPlus 會自動識別 BOM 頭並自動去掉，可能是這個處理的過程發生什麽錯誤，也可能是格式不對，可以提供一下 sn_list 檔案麽？

**Comment by danny740211** [comment]
[sn_list111.txt](https://github.com/miyouzi/aniGamerPlus/files/2983061/sn_list111.txt)
這個是舊的

**Comment by miyouzi** [comment]
你的 sn_list 編碼是 Big5，但是 aniGamerPlus 是以 UTF-8 編碼讀取的，你把編碼改成 UTF-8 試試

**Comment by danny740211** [comment]
好我測試看看

**Comment by danny740211** [comment]
不知為何我改了還是不行
我直接拿sample把內容貼過去就是可以
且這個檔案notepad 另存成新的也是不行
沒關係下次我不行我就直接重新存過檔案

**Comment by miyouzi** [comment]
你的這個問題應該是編碼問題，我在下一個版本加入自動處理非UTF-8編碼，到時候你再試試

**Comment by danny740211** [comment]
好的謝謝您幫忙解決問題

**Comment by miyouzi** [comment]
[v10.2](https://github.com/miyouzi/aniGamerPlus/releases/tag/v10.2) 已更新，嘗試使用一下？

**Comment by danny740211** [comment]
測試沒問題
有問題的txt也可以自動轉換了
