### ISSUE TITLE
希望添加自动更新弹幕功能

### ISSUE THREAD

**Issue by timk-lalala** [miyouzi/aniGamerPlus#75]
不知道作者是否可以在后期添加自动更新弹幕功能

**Comment by miyouzi** [comment]
是説自動模式下隔幾天重新下載一次彈幕？

**Comment by zgbjwzh** [comment]
可以手动更新或者自动模式下指定间隔时间重新下载弹幕

另外一题现在自动下载弹幕的时候偶尔会出现后半段乱码的情况，需要手动转换编码

**Comment by miyouzi** [comment]
> 偶尔会出现后半段乱码的情况，需要手动转换编码

能具体说说嘛，你说的转码是转成什么码，转码后可以解决乱码问题是吗？

**Comment by zgbjwzh** [comment]
Notepad++手动先转成ANSI然后再转成UTF-8，就能解决后面乱码的问题

**Comment by zgbjwzh** [comment]
我直接拿Notepad++直接打开不乱码，但是播放器打开乱码，PC：Potplayer/MPC，手机：MX播放器
我测试后发现应该就是编码问题

**Comment by miyouzi** [comment]
如果你可以提供问题 sn 或者问题 ass 文件就更好了，弹幕的问题可能需要 @a20034294 帮忙看看。

**Comment by a20034294** [comment]
可以請你提供轉出的 ass file 以及 sn 嗎
是偶發出現還是常態呢 謝謝

**Comment by zgbjwzh** [comment]
偶发，晚上下班我再提供ass file和sn码

**Comment by zgbjwzh** [comment]
[【動畫瘋】請問您今天要來點兔子嗎？BLOOM[6][1080P].zip](https://github.com/miyouzi/aniGamerPlus/files/5541926/BLOOM.6.1080P.zip)
SN:18549 #点兔

**Comment by zgbjwzh** [comment]
字幕在14分之后

**Comment by zgbjwzh** [comment]
> 如果您可以提供问题sn或问题ass文件就更好了，弹幕的问题可能需要@ a20034294帮忙看看。
[转码后的文件.zip](https://github.com/miyouzi/aniGamerPlus/files/5541941/default.zip)
[Snipaste_2020-11-15_15-08-19](https://user-images.githubusercontent.com/17139396/99179025-7777ad00-2754-11eb-90b5-861728d4395d.png)
转码前后CRC32对比

**Comment by zgbjwzh** [comment]
> 如果你可以提供问题 sn 或者问题 ass 文件就更好了，弹幕的问题可能需要 @a20034294 帮忙看看。

转码前后对比
[转码后的文件.zip](https://github.com/miyouzi/aniGamerPlus/files/5541944/default.zip)
![Snipaste_2020-11-15_15-08-19](https://user-images.githubusercontent.com/17139396/99179050-b73e9480-2754-11eb-94c4-85f5cb4c8345.png)
CRC32前后对比

**Comment by a20034294** [comment]
尷尬了 我看起來沒有問題

**Comment by a20034294** [comment]
這幾天比較有空 仔細研究了一下
發生的原因應該是用的系統 OR 軟體不支援 4 bytes 的 utf8 所致
可是彈幕本身是支援的，常見的 4 bytes utf8 字元像是 emoji 等
在使用 notepad 轉碼過後，會將 4 bytes 的字元轉成兩個 "?" 為 2 bytes
你所提供的 ass 中共有兩處有 emoji 因此轉碼過後總共少 4 bytes

**Comment by zgbjwzh** [comment]
> 这几天比较有空仔细研究了一下
> 发生的原因应该是用的系统或软体不支持4字节的utf8所致
> 可是弹幕本身是支持的，常见的4字节utf8字元像是emoji等
> 在使用记事本转码过后，可以重新设置4个字节的字元转成两个“？” 为2字节您
> 所提供的屁股中共有两处有emoji因此转码过后总共少4字节

感谢大佬回复

**Comment by zgbjwzh** [comment]
> 這幾天比較有空 仔細研究了一下
> 發生的原因應該是用的系統 OR 軟體不支援 4 bytes 的 utf8 所致
> 可是彈幕本身是支援的，常見的 4 bytes utf8 字元像是 emoji 等
> 在使用 notepad 轉碼過後，會將 4 bytes 的字元轉成兩個 "?" 為 2 bytes
> 你所提供的 ass 中共有兩處有 emoji 因此轉碼過後總共少 4 bytes

感谢大佬回复

**Comment by a20034294** [comment]
另外自動更新我覺得比較困難
手動更新倒沒什麼問題
可能會設計成 only danmu 模式

**Comment by zgbjwzh** [comment]
> 另外自動更新我覺得比較困難
> 手動更新倒沒什麼問題
> 可能會設計成 only danmu 模式

我觉得能更新就成，哈哈哈

**Comment by timk-lalala** [comment]
现阶段-i与-d连用时无法自动下载到sn_list设定的目录下，希望可以添加一键更新所有字幕

**Comment by miyouzi** [comment]
v24.0 以上版本已实现
