### ISSUE TITLE
沒辦法添加手動任務

### ISSUE THREAD

**Issue by andy7557** [miyouzi/aniGamerPlus#79]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#
沒辦法利用 WEB 控制台添加手動任務

## 錯誤截圖
#在這裏附上錯誤的窗口截圖#
![image](https://user-images.githubusercontent.com/69379745/98813084-9af1dd80-245e-11eb-9d9a-89e60a9ecf9a.png)

## config.json 配置
```
#將你的config.json内容複製到這裏#
```
{
    "bangumi_dir": "D:\\\\\\\\Download\\\\\\\\anime",
    "temp_dir": "C:\\\\\\\\",
    "classify_bangumi": false,
    "check_frequency": 15,
    "download_resolution": "1080",
    "lock_resolution": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "[動畫瘋] ",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36",
    "use_proxy": false,
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "query": [
            "http://127.0.0.1:5700/send_group_msg?group_id=123456789"
        ],
        "message_suffix": "",
        "msg_argument_name": "message"
    },
    "faststart_movflags": false,
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 15.1,
    "database_version": 2.0,
    "audio_language": false,
    "proxy": "socks5://127.0.0.1:1080",
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "danmu": false,
    "use_mobile_api": false,
    "mobile_ads_time": 3
}

## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```
18427 # 魔女之旅
18431 # 王之逆襲：意志的繼承者
18432 # 排球少年！！第四季 Part 2
18437 # 魔法科高中的劣等生 來訪者篇
18215 # 熊熊勇闖異世界
18554 # 無能力者娜娜
18626 # 咒術迴戰
18623 # 土下座跪求給看
18603 # 我立於百萬生命之上

**最好上傳 log 檔案**
[2020-11-11.log](https://github.com/miyouzi/aniGamerPlus/files/5524024/2020-11-11.log)

**Comment by miyouzi** [comment]
我測試沒有這個問題，你瀏覽器有開廣告過濾插件一類的東西麽？嘗試關閉看看？

**Comment by andy7557** [comment]
用無痕就正常耶，不過回來擴充全關了還是不行

**Comment by miyouzi** [comment]
Ctrl+F5試試？另外你有没有看到下載彈幕的開關？

**Comment by andy7557** [comment]
Ctrl+F5 就正常了!  彈幕開關本來就有看到

**Comment by andy7557** [comment]
感謝協助解決，結案~
