### ISSUE TITLE
請問下載有錯誤

### ISSUE THREAD

**Issue by danny740211** [miyouzi/aniGamerPlus#8]
[2019-04-12.log](https://github.com/miyouzi/aniGamerPlus/files/3072837/2019-04-12.log)
不知道這下載錯誤是甚麼
下載異常: sn=12098 發生未知錯誤: 'BAHARUNE'

**Comment by miyouzi** [comment]
似乎cookie檔案出了問題，檢查cookie是否正確？

**Comment by danny740211** [comment]
我重貼好幾次
案下載都會cookie都會被轉換調
不知道為何

**Comment by danny740211** [comment]
還專程用BahamutAnimeDownloader 測試是正常的
所以應該是cookie檔案會轉換的問題

**Comment by danny740211** [comment]
[cookie.txt](https://github.com/miyouzi/aniGamerPlus/files/3072895/cookie.txt)
轉成這樣的形式
![image](https://user-images.githubusercontent.com/29675187/56031620-9d57f700-5d52-11e9-9ba5-b55550086298.png)
貼上去時貼上去時明明是這樣的
按了下載就轉換掉了

**Comment by miyouzi** [comment]
```按了下載``` 指的是？

**Comment by imball** [comment]
應該是這麼說，現在動畫瘋的cookie不知道為何一直在更新，然後如果去抓前面的cookie再按了aniGamerPlus.exe後就會出現「發生未知錯誤: 'BAHARUNE'」這樣的字眼
![1555068341248](https://user-images.githubusercontent.com/49181460/56034082-d2674800-5d58-11e9-961a-2e38df8301e9.jpg)

**Comment by danny740211** [comment]
謝謝imball 大大的解釋
就是這樣沒錯,但我發現其實cookie其實沒變只是aniGamerPlus.exe按下去cookie的檔案會自己轉換成其他的
導致無法下載

**Comment by miyouzi** [comment]
已復現，巴哈的cookie進行了改動，現在進行適配。

**Comment by miyouzi** [comment]
已更新，看看如何？

**Comment by imball** [comment]
@miyouzi 感謝大大，更新過後已經確定可以繼續下載使用。

**Comment by danny740211** [comment]
@miyouzi  謝謝修復確定可以用啦
個人資料已經刪除了

**Comment by zero20089** [comment]
最近發現 怎麼不能單集下載? 我前幾天遇到 全集下載之後 發現缺集~ 不管打SN多少 還是沒辦法抓單集~
有沒有辦法修復 單集下載問題?

**Comment by miyouzi** [comment]
@zero20089 能具體説一下提示了什麽錯誤麽？是否有提供cookie？

**Comment by zero20089** [comment]
> @zero20089 能具體説一下提示了什麽錯誤麽？是否有提供cookie？
剛剛測試其他動漫 輕音部第二季 結果~~
我只看到 SN 少三個(1~3話) 突然變成抓特別篇1~ 3+1本篇4~24
![未命名](https://user-images.githubusercontent.com/49590648/56081093-e172f680-5e3b-11e9-9394-573f556168d2.jpg)

**Comment by miyouzi** [comment]
@zero20089 動畫瘋的特別篇部分改版了，目前正在修，另外游客身份下載遇到 ```「發生未知錯誤: 'BAHARUNE'」``` 問題也正在修

**Comment by zero20089** [comment]
> @zero20089 動畫瘋的特別篇部分改版了，目前正在修，另外游客身份下載遇到 `「發生未知錯誤: 'BAHARUNE'」` 問題也正在修

游客身份下載遇到 `「發生未知錯誤: 'BAHARUNE'」 這個問題  COOKIE 只能填上去可以~

動畫瘋特別篇問題還在修??~ 如果作者可以更新問題 單集下載 或 全集下載 就好~
但是 sn_list.txt 要打編輯 sn 後面打 單集或all (覺得建議)

**Comment by miyouzi** [comment]
> 如果作者可以更新問題 單集下載 或 全集下載 就好~
> 但是 sn_list.txt 要打編輯 sn 後面打 單集或all (覺得建議)

這段話沒怎麽懂，上面你舉例 K-ON 的問題是所有帶特別篇的番劇會觸發的，這部分代碼已經寫好了
```sn_list.txt``` 是設計給大量下載和自動下載的，能夠記錄每集的下載狀態，如果sn後面沒有寫模式，則是使用 ```config.json``` 中指定的默認模式，單集下載沒計劃加入 sn_list，需要單集下載用命令行模式即可

**Comment by zero20089** [comment]
> @zero20089
> 
> > 如果作者可以更新問題 單集下載 或 全集下載 就好~
> > 但是 sn_list.txt 要打編輯 sn 後面打 單集或all (覺得建議)
> 
> 這段話沒怎麽懂，上面你舉例 K-ON 的問題是所有帶特別篇的番劇會觸發的，這部分代碼已經寫好了
> `sn_list.txt` 是設計給大量下載和自動下載的，能夠記錄每集的下載狀態，如果sn後面沒有寫模式，則是使用 `config.json` 中指定的默認模式，單集下載沒計劃加入 sn_list，需要單集下載用命令行模式即可

單集下載怎麼用命令打?

**Comment by imball** [comment]
@zero20089 你如果不會用命令單集下載的話要不要我幫你下載然後再給你，雖然說作者已經在README.md寫的很清楚了

**Comment by zero20089** [comment]
> @zero20089 你如果不會用命令單集下載的話要不要我幫你下載然後再給你，雖然說作者已經在README.md寫的很清楚了

是的~我都試過打CMD~ 還是不行~ 不知道怎麼打XD

**Comment by imball** [comment]
你要K-on!! 第二季的1跟2集對吧

**Comment by zero20089** [comment]
> 你要K-on!! 第二季的1跟2集對吧

1 2 3 才對~ 不過 你要給我 怎麼指令打 ~ 單集也可以  README.md我有看 試過好幾次 還是顯示不是內部或外部命令....

**Comment by imball** [comment]
如果你真心想要自己下載的話我是可以稍微花點時間交你怎麼用，但是作者剛剛已經提到他已經修好了這部分的BUG，單集下載這東西就不太需要會了
他是另外用CMD的方式下載。

**Comment by zero20089** [comment]
> 如果你真心想要自己學會下載的話我是可以稍微花點時間教你怎麼用，但是作者剛剛已經提到他已經修好了這部分的BUG，單集下載這東西就不太需要會了
> 他是另外用CMD的方式下載。
 只等作者修好~~ 我都用CMD 打的 ~ 搞到心累~ 謝謝~~

**Comment by miyouzi** [comment]
@zero20089 @imball v11已更新，測試下看看

**Comment by imball** [comment]
@miyouzi 非常感謝，經過測試沒有問題
![1555170106363](https://user-images.githubusercontent.com/49181460/56081961-bab9bd80-5e45-11e9-8c76-1bbda6c839be.jpg)
