### ISSUE TITLE
請問下載出現winError 2

### ISSUE THREAD

**Issue by leonard-lin-joker** [miyouzi/aniGamerPlus#80]
[2020-11-17.log](https://github.com/miyouzi/aniGamerPlus/files/5549315/2020-11-17.log)
![Error](https://user-images.githubusercontent.com/74565774/99301221-95dec500-2888-11eb-9129-d8063213ff52.PNG)
我是新使用者，使用的是exe版本，不曉得這個issue是什麼狀況。

**Comment by miyouzi** [comment]
可以放一下配置文件嗎？我這邊用Web解析沒問題

**Comment by LiMoon** [comment]
估計是 windows 的資料夾判斷錯誤問題。

FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'E:\\aniGamerPlus\\temp\\【動畫瘋】魔法科高中的劣等生 來訪者篇[1][1080P].MERGING.mp4'

exe判斷檔案在不在應該要是，可能是代碼判斷寫錯了？
'E:\aniGamerPlus\temp\【動畫瘋】魔法科高中的劣等生 來訪者篇[1][1080P].MERGING.mp4' 才對。

**Comment by miyouzi** [comment]
問一下用的 ffmpeg 版本是？

**Comment by LiMoon** [comment]
> 問一下用的 ffmpeg 版本是？

git-2020-05-13-b12b053

**Comment by LiMoon** [comment]
看起來是 FFMPEG 版本太舊的關係？
剛才更新到最新版本後，就正常了。

**Comment by miyouzi** [comment]
> 看起來是 FFMPEG 版本太舊的關係？
> 剛才更新到最新版本後，就正常了。
> 可能要在備註提醒 FFMPEG 要最新版本

之前有一段版本的 FFMPEG 是有問題的（對於當時來説就是新版有問題），然後現在又修好了，大概是這麽個情況

**Comment by leonard-lin-joker** [comment]
> > 看起來是FFMPEG版本太舊的關係？
> > 剛才更新到最新版本後，就正常了。
> > 可能要在備註提醒FFMPEG要最新版本
> 
> 之前有一段版本的FFMPEG是有問題的（對於當時來說就是新版有問題），然後現在又修好了，大概是這麼個情況

我重新下載其他的ffmpeg就可以使用了
