### ISSUE TITLE
酷Q机器人好像已经关了。

### ISSUE THREAD

**Issue by DirectLinkSs** [miyouzi/aniGamerPlus#81]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#

## 錯誤截圖
#在這裏附上錯誤的窗口截圖#

## config.json 配置
```
#將你的config.json内容複製到這裏#
```

## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```

**最好上傳 log 檔案**

可以清理一些代码，或者换用其他比如  Server酱

**Comment by miyouzi** [comment]
酷Q目前可以使用 [go-cqhttp](https://github.com/Mrs4s/go-cqhttp) 替代。

另外配置文件为了兼容各类 api 接口，已经采用了兼容性更强的配置格式，你可以自己构造 api 链接，aniGamerPlus 会加上消息参数后 get 链接，支持一个任务完成后对多个 api 链接发起请求。

你提到的Server酱的文档，配置可以这么写试看看
PS：```msg_argument_name``` 是消息正文的参数名。
```json
"coolq_notify": true,
    "coolq_settings": {
        "msg_argument_name": "text",
        "message_suffix": "追加的資訊",
        "query": [
            "https://sc.ftqq.com/[SCKEY].send"
        ]
    }
```
上述配置发起的链接示例：
```
https://sc.ftqq.com/[SCKEY].send?text=%e8%bf%bd%e5%8a%a0%e7%9a%84%e8%b3%87%e8%a8%8a
```

**Comment by DirectLinkSs** [comment]
了解，谢谢。
