### ISSUE TITLE
下載到一半怎麼退出?(EXE 檔案執行)

### ISSUE THREAD

**Issue by karta282036** [miyouzi/aniGamerPlus#84]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#
下載到一半怎麼退出?
直接關掉黑視窗嗎?有指令可以退出嗎?怕直接關閉黑視窗有問題。

**Comment by miyouzi** [comment]
直接關掉沒什麽問題

**Comment by LiMoon** [comment]
在視窗内按 Ctrl + C 就能強制關閉了。
