### ISSUE TITLE
下載影片似乎不完整

### ISSUE THREAD

**Issue by bmanex** [miyouzi/aniGamerPlus#89]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#
下載下來動畫似乎會缺少最後一片段
## 錯誤截圖
#在這裏附上錯誤的窗口截圖#
![image](https://user-images.githubusercontent.com/22031843/103461281-22214a80-4d58-11eb-9426-8aeb7518a129.png)
![image](https://user-images.githubusercontent.com/22031843/103461282-264d6800-4d58-11eb-8ba3-caf4adf5ea61.png)
PS 不知道是跨年了動畫瘋調整設定還是這部動畫比較特別，因為我在2020之前下載的影片就是完整的
抱歉麻煩您了
## config.json 配置
```
#將你的config.json内容複製到這裏#
```
{
    "bangumi_dir": "D:\\\\\\\\\\\\\\\\Anime",
    "temp_dir": "",
    "classify_bangumi": true,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": false,
    "default_download_mode": "all",
    "use_copyfile_method": false,
    "multi-thread": 5,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 5,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36",
    "use_proxy": false,
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "query": [
            "http://127.0.0.1:5700/send_group_msg?group_id=123456789"
        ],
        "message_suffix": "",
        "msg_argument_name": "message"
    },
    "faststart_movflags": false,
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 15.1,
    "database_version": 2.0,
    "audio_language": false,
    "proxy": "socks5://127.0.0.1:1080",
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "ads_time": 25,
    "danmu": false,
    "use_mobile_api": false,
    "mobile_ads_time": 3
}
## sn_list.txt 配置
```
#將你的sn_list.txt内容複製到這裏#
```
18215 largest-sn <熊熊勇闖異世界>
18370 largest-sn <無能力者娜娜>
18427 largest-sn <魔女之旅>
18626 largest-sn <咒術迴戰>
11419 all <佐賀偶像是傳奇>
**最好上傳 log 檔案**
[2021-01-02.log](https://github.com/miyouzi/aniGamerPlus/files/5760501/2021-01-02.log)

**Comment by miyouzi** [comment]
實際看下來有缺畫面嗎？（可能只是時長顯示的問題？

**Comment by kaiconan** [comment]
有沒有試過更新 ffmpeg ？
Windows 版選擇：
請移動至 `https://www.ffmpeg.org/download.html#build-windows` 選擇 `Windows builds by BtbN` 下載覆蓋並更新，看看能不能解決。
