### ISSUE TITLE
命令行使用問題

### ISSUE THREAD

**Issue by imball** [miyouzi/aniGamerPlus#9]
想請問用命令列下載時，輸入了python aniGamerPlus.py （後面省略） 會跑出下列字眼
Traceback (most recent call last):
  File "aniGamerPlus.py", line 21, in <module>
    import Config
  File "D:\aniGamerPlus_v10.3_windows_64bit\Config.py", line 8, in <module>
    import os, json, re, sys, requests, time, random, codecs, chardet
ModuleNotFoundError: No module named 'requests'
想請問是我有設定沒有調到還是哪裡有問題?

還有追加一個問題，在用aniGamerPlus.exe下載番的情形下，有發現如果該番如果有特別篇時，程式不會下載該番與特別篇數字一樣的集數(e.g. 工作O胞 有1-13和特別篇1，下載時會漏掉第1集，只會下載2-13及特別篇1)。

附圖：
![1555128157496](https://user-images.githubusercontent.com/49181460/56074440-40f1e780-5de5-11e9-8d6a-3a1bb507facd.jpg)

**Comment by miyouzi** [comment]
源碼運行缺少依賴庫，安裝依賴在readme有說明。

第二個問題是使用全集下載模式？

**Comment by imball** [comment]
第一個問題已經解決，感謝提醒！
關於第二個問題是在sn_list.txt這個檔案中打all時是會這樣
至於在config.json中更改下載模式倒是沒有嘗試過

**Comment by miyouzi** [comment]
問題已複現，晚些時候進行修復

**Comment by miyouzi** [comment]
[v11](https://github.com/miyouzi/aniGamerPlus/releases/tag/v11) 版本已修復
