### ISSUE TITLE
含有特別篇SP的劇集不能解析出正片

### ISSUE THREAD

**Issue by joseph-cheung** [miyouzi/aniGamerPlus#91]
關於我轉生變成史萊姆這檔事 第二季 只能解析出特別篇SP，然後就停止不動了，正片更新了一話，無法自動下載

**Comment by joseph-cheung** [comment]
sn=20530

**Comment by Hoshino0881118** [comment]
我使用exe的版本可以正常更新並下載
您要不要使用乾淨的作業系統重新試試?

**Comment by da21510** [comment]
我用v22.0 的.py檔 也有一樣的問題

**Comment by miyouzi** [comment]
給一下配置文件和 log

**Comment by da21510** [comment]
[2021-02-28.log](https://github.com/miyouzi/aniGamerPlus/files/6055905/2021-02-28.log)

[config.json.txt](https://github.com/miyouzi/aniGamerPlus/files/6055908/config.json.txt)

基本上就是咒術迴戰跟轉生史萊姆這兩部

**Comment by miyouzi** [comment]
> [2021-02-28.log](https://github.com/miyouzi/aniGamerPlus/files/6055905/2021-02-28.log)
> 
> [config.json.txt](https://github.com/miyouzi/aniGamerPlus/files/6055908/config.json.txt)
> 
> 基本上就是咒術迴戰跟轉生史萊姆這兩部

你用的 ```latest``` 模式，```latest``` 模式的説明是 ```下載此番劇最後一集(即網頁上顯示排最後的一集)``` 這麽看來也沒錯，SP 在網頁顯示確實是排在最後的。

你可以換成 ```largest-sn``` 模式，這個模式是 ```下載此番劇最近上傳的一集(即sn最大的一集)``` ，或者你乾脆用 ```all``` 模式下載全集
