### ISSUE TITLE
檔名與番據目錄名稱問題

### ISSUE THREAD

**Issue by Rex1152** [miyouzi/aniGamerPlus#94]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#
想要自訂folder name=工作細胞
filename=工作細胞 S02E01[1080P].mp4這樣
目前想到的是
folder name可以從 sn_list去控制
filename 01 可用"zerofill": 1,  # 劇集名補零, 填寫補足位數, 例: 填寫 2 劇集名為 01, 填寫 3 劇集名為 001
但S02E這幾個字目前似乎無法達到此目的

**Comment by miyouzi** [comment]
v24.0 版本以上支持 https://github.com/miyouzi/aniGamerPlus/pull/181
