### ISSUE TITLE
纯v6的vps无法获取本机IP地址导致无法启动

### ISSUE THREAD

**Issue by Sakura1338** [miyouzi/aniGamerPlus#95]
## 問題描述
#在這裏詳細説明你遇到了什麽問題#
在开启了外部访问的情况下，用于离线下载的VPS没有公网的ipv4 ip，程序提示网络不可用，无法获取到本地ip地址，随后报错自动退出
## 錯誤截圖
#在這裏附上錯誤的窗口截圖#
![image](https://user-images.githubusercontent.com/61232882/108064554-d0c6e380-7097-11eb-9735-f68648684dbc.png)
## config.json 配置
```
#將你的config.json内容複製到這裏#
```
{
    "bangumi_dir": "/root/onedrive/ani",
    "temp_dir": "",
    "classify_bangumi": true,
    "check_frequency": 5,
    "download_resolution": "720",
    "lock_resolution": false,
    "default_download_mode": "all",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36",
    "use_proxy": true,
    "proxy": "socks5://127.0.0.1:1080",
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "msg_argument_name": "message",
        "message_suffix": "追加的資訊",
        "query": [
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
        ]
    },
    "telebot_notify": false,
    "telebot_token": "",
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": false,
    "danmu": false,
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "mobile_ads_time": 3,
    "use_dashboard": true,
    "dashboard": {
        "host": "0.0.0.0",
        "port": 19999,
        "SSL": false,
        "BasicAuth": true,
        "username": "admin",
        "password": "0000"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 15.2,
    "database_version": 2.0
}

**Comment by miyouzi** [comment]
看看 ```ip a``` 和 `ifconfig`

**Comment by Sakura1338** [comment]
> 看看 `ip a` 和 `ifconfig`

![image](https://user-images.githubusercontent.com/61232882/108067916-68c6cc00-709c-11eb-8ac3-10a1ee312c7e.png)

**Comment by miyouzi** [comment]
你这连个局域网v4地址都没有，你试试配置改成 `"host": "127.0.0.1"`，然后搭配反向代理软件使用吧（比如nginx）

**Comment by Sakura1338** [comment]
> 你这连个局域网v4地址都没有，你试试配置改成 `"host": "127.0.0.1"`，然后搭配反向代理软件使用吧（比如nginx）

好的，谢谢了😝。通过tengine反代成功实现外网访问了
