### ISSUE TITLE
無法解析任何sn

### ISSUE THREAD

**Issue by Hoshino0881118** [miyouzi/aniGamerPlus#97]
我最後一次成功下載的時間點是2/23 10:00左右
到現在都無法成功下載
請問有其他人是一樣的狀況嗎??
[2021-02-25.log](https://github.com/miyouzi/aniGamerPlus/files/6041289/2021-02-25.log)

[config.txt](https://github.com/miyouzi/aniGamerPlus/files/6041292/config.txt)

**Comment by miyouzi** [comment]
你的 sn_list 給一下

**Comment by Hoshino0881118** [comment]
我的sn_list很單純
[sn_list.txt](https://github.com/miyouzi/aniGamerPlus/files/6042277/sn_list.txt)

**Comment by miyouzi** [comment]
你這是想幹嘛，把整個動畫瘋網站扒下來嗎

**Comment by Hoshino0881118** [comment]
不是想 是已經%下來了
不會看得再刪掉而已

**Comment by miyouzi** [comment]
情況應該就是 log 裏字面寫的，這個 sn 動畫不存在，你直接从 1 開始，很多已經下架了不奇怪

**Comment by Hoshino0881118** [comment]
剛剛用瀏覽器去看 已經查到原因了
IP被封鎖 需要手動驗證才能
![image](https://user-images.githubusercontent.com/26840198/109144998-e1184600-779c-11eb-94b7-7399b7d150a2.png)
sn=1的部分還沒被下架

**Comment by DirectLinkSs** [comment]
可以的，巴哈一共不到16000集视频，你这序号都排到20000+了。

**Comment by miyouzi** [comment]
> 可以的，巴哈一共不到16000集视频，你这序号都排到20000+了。

说起来，你是用 IP 池随机 IP 检查更新，有更新再传 cookie 么（好像同一个cookie会风控）

**Comment by Hoshino0881118** [comment]
> 可以的，巴哈一共不到16000集视频，你这序号都排到20000+了。

會排到20000+是因為那邊也有視頻

**Comment by Hoshino0881118** [comment]
> > 可以的，巴哈一共不到16000集视频，你这序号都排到20000+了。
> 
> 说起来，你是用 IP 池随机 IP 检查更新，有更新再传 cookie 么（好像同一个cookie会风控）

會被鎖應該是因為我用固定公網IP掃了一陣子的關西
我更新的方式是設定完後直接啟動(.exe)

**Comment by DirectLinkSs** [comment]
> > 可以的，巴哈一共不到16000集视频，你这序号都排到20000+了。
> 
> 说起来，你是用 IP 池随机 IP 检查更新，有更新再传 cookie 么（好像同一个cookie会风控）

没有，就一个ip，是有风控，不过好像重新登录就行了。
