### ISSUE TITLE
命令行模式会读取config中的哪些内容

### ISSUE THREAD

**Issue by BraveSail** [miyouzi/aniGamerPlus#98]
## 問題描述
看了说明中的命令行支持参数，没有檔名添加解析度、影片檔名前綴、影片檔名後綴这些参数，当使用命令行模式的时候这些参数是否会从config中读取？

**Comment by miyouzi** [comment]
會，但是番劇名稱無法自定義。

**Comment by BraveSail** [comment]
好的谢谢
